<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.51">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Resampling statistics - 29&nbsp; Correlation and Causation</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./how_big_sample.html" rel="next">
<link href="./reliability_average.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<script type="text/javascript">
  $(document).ready(function() {
    $("table").addClass('lightable-paper lightable-striped lightable-hover')
  });
</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="style.css">
<link rel="stylesheet" href="font-awesome.min.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./correlation_causation.html"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Correlation and Causation</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Resampling statistics</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R edition</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface_third.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface to the third edition</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface_second.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface to the second edition</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./resampling_method.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The resampling method</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./what_is_probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">What is probability?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./about_technology.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Introducing R and the RStudio notebook</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./resampling_with_code.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Resampling with code</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./resampling_with_code2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">More resampling with code</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sampling_tools.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Tools for samples and sampling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability_theory_1a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Probability Theory, Part 1</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability_theory_1b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Probability Theory Part I (continued)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./more_sampling_tools.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Two puzzles and more tools</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability_theory_2_compound.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Probability Theory, Part 2: Compound Probability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability_theory_3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Probability Theory, Part 3</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability_theory_4_finite.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Probability Theory, Part 4: Estimating Probabilities from Finite Universes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sampling_variability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">On Variability in Sampling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./monte_carlo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">The Procedures of Monte Carlo Simulation (and Resampling)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./standard_scores.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Ranks, Quantiles and Standard Scores</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference_ideas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">The Basic Ideas in Statistical Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Introduction to Statistical Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./point_estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Point Estimation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./framing_questions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Framing Statistical Questions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./testing_counts_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Hypothesis-Testing with Counted Data, Part 1</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./significance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">The Concept of Statistical Significance in Testing Hypotheses</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./testing_counts_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">The Statistics of Hypothesis-Testing with Counted Data, Part 2</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./testing_measured.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">The Statistics of Hypothesis-Testing With Measured Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./testing_procedures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">General Procedures for Testing Hypotheses</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./confidence_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Confidence Intervals, Part 1: Assessing the Accuracy of Samples</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./confidence_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Confidence Intervals, Part 2: The Two Approaches to Estimating Confidence Intervals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./reliability_average.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Some Last Words About the Reliability of Sample Averages</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./correlation_causation.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Correlation and Causation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./how_big_sample.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">How Large a Sample?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bayes_simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Bayesian Analysis by Simulation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./exercise_solutions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Exercise Solutions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./acknowlegements.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Acknowledgements</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./technical_note.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Technical Note to the Professional Reader</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#preview" id="toc-preview" class="nav-link active" data-scroll-target="#preview"><span class="header-section-number">29.1</span> Preview</a></li>
  <li><a href="#introduction-to-correlation-and-causation" id="toc-introduction-to-correlation-and-causation" class="nav-link" data-scroll-target="#introduction-to-correlation-and-causation"><span class="header-section-number">29.2</span> Introduction to correlation and causation</a></li>
  <li><a href="#a-note-on-association-compared-to-testing-a-hypothesis" id="toc-a-note-on-association-compared-to-testing-a-hypothesis" class="nav-link" data-scroll-target="#a-note-on-association-compared-to-testing-a-hypothesis"><span class="header-section-number">29.3</span> A Note on Association Compared to Testing a Hypothesis</a>
  <ul class="collapse">
  <li><a href="#sec-athletic-iq-ranks" id="toc-sec-athletic-iq-ranks" class="nav-link" data-scroll-target="#sec-athletic-iq-ranks"><span class="header-section-number">29.3.1</span> Example: Is Athletic Ability Directly Related to Intelligence?</a></li>
  <li><a href="#example-athletic-ability-and-i.q.-a-third-way" id="toc-example-athletic-ability-and-i.q.-a-third-way" class="nav-link" data-scroll-target="#example-athletic-ability-and-i.q.-a-third-way"><span class="header-section-number">29.3.2</span> Example: Athletic ability and I.Q. a third way</a></li>
  </ul></li>
  <li><a href="#correlation-sum-of-products" id="toc-correlation-sum-of-products" class="nav-link" data-scroll-target="#correlation-sum-of-products"><span class="header-section-number">29.4</span> Correlation: sum of products</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">29.5</span> Exercises</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-correlation-causation" class="quarto-section-identifier"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Correlation and Causation</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Draft page partially ported from original PDF
</div>
</div>
<div class="callout-body-container callout-body">
<p>This page is an automated and partial import from the <a href="https://resample.com/content/text/27-Chap-23.pdf">original second-edition PDF</a>.</p>
<p>We are in the process of updating this page for formatting, and porting any code from the original <a href="http://www.statistics101.net">RESAMPLING-STATS language</a> to Python and R.</p>
<p>Feel free to read this version for the sense, but expect there to be multiple issues with formatting.</p>
<p>We will remove this warning when the page has adequate formatting, and we have ported the code.</p>
</div>
</div>
<section id="preview" class="level2" data-number="29.1">
<h2 data-number="29.1" class="anchored" data-anchor-id="preview"><span class="header-section-number">29.1</span> Preview</h2>
<p>The correlation (speaking in a loose way for now) between two variables measures the strength of the relationship between them. A positive “linear” correlation between two variables x and y implies that high values of x are associated with high values of y, and that low values of x are associated with low values of y. A negative correlation implies the opposite; high values of x are associated with <em>low</em> values of y. By definition a “correlation coefficient” close to zero indicates little or no linear relationship between two variables; correlation coefficients close to 1 and -1 denote a strong positive or negative relationship. We will generally use a simpler measure of correlation than the correlation coefficient, however.</p>
<p>One way to measure correlation with the resampling method is to rank both variables from highest to lowest, and investigate how often in randomly-generated samples the rankings of the two variables are as close to each other as the rankings in the observed variables. A better approach, because it uses more of the quantitative information contained in the data though it requires more computation, is to multiply the values for the corresponding pairs of values for the two variables, and compare the sum of the resulting products to the analogous sum for randomly-generated pairs of the observed variable values. The last section of the chapter shows how the strength of a relationship can be determined when the data are counted, rather than measured. First comes some discussion of the philosophical issues involved in correlation and causation.</p>
</section>
<section id="introduction-to-correlation-and-causation" class="level2" data-number="29.2">
<h2 data-number="29.2" class="anchored" data-anchor-id="introduction-to-correlation-and-causation"><span class="header-section-number">29.2</span> Introduction to correlation and causation</h2>
<p>The questions in examples <a href="probability_theory_3.html#sec-birthday-problem" class="quarto-xref"><span>Section&nbsp;12.1</span></a> to <a href="probability_theory_4_finite.html#sec-fifteen-bridge" class="quarto-xref"><span>Section&nbsp;13.3.3</span></a> have been stated in the following form: Does the independent variable (say, irradiation; or type of pig ration) have an effect upon the dependent variable (say, sex of fruit flies; or weight gain of pigs)? This is another way to state the following question: Is there a <em>causal relationship</em> between the independent variable(s) and the dependent variable? (“Independent” or “control” is the name we give to the variable(s) the researcher believes is (are) responsible for changes in the other variable, which we call the “dependent” or “response” variable.)</p>
<p>A causal relationship cannot be defined perfectly neatly. Even an experiment does not determine perfectly whether a relationship deserves to be called “causal” because, among other reasons, the independent variable may not be clear-cut. For example, even if cigarette smoking experimentally produces cancer in rats, it might be the paper and not the tobacco that causes the cancer. Or consider the fabled gentlemen who got experimentally drunk on bourbon and soda on Monday night, scotch and soda on Tuesday night, and brandy and soda on Wednesday night — and stayed sober Thursday night by drinking nothing. With a vast inductive leap of scientific imagination, they treated their experience as an empirical demonstration that soda, the common element each evening, was the cause of the inebriated state they had experienced. Notice that their deduction was perfectly sound, given only the recent evidence they had. Other knowledge of the world is necessary to set them straight. That is, even in a controlled experiment there is often no way except subject-matter knowledge to avoid erroneous conclusions about causality. Nothing except substantive knowledge or scientific intuition would have led them to the recognition that it is the alcohol rather than the soda that made them drunk, <em>as long as they always took soda with their drinks</em> . And no statistical procedure can suggest to them that they ought to experiment with the presence and absence of soda. If this is true for an experiment, it must also be true for an uncontrolled study.</p>
<p>Here are some tests that a relationship usually must pass to be called causal. That is, a working definition of a particular causal relationship is expressed in a statement that has these important characteristics:</p>
<ol type="1">
<li><p>It is an association that is strong enough so that the observer believes it to have a predictive (explanatory) power great enough to be scientifically useful or interesting. For example, he is not likely to say that wearing glasses causes (or is a cause of) auto accidents if the observed correlation is .07, even if the sample is large enough to make the correlation statistically significant. In other words, unimportant relationships are not likely to be labeled causal.</p>
<p>Various observers may well differ in judging whether or not an association is strong enough to be important and therefore “causal.” And the particular field in which the observer works may affect this judgment. This is an indication that whether or not a relationship is dubbed “causal” involves a good deal of human judgment and is subject to dispute.</p></li>
<li><p>The “side conditions” must be sufficiently <em>few</em> and sufficiently observable so that the relationship will apply under a wide enough range of conditions to be considered useful or interesting. In other words, <em>the relationship must not require too many “if”s, “and”s, and “but”s in order to hold</em> . For example, one might say that an increase in income caused an increase in the birth rate if this relationship were observed everywhere. But, if the relationship were found to hold only in developed countries, among the educated classes, and among the higher-income groups, then it would be less likely to be called “causal” — even if the correlation were extremely high once the specified conditions had been met. A similar example can be made of the relationship between income and happiness.</p></li>
<li><p>For a relationship to be called “causal,” there should be sound reason to believe that, even if the control variable were not the “real” cause (and it never is), other relevant “hidden” and “real” cause variables must also change <em>consistently</em> with changes in the control variables. That is, a variable being manipulated may reasonably be called “causal” if the real variable for which it is believed to be a proxy must always be tied intimately to it. (Between two variables, v and w, v may be said to be the “more real” cause and <em>w</em> a “spurious” cause, if <em>v</em> and <em>w</em> require the same side conditions, except that <em>v</em> does not require <em>w</em> as a side condition.) This third criterion (non-spuriousness) is of particular importance to policy makers. The difference between it and the previous criterion for side conditions is that a plenitude of very restrictive side conditions may take the relationship out of the class of causal relationships, <em>even though the effects of the side conditions are known</em> . This criterion of nonspuriousness concerns variables that are as yet <em>unknown and unevaluated</em> but that have a <em>possible</em> ability to <em>upset</em> the observed association.</p>
<p>Examples of spurious relationships and hidden-third-factor causation are commonplace. For a single example, toy sales rise in December. There is no danger in saying that December causes an increase in toy sales, even though it is “really” Christmas that causes the increase, because Christmas and December practically always accompany each other.</p>
<p>Belief that the relationship is not spurious is increased if <em>many</em> likely variables have been investigated and none removes the relationship. This is further demonstration that the test of whether or not an association should be called “causal” cannot be a logical one; there is no way that one can express in symbolic logic the fact that many other variables have been tried without changing the relationship in question.</p></li>
<li><p>The more tightly a relationship is bound into (that is, deduced from, compatible with, and logically connected to) a general framework of theory, the stronger is its claim to be called “causal.” For an economics example, observed positive relationships between the interest rate and business investment and between profits and investment are more likely to be called “causal” than is the relationship between liquid assets and investment. This is so because the first two statements can be deduced from classical price theory, whereas the third statement cannot. Connection to a theoretical framework provides support for belief that the side conditions necessary for the statement to hold true are not restrictive and that the likelihood of spurious correlation is not great; because a statement is logically connected to the rest of the system, the statement tends to stand or fall as the rest of the system stands or falls. And, because the rest of the system of economic theory has, over a long period of time and in a wide variety of tests, been shown to have predictive power, a statement connected with it is cloaked in this mantle.</p></li>
</ol>
<p>The social sciences other than economics do not have such well-developed bodies of deductive theory, and therefore this criterion of causality does not weigh as heavily in sociology, for instance, as in economics. Rather, the other social sciences seem to substitute a weaker and more general criterion, that is, whether or not the statement of the relationship is accompanied by other statements that seem to “explain” the “mechanism” by which the relationship operates. Consider, for example, the relationship between the phases of the moon and the suicide rate. The reason that sociologists do not call it causal is that there are no auxiliary propositions that explain the relationship and describe an operative mechanism. On the other hand, the relationship between broken homes and juvenile delinquency is often referred to as “causal,” in large part because a large body of psychoanalytic theory serves to explain why a child raised without one or the other parent, or in the presence of parental strife, should not adjust readily.</p>
<p>Furthermore, one can never decide with perfect certainty whether in any <em>given</em> situation one variable “causes” a particular change in another variable. At best, given your particular purposes in investigating a phenomena, you may be safe in judging that very likely there is causal influence.</p>
<p>In brief, it is correct to say (as it is so often said) that correlation does not prove causation — if we add the word “completely” to make it “correlation does not <em>completely</em> prove causation.” On the other hand, causation can <em>never</em> be “proven” <em>completely</em> by correlation <em>or any other</em> tool or set of tools, including experimentation. The best we can do is make informed judgments about whether to call a relationship causal.</p>
<p>It is clear, however, that in any situation where we are interested in the possibility of causation, we must <em>at least</em> know whether there is a relationship (correlation) between the variables of interest; the existence of a relationship is necessary for a relationship to be judged causal even if it is not sufficient to receive the causal label. And in other situations where we are not even interested in causality, but rather simply want to predict events or understand the structure of a system, we may be interested in the existence of relationships quite apart from questions about causations. Therefore our next set of problems deals with the probability of there being a relationship between two measured variables, variables that can take on any values (say, the values on a test of athletic scores) rather than just two values (say, whether or not there has been irradiation.)<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<p>Another way to think about such problems is to ask whether two variables are <em>independent</em> of each other — that is, whether you know anything about the value of one variable if you know the value of the other in a particular case — or whether they are not independent but rather are related.</p>
</section>
<section id="a-note-on-association-compared-to-testing-a-hypothesis" class="level2" data-number="29.3">
<h2 data-number="29.3" class="anchored" data-anchor-id="a-note-on-association-compared-to-testing-a-hypothesis"><span class="header-section-number">29.3</span> A Note on Association Compared to Testing a Hypothesis</h2>
<p>Problems in which we investigate a) whether there is an <em>association</em> , versus b) whether there is a <em>difference</em> between just two groups, often look very similar, especially when the data constitute a 2-by-2 table. There is this important difference between the two types of analysis, however: Questions about <em>association</em> refer to <em>variables</em> — say weight and age — and it never makes sense to ask whether there is a difference between variables (except when asking whether they measure the same quantity). Questions about <em>similarity or difference</em> refer to <em>groups of individuals</em> , and in such a situation it does make sense to ask whether or not two groups are observably different from each other.</p>
<section id="sec-athletic-iq-ranks" class="level3" data-number="29.3.1">
<h3 data-number="29.3.1" class="anchored" data-anchor-id="sec-athletic-iq-ranks"><span class="header-section-number">29.3.1</span> Example: Is Athletic Ability Directly Related to Intelligence?</h3>
<p>Question: <strong>Is there correlation between two variables or are they independent?</strong></p>
<p>A scientist often wants to know whether or not two characteristics go together, that is, whether or not they are correlated (that is, related or associated). For example, do youths with high athletic ability tend to also have high I.Q.s?</p>
<p>Hypothetical physical-education scores of a group of ten high-school boys are shown in <a href="#tbl-physical-mental" class="quarto-xref">Table&nbsp;<span>29.1</span></a>, ordered from high to low, along with the I.Q. score for each boy. The ranks for each student’s athletic and I.Q. scores are then shown in the third and fourth columns:</p>
<div id="tbl-physical-mental" class="anchored">
<table class="table">
<caption>Table&nbsp;29.1: Hypothetical athletic and i.q. scores for high school boys</caption>
<colgroup>
<col style="width: 28%">
<col style="width: 23%">
<col style="width: 27%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th>Athletic Score</th>
<th>I.Q. Score</th>
<th>Athletic Rank</th>
<th>I.Q.Rank</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>97</td>
<td>114</td>
<td>1</td>
<td>3</td>
</tr>
<tr class="even">
<td>94</td>
<td>120</td>
<td>2</td>
<td>1</td>
</tr>
<tr class="odd">
<td>93</td>
<td>107</td>
<td>3</td>
<td>7</td>
</tr>
<tr class="even">
<td>90</td>
<td>113</td>
<td>4</td>
<td>4</td>
</tr>
<tr class="odd">
<td>87</td>
<td>118</td>
<td>5</td>
<td>2</td>
</tr>
<tr class="even">
<td>86</td>
<td>101</td>
<td>6</td>
<td>8</td>
</tr>
<tr class="odd">
<td>86</td>
<td>109</td>
<td>7</td>
<td>6</td>
</tr>
<tr class="even">
<td>85</td>
<td>110</td>
<td>8</td>
<td>5</td>
</tr>
<tr class="odd">
<td>81</td>
<td>100</td>
<td>9</td>
<td>9</td>
</tr>
<tr class="even">
<td>76</td>
<td>99</td>
<td>10</td>
<td>10</td>
</tr>
</tbody>
</table>
</div>
<p>We want to know whether a high score on athletic ability tends to be found along with a high I.Q. score more often than would be expected by chance. Therefore, our strategy is to see how often high scores on <em>both</em> variables are found by chance. We do this by disassociating the two variables and making two separate and independent universes, one composed of the athletic scores and another of the I.Q. scores. Then we draw pairs of observations from the two universes at random, and compare the experimental patterns that occur by chance to what actually is observed to occur in the world.</p>
<p>The first testing scheme we shall use is similar to our first approach to the pig rations — splitting the results into just “highs” and “lows.” We take ten cards, one of each denomination from “ace” to “10,” shuffle, and deal five cards to correspond to the first five athletic ranks. The face values then correspond to the I.Q. ranks. Under the benchmark hypothesis the athletic ranks will not be associated with the I.Q. ranks. Add the face values in the first five cards in each trial; the first hand includes 2, 4, 5, 6, and 9, so the sum is 26. Record, shuffle, and repeat perhaps ten times. Then compare the random results to the sum of the observed ranks of the five top athletes, which equals 17.</p>
<p>The following steps describe a slightly different procedure than that just described, because this one may be easier to understand:</p>
<ul>
<li><strong>Step 1.</strong> Convert the athletic and I.Q. scores to ranks. Then constitute a universe of spades, “ace” to “10,” to correspond to the athletic ranks, and a universe of hearts, “ace” to “10,” to correspond to the IQ ranks.</li>
<li><strong>Step 2.</strong> Deal out the well-shuffled cards into pairs, each pair with an athletic score and an I.Q. score.</li>
<li><strong>Step 3.</strong> Locate the cards with the top five athletic ranks, and add the I.Q. rank scores on their paired cards. Compare this sum to the observed sum of 17. If 17 or less, indicate “yes,” otherwise “no.” (Why do we use “17 or less” rather than “less than 17”? Because we are asking the probability of a score <em>this low or lower</em>.)</li>
<li><strong>Step 4.</strong> Repeat steps 2 and 3 ten times.</li>
<li><strong>Step 5.</strong> Calculate the proportion “yes.” This estimates the probability sought.</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Sum of the top ranks and the difference in sums
</div>
</div>
<div class="callout-body-container callout-body">
<p>Notice that we could also find the sum of the IQ ranks for the <em>top</em> five athletes, as above, and then <em>subtract</em> the sum of the <em>bottom</em> five. The result will be negative if the athletes have lower-numbered (higher) IQ ranks on average, and positive otherwise. But gives us no more information than the sum of the top five. The sum of all the ranks (<span class="math inline">\(1 + 2 + ... + 10\)</span>) is <span class="math inline">\(55\)</span>. Say we find the sum of the top five ranks is 18, then the sum of the bottom five ranks must be <span class="math inline">\(55 - 18 = 37\)</span>, and the subtraction of the two is <span class="math inline">\(18 - (55 - 18) = 18 * 2 - 55 = -19\)</span>. In general, for any sum of the top five ranks <span class="math inline">\(T\)</span>, the sum of the bottom five ranks <span class="math inline">\(B\)</span> is <span class="math inline">\(55 - T\)</span>, and the difference is <span class="math inline">\(T - B = T - (55 - T) = T * 2 - 55\)</span>. So, if the top-five sum <span class="math inline">\(T\)</span> is smaller, the difference between <span class="math inline">\(T - B\)</span> will also be more negative. Put another way, if we know the sum of the top five ranks <span class="math inline">\(T\)</span> is 18, we also know the difference is <span class="math inline">\(2 * 18 = 55 = -19\)</span>, when <span class="math inline">\(T = 19\)</span>, the difference <span class="math inline">\(T - B\)</span> is <span class="math inline">\(2 * 19 - 15 = -17\)</span>, when <span class="math inline">\(T = 20\)</span>, <span class="math inline">\(T - B = -15\)</span> and so on.</p>
</div>
</div>
<p>In <a href="#tbl-ability-trials" class="quarto-xref">Table&nbsp;<span>29.2</span></a> we see that the observed sum (17) is lower than the sum of the top 5 ranks in all but one (shown in bold) of the ten random trials (trial 5), which suggests that there is a good chance (9 in 10) that the five best athletes will not have I.Q. scores that high by chance. But it might be well to deal some more to get a more reliable average. We add thirty hands, and thirty-nine of the total forty hands exceed the observed rank value, so the probability that the observed correlation of athletic and I.Q. scores would occur by chance is about .025. In other words, if there is no real association between the variables, the probability that the top 5 ranks would sum to a number this low or lower is only 1 in 40, and it therefore seems reasonable to believe that high athletic ability tends to accompany a high I.Q.</p>
<div id="tbl-ability-trials" class="anchored">
<table class="table">
<caption>Table&nbsp;29.2: 40 random trials of the problem athletic / IQ problem</caption>
<thead>
<tr class="header">
<th>Trial</th>
<th>Sum of IQ Ranks</th>
<th>&lt;= observed (17)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>26</td>
<td>No</td>
</tr>
<tr class="even">
<td>2</td>
<td>23</td>
<td>No</td>
</tr>
<tr class="odd">
<td>3</td>
<td>22</td>
<td>No</td>
</tr>
<tr class="even">
<td>4</td>
<td>37</td>
<td>No</td>
</tr>
<tr class="odd">
<td><strong>5</strong></td>
<td><strong>16</strong></td>
<td><strong>Yes</strong></td>
</tr>
<tr class="even">
<td>6</td>
<td>22</td>
<td>No</td>
</tr>
<tr class="odd">
<td>7</td>
<td>22</td>
<td>No</td>
</tr>
<tr class="even">
<td>8</td>
<td>28</td>
<td>No</td>
</tr>
<tr class="odd">
<td>9</td>
<td>38</td>
<td>No</td>
</tr>
<tr class="even">
<td>10</td>
<td>22</td>
<td>No</td>
</tr>
<tr class="odd">
<td>11</td>
<td>35</td>
<td>No</td>
</tr>
<tr class="even">
<td>12</td>
<td>36</td>
<td>No</td>
</tr>
<tr class="odd">
<td>13</td>
<td>31</td>
<td>No</td>
</tr>
<tr class="even">
<td>14</td>
<td>29</td>
<td>No</td>
</tr>
<tr class="odd">
<td>15</td>
<td>32</td>
<td>No</td>
</tr>
<tr class="even">
<td>16</td>
<td>25</td>
<td>No</td>
</tr>
<tr class="odd">
<td>17</td>
<td>25</td>
<td>No</td>
</tr>
<tr class="even">
<td>18</td>
<td>29</td>
<td>No</td>
</tr>
<tr class="odd">
<td>19</td>
<td>25</td>
<td>No</td>
</tr>
<tr class="even">
<td>20</td>
<td>22</td>
<td>No</td>
</tr>
<tr class="odd">
<td>21</td>
<td>30</td>
<td>No</td>
</tr>
<tr class="even">
<td>22</td>
<td>31</td>
<td>No</td>
</tr>
<tr class="odd">
<td>23</td>
<td>35</td>
<td>No</td>
</tr>
<tr class="even">
<td>24</td>
<td>25</td>
<td>No</td>
</tr>
<tr class="odd">
<td>25</td>
<td>33</td>
<td>No</td>
</tr>
<tr class="even">
<td>26</td>
<td>30</td>
<td>No</td>
</tr>
<tr class="odd">
<td>27</td>
<td>24</td>
<td>No</td>
</tr>
<tr class="even">
<td>28</td>
<td>29</td>
<td>No</td>
</tr>
<tr class="odd">
<td>29</td>
<td>30</td>
<td>No</td>
</tr>
<tr class="even">
<td>30</td>
<td>31</td>
<td>No</td>
</tr>
<tr class="odd">
<td>31</td>
<td>30</td>
<td>No</td>
</tr>
<tr class="even">
<td>32</td>
<td>21</td>
<td>No</td>
</tr>
<tr class="odd">
<td>33</td>
<td>25</td>
<td>No</td>
</tr>
<tr class="even">
<td>34</td>
<td>19</td>
<td>No</td>
</tr>
<tr class="odd">
<td>35</td>
<td>29</td>
<td>No</td>
</tr>
<tr class="even">
<td>36</td>
<td>23</td>
<td>No</td>
</tr>
<tr class="odd">
<td>37</td>
<td>23</td>
<td>No</td>
</tr>
<tr class="even">
<td>38</td>
<td>34</td>
<td>No</td>
</tr>
<tr class="odd">
<td>39</td>
<td>23</td>
<td>No</td>
</tr>
<tr class="even">
<td>40</td>
<td>26</td>
<td>No</td>
</tr>
</tbody>
</table>
</div>
<p>In fact we can apply an even simpler procedure to get the same result, by reasoning about the individual trial.</p>
<p>One trial in our procedure is:</p>
<ul>
<li><strong>Step 2.</strong> Deal out the well-shuffled cards into pairs, each pair with an athletic score and an I.Q. score.</li>
<li><strong>Step 3.</strong> Locate the cards with the top five athletic ranks, and add the I.Q. rank scores on their paired cards. Compare this sum to the observed sum of 17. If 17 or less, indicate “yes,” otherwise “no.” (Why do we use “17 or less” rather than “less than 17”? Because we are asking the probability of a score <em>this low or lower</em>.)</li>
</ul>
<p>Now consider the 5 IQ rank cards. In the procedure above, we found these by <em>first</em> pairing the athletic ranks and the IQ ranks, <em>then</em> selecting the IQ ranks corresponding to the top 5 athletic ranks. A little thought may persuade you, that by doing this, we have have a <em>random selection of 5 IQ ranks</em>. We got that random selection by pairing, selecting on athletic rank — but the initial pairing and selection will do nothing other than giving us one particular set of randomly chosen 5 IQ rank cards. So we can simplify our procedure even further by missing out the pairing and selecting by rank steps; we can just shuffle the IQ rank cards and deal out 5 to be our randomly selected IQ ranks.</p>
<p>::: {.notebook name=“athlete_iq” title=“Athletic ability and IQ”}</p>
<p>To simulate this problem in R, we first create a vector containing the I.Q. rankings of the top 5 students in athletics. The <code>sum</code> of these I.Q. rankings constitutes the observed result to be tested against randomly-drawn samples. We observe that the actual I.Q. rankings of the top five athletes sums to 17. The more frequently that the sum of 5 randomly-generated rankings (out of 10) is as low as this observed number, the higher is the probability that there is no relationship between athletic performance and I.Q. based on these data.</p>
<p>First we record the 1 through 10 into vector <code>iq_ranks</code>. Then we shuffle the numbers so the rankings are in a random order. Then select the first 5 of these numbers and put them in another vector, <code>top_5</code>, and <code>sum</code> them, putting the result in <code>top_5_sum</code>. We repeat this procedure <code>N = 10000</code> times, recording each result in a scorekeeping vector: <code>z</code>. Graphing <code>z</code>, we get a histogram that shows us how often our randomly assigned sums are equal to or below 17.</p>
<div class="cell" data-layout-align="center" data-opts.label="py_ed" data-hash="correlation_causation_cache/html/unnamed-chunk-3_45e18fea83cdc814a186e2f27577a2be">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Number of repeats.</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># The IQ ranks, ready for shuffling.</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>iq_ranks <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>  <span class="co"># 1 through 10.</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Scorekeeping array.</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="fu">numeric</span>(N)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>N) {</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Shuffle the ranks.</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    shuffled <span class="ot">&lt;-</span> <span class="fu">sample</span>(iq_ranks)</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Take the first 5 ranks.</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    top_5 <span class="ot">&lt;-</span> shuffled[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Sum those ranks.</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    top_5_sum <span class="ot">&lt;-</span> <span class="fu">sum</span>(top_5)</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Keep track of the result of each trial.</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>    z[i] <span class="ot">&lt;-</span> top_5_sum</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>    <span class="co"># End the experiment, go back and repeat.</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Produce a histogram of trial results.</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="co"># Make the bins be the integers from 10 through 45.</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(z, <span class="at">breaks=</span><span class="dv">10</span><span class="sc">:</span><span class="dv">45</span>, <span class="at">main=</span><span class="st">'Sums of 5 ranks selected at random'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="correlation_causation_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<p>We see that in only about 2% of the trials did random selection of ranks produce a total of 17 or lower. R can calculate this for us directly:</p>
<div class="cell" data-layout-align="center" data-hash="correlation_causation_cache/html/unnamed-chunk-6_4f7adc91de380173f4ecd03c29c77437">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Determine how many trials produced sums of ranks &lt;= 17 by chance.</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="fu">sum</span>(z <span class="sc">&lt;=</span> <span class="dv">17</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># The proportion.</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>kk <span class="ot">&lt;-</span> k <span class="sc">/</span> N</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Show the result</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>kk</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.016</code></pre>
</div>
</div>
<p>Why do we sum the ranks of the first <em>five</em> athletes rather than taking the sum of the top three, say? Indeed, we could have looked at the top three, two, four, or even six or seven. The first reason for splitting the group in half is that an even split uses the available information more fully, and therefore we obtain greater efficiency. (I cannot prove this formally here, but perhaps it makes intuitive sense to you.) A second reason is that getting into the habit of always looking at an even split reduces the chances that you will pick and choose in such a manner as to fool yourself. For example, if the I.Q. ranks of the top five athletes were 3, 2, 1, 10, and 9, we would be deceiving ourselves if, after looking the data over, we drew the line between athletes 3 and 4. (More generally, choosing an appropriate measure before examining the data will help you avoid fooling yourself in such matters.)</p>
<p>A simpler but less efficient approach to this same problem is to classify the top-half athletes by whether or not they were also in the top half of the I.Q. scores. Of the first five athletes actually observed, <em>four</em> were in the top five I.Q. scores. We can then shuffle five black and five red cards and see how often four or more (that is, four or five) blacks come up with the first five cards. The proportion of times that four or more blacks occurs in the trial is the probability that an association as strong as that observed might occur by chance even if there is no association. Table 23-3 shows a proportion of five trials out of twenty.</p>
<p>In the R program below, we first note that the top 5 athletes had 4 of the top 5 I.Q. scores. So we constitute the set of 10 IQ rankings vector <code>a</code>. We then SHUFFLE A and TAKE 5 I.Q. rankings (out of 10). We COUNT how many are in the top 5, and keep SCORE of the result. After REPEATing 1000 times, we find out how often we select 4 of the top 5.</p>
<div class="cell" data-layout-align="center" data-opts.label="py_ed" data-hash="correlation_causation_cache/html/unnamed-chunk-8_f3c2598d8c6c1bd9734f9ba4167f7658">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Number of repeats.</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>N <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co"># The IQ ranks, ready for shuffling.</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>iq_ranks <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>  <span class="co"># 1 through 10.</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Scorekeeping array.</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>z <span class="ot">&lt;-</span> <span class="fu">numeric</span>(N)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>N) {</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Shuffle the ranks.</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>    shuffled <span class="ot">&lt;-</span> <span class="fu">sample</span>(iq_ranks)</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Take the first 5 ranks.</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>    top_5 <span class="ot">&lt;-</span> shuffled[<span class="dv">1</span><span class="sc">:</span><span class="dv">5</span>]</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Everything up until this point is the same as the code above.</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Here is the difference.</span></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Check whether the selected IQ ranks are in the top 5.</span></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>    are_top <span class="ot">&lt;-</span> top_5 <span class="sc">&lt;=</span> <span class="dv">5</span></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Count how many were in the top 5</span></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>    n_are_top <span class="ot">&lt;-</span> <span class="fu">sum</span>(are_top)</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Keep track of the result of each trial.</span></span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>    z[i] <span class="ot">&lt;-</span> n_are_top</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>    <span class="co"># End the experiment, go back and repeat.</span></span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Determine how many trials produced 4 or more top ranks by chance.</span></span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a>k <span class="ot">=</span> <span class="fu">sum</span>(z <span class="sc">&gt;=</span> <span class="dv">4</span>)</span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a><span class="co">#  Convert to a proportion.</span></span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>kk <span class="ot">=</span> k <span class="sc">/</span> N</span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Show the result.</span></span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>kk</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.103</code></pre>
</div>
</div>
<p>Observed Score: 4</p>
<div id="tbl-top-rank-counts" class="anchored">
<table class="table">
<caption>Table&nbsp;29.3: Results of 20 random trials of the top-5 rank counts</caption>
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Trial</strong></td>
<td style="text-align: left;"><strong>Score</strong></td>
<td style="text-align: left;"><strong>Yes or No</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">1</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">Yes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">3</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="odd">
<td style="text-align: left;">4</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">5</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="odd">
<td style="text-align: left;">6</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">7</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">Yes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">8</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">9</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="odd">
<td style="text-align: left;">10</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">Yes</td>
</tr>
<tr class="even">
<td style="text-align: left;">11</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="odd">
<td style="text-align: left;">12</td>
<td style="text-align: left;">1</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">13</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="odd">
<td style="text-align: left;">14</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">15</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">Yes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">16</td>
<td style="text-align: left;">3</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">17</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="odd">
<td style="text-align: left;">18</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">19</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="odd">
<td style="text-align: left;">20</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">Yes</td>
</tr>
</tbody>
</table>
</div>
<p>So far we have proceeded on the theory that if there is <em>any</em> relationship between athletics and I.Q., then the better athletes have higher rather than lower I.Q. scores. The justification for this assumption is that past research suggests that it is probably true. But if we had <em>not</em> had the benefit of that past research, we would then have had to proceed somewhat differently; we would have had to consider the possibility that the top five athletes could have I.Q. scores either higher <em>or</em> lower than those of the other students. The results of the “two-tail” test would have yielded odds weaker than those we observed.</p>
</section>
<section id="example-athletic-ability-and-i.q.-a-third-way" class="level3" data-number="29.3.2">
<h3 data-number="29.3.2" class="anchored" data-anchor-id="example-athletic-ability-and-i.q.-a-third-way"><span class="header-section-number">29.3.2</span> Example: Athletic ability and I.Q. a third way</h3>
<p>The example in <span class="quarto-unresolved-ref">?sec-althletic-iq-ranks</span> investigated the relationship between I.Q. and athletic score by ranking the two sets of scores. But ranking of scores loses some efficiency because it uses only an “ordinal” (rank-ordered) rather than a “cardinal” (measured) scale; the numerical shadings and relative relationships are lost when we convert to ranks. Therefore let us consider a test of correlation that uses the original cardinal numerical scores.</p>
<p>First a little background: <a href="#fig-hypot_iq_athletic_1" class="quarto-xref">Figure&nbsp;<span>29.1</span></a> and <a href="#fig-hypot_iq_athletic_2" class="quarto-xref">Figure&nbsp;<span>29.2</span></a> show two hypothetical cases of very high association among the I.Q. and athletic scores used in previous examples. <a href="#fig-hypot_iq_athletic_1" class="quarto-xref">Figure&nbsp;<span>29.1</span></a> indicates that the higher the I.Q. score, the higher the athletic score. With a boy’s athletic score you can thus predict quite well his I.Q. score by means of a hand-drawn line — or vice versa. The same is true of <a href="#fig-hypot_iq_athletic_2" class="quarto-xref">Figure&nbsp;<span>29.2</span></a>, but in the opposite direction. Notice that even though athletic score is on the x-axis (horizontal) and I.Q. score is on the y-axis (vertical), the athletic score does not <em>cause</em> the I.Q. score. (It is an unfortunate deficiency of such diagrams that <em>some</em> variable must arbitrarily be placed on the x-axis, whether you intend to suggest causation or not.)</p>
<div class="cell" data-layout-align="center" data-opts.label="svg_fig" data-hash="correlation_causation_cache/html/fig-hypot_iq_athletic_1_9fcaaaa528337f601b97cf16d293b1c8">
<div class="cell-output-display">
<div id="fig-hypot_iq_athletic_1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="diagrams/hypot_iq_athletic_1.svg" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;29.1: Hypothetical Scores for I.Q. and Athletic Ability — 1</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center" data-opts.label="svg_fig" data-hash="correlation_causation_cache/html/fig-hypot_iq_athletic_2_9ccbf166d68204a8ff452670ab68dddf">
<div class="cell-output-display">
<div id="fig-hypot_iq_athletic_2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="diagrams/hypot_iq_athletic_2.svg" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;29.2: Hypothetical Scores for I.Q. and Athletic Ability — 2</figcaption>
</figure>
</div>
</div>
</div>
<p>In <a href="#fig-given_iq_athletic" class="quarto-xref">Figure&nbsp;<span>29.3</span></a>, which plots the scores as given in table 23-1 the prediction of athletic score given I.Q. score, or vice versa, is less clear-cut than in <a href="#fig-hypot_iq_athletic_1" class="quarto-xref">Figure&nbsp;<span>29.1</span></a>. On the basis of <a href="#fig-given_iq_athletic" class="quarto-xref">Figure&nbsp;<span>29.3</span></a> alone, one can say only that there <em>might</em> be some association between the two variables.</p>
<div class="cell" data-layout-align="center" data-opts.label="svg_fig" data-hash="correlation_causation_cache/html/fig-given_iq_athletic_04205979c511b4350aed4c13261caf36">
<div class="cell-output-display">
<div id="fig-given_iq_athletic" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="diagrams/given_iq_athletic.svg" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;29.3: Given Scores for I.Q. and Athletic Ability</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="correlation-sum-of-products" class="level2" data-number="29.4">
<h2 data-number="29.4" class="anchored" data-anchor-id="correlation-sum-of-products"><span class="header-section-number">29.4</span> Correlation: sum of products</h2>
<p>Now let us take advantage of a handy property of numbers. The more closely two sets of numbers match each other in order, the higher the sums of their products. Consider the following arrays of the numbers 1, 2, and 3:</p>
<p>1 x 1 = 1</p>
<p>2 x 2 = 4 (columns in matching order) 3 x 3 = 9</p>
<p>SUM = 14</p>
<p>1 x 2 = 2</p>
<p>2 x 3 = 6 (columns not in matching order) 3 x 1 = 3</p>
<p>SUM = 11</p>
<p>I will not attempt a mathematical proof, but the reader is encouraged to try additional combinations to be sure that the highest sum is obtained when the order of the two columns is the same. Likewise, the lowest sum is obtained when the two columns are in perfectly opposite order:</p>
<p>1 x 3 = 3</p>
<p>2 x 2 = 4 (columns in opposite order) 3 x 1 = 3</p>
<p>SUM = 10</p>
<p>Consider the cases in Table 23-4 which are chosen to illustrate a perfect (linear) association between <em>x</em> (Column 1) and <em>y</em> 1 (Column 2), and also between <em>x</em> (Column 1) and <em>y</em> 2 (Column 4); the numbers shown in Columns 3 and 5 are those that would be consistent with perfect associations. Notice the sum of the multiples of the <em>x</em> and <em>y</em> values in the two cases. It is either higher ( <em>xy</em> 1) or lower ( <em>xy</em> 2) than for any other possible way of arranging the <em>y</em> ’s. Any other arrangement of the <em>y’s</em> ( <em>y</em> 3, in Column 6, for example, chosen at random), when multiplied by the <em>x</em> ’s in Column 1, ( <em>xy</em> 3), produces a sum that falls somewhere between the sums of <em>xy</em> 1 and <em>xy</em> 2, as is the case with any other set of <em>y</em> 3’s which is not perfectly correlated with the <em>x</em> ’s.</p>
<p>Table 23-5, below, shows that the sum of the products of the <em>observed</em> I.Q. scores multiplied by athletic scores (column 7) is between the sums that would occur if the I.Q. scores were ranked from best to worst (column 3) and worst to best (column 5). The extent of correlation (association) can thus be measured by whether the sum of the multiples of the observed <em>x</em></p>
<p>and <em>y</em> values is relatively much higher or much lower than are sums of randomly-chosen pairs of <em>x</em> and <em>y</em> .</p>
<p>Table 23-4</p>
<p><strong>Comparison of Sums of Multiplications</strong></p>
<table class="table">
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Strong Positive Relationship</strong></td>
<td style="text-align: left;"><strong>Strong Negative Relationship</strong></td>
<td style="text-align: left;"><strong>Random Pairings</strong></td>
<td></td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>X</strong></td>
<td style="text-align: left;"><strong>Y1</strong></td>
<td style="text-align: left;"><strong>X*Y1</strong></td>
<td><strong>Y2</strong></td>
<td><strong>X*Y2</strong></td>
<td><strong>Y3</strong></td>
<td><strong>X*Y3</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;">2</td>
<td style="text-align: left;">2</td>
<td style="text-align: left;">4</td>
<td>10</td>
<td>20</td>
<td>4</td>
<td>8</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">4</td>
<td style="text-align: left;">16</td>
<td>8</td>
<td>32</td>
<td>8</td>
<td>32</td>
</tr>
<tr class="odd">
<td style="text-align: left;">6</td>
<td style="text-align: left;">6</td>
<td style="text-align: left;">36</td>
<td>6</td>
<td>36</td>
<td>6</td>
<td>36</td>
</tr>
<tr class="even">
<td style="text-align: left;">8</td>
<td style="text-align: left;">8</td>
<td style="text-align: left;">64</td>
<td>4</td>
<td>48</td>
<td>2</td>
<td>16</td>
</tr>
<tr class="odd">
<td style="text-align: left;">10</td>
<td style="text-align: left;">10</td>
<td style="text-align: left;">100</td>
<td>2</td>
<td>20</td>
<td>10</td>
<td>100</td>
</tr>
<tr class="even">
<td style="text-align: left;">SUMS:</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">220</td>
<td></td>
<td>156</td>
<td></td>
<td>192</td>
</tr>
</tbody>
</table>
<p>Table 23-5</p>
<p><strong>Sums of Products: IQ and Athletic Scores</strong></p>
<table class="table">
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>1</strong></td>
<td style="text-align: left;"><strong>2</strong></td>
<td style="text-align: left;"><strong>3</strong></td>
<td style="text-align: left;"><strong>4</strong></td>
<td style="text-align: left;"><strong>5</strong></td>
<td style="text-align: left;"><strong>6</strong></td>
<td style="text-align: left;"><strong>7</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Athletic</strong></td>
<td style="text-align: left;"><strong>Hypothetical</strong></td>
<td style="text-align: left;"><strong>Col. 1 x</strong></td>
<td style="text-align: left;"><strong>Hypothetical</strong></td>
<td style="text-align: left;"><strong>Col. 1 x</strong></td>
<td style="text-align: left;"><strong>Actual</strong></td>
<td style="text-align: left;"><strong>Col. 1 x</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Score</strong></td>
<td style="text-align: left;"><strong>I.Q.</strong></td>
<td style="text-align: left;"><strong>Col.2</strong></td>
<td style="text-align: left;"><strong>I.Q.</strong></td>
<td style="text-align: left;"><strong>Col. 4</strong></td>
<td style="text-align: left;"><strong>I.Q.</strong></td>
<td style="text-align: left;"><strong>Col.6</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">97</td>
<td style="text-align: left;">120</td>
<td style="text-align: left;">11640</td>
<td style="text-align: left;">99</td>
<td style="text-align: left;">9603</td>
<td style="text-align: left;">114</td>
<td style="text-align: left;">11058</td>
</tr>
<tr class="odd">
<td style="text-align: left;">94</td>
<td style="text-align: left;">118</td>
<td style="text-align: left;">11092</td>
<td style="text-align: left;">100</td>
<td style="text-align: left;">9400</td>
<td style="text-align: left;">120</td>
<td style="text-align: left;">11280</td>
</tr>
<tr class="even">
<td style="text-align: left;">93</td>
<td style="text-align: left;">114</td>
<td style="text-align: left;">10602</td>
<td style="text-align: left;">101</td>
<td style="text-align: left;">9393</td>
<td style="text-align: left;">107</td>
<td style="text-align: left;">9951</td>
</tr>
<tr class="odd">
<td style="text-align: left;">90</td>
<td style="text-align: left;">113</td>
<td style="text-align: left;">10170</td>
<td style="text-align: left;">107</td>
<td style="text-align: left;">9630</td>
<td style="text-align: left;">113</td>
<td style="text-align: left;">10170</td>
</tr>
<tr class="even">
<td style="text-align: left;">87</td>
<td style="text-align: left;">110</td>
<td style="text-align: left;">9570</td>
<td style="text-align: left;">109</td>
<td style="text-align: left;">9483</td>
<td style="text-align: left;">118</td>
<td style="text-align: left;">10266</td>
</tr>
<tr class="odd">
<td style="text-align: left;">86</td>
<td style="text-align: left;">109</td>
<td style="text-align: left;">9374</td>
<td style="text-align: left;">110</td>
<td style="text-align: left;">8460</td>
<td style="text-align: left;">101</td>
<td style="text-align: left;">8686</td>
</tr>
<tr class="even">
<td style="text-align: left;">86</td>
<td style="text-align: left;">107</td>
<td style="text-align: left;">9202</td>
<td style="text-align: left;">113</td>
<td style="text-align: left;">9718</td>
<td style="text-align: left;">109</td>
<td style="text-align: left;">9374</td>
</tr>
<tr class="odd">
<td style="text-align: left;">85</td>
<td style="text-align: left;">101</td>
<td style="text-align: left;">8585</td>
<td style="text-align: left;">114</td>
<td style="text-align: left;">9690</td>
<td style="text-align: left;">110</td>
<td style="text-align: left;">9350</td>
</tr>
<tr class="even">
<td style="text-align: left;">81</td>
<td style="text-align: left;">100</td>
<td style="text-align: left;">8100</td>
<td style="text-align: left;">118</td>
<td style="text-align: left;">9558</td>
<td style="text-align: left;">100</td>
<td style="text-align: left;">8100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">76</td>
<td style="text-align: left;">99</td>
<td style="text-align: left;">7524</td>
<td style="text-align: left;">120</td>
<td style="text-align: left;">9120</td>
<td style="text-align: left;">99</td>
<td style="text-align: left;">7524</td>
</tr>
<tr class="even">
<td style="text-align: left;">SUMS:</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">95859</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">95055</td>
<td style="text-align: left;"></td>
<td style="text-align: left;">95759</td>
</tr>
</tbody>
</table>
<p>3 Cases:</p>
<ul>
<li><p>Perfect positive correlation (hypothetical); column 3</p></li>
<li><p>Perfect negative correlation (hypothetical); column 5</p></li>
<li><p>Observed; column 7</p></li>
</ul>
<p>Now we attack the I.Q. and athletic-score problem using the property of numbers just discussed. First multiply the x and y values of the actual observations, and sum them to be 95,759 (Table 23-5). Then write the ten observed I.Q. scores on cards, and assign the cards in random order to the ten athletes, as shown in column 1 in Table 23-6.</p>
<p>Multiply by the x’s, and sum as in Table 23-7. If the I.Q. scores and athletic scores are <em>positively associated</em> , that is, if high I.Q.s and high athletic scores go together, then the sum of the multiplications for the observed sample will be higher than for most of the random trials. (If high I.Q.s go with low athletic scores, the sum of the multiplications for the observed sample will be <em>lower</em> than most of the random trials.)</p>
<p>Table 23-6</p>
<p><strong>Random Drawing of I.Q. Scores and Pairing (Randomly) Against Athletic Scores (20 Trials)</strong></p>
<p><strong>Trial Number</strong></p>
<p><strong>Athletic 1 2 3 4 5 6 7 8 9 10</strong></p>
<p><strong>Score</strong></p>
<table class="table">
<tbody>
<tr class="odd">
<td style="text-align: left;">97</td>
<td style="text-align: left;">114</td>
<td style="text-align: left;">109</td>
<td style="text-align: left;">110</td>
<td style="text-align: left;">118</td>
<td style="text-align: left;">107</td>
<td style="text-align: left;">114</td>
<td style="text-align: left;">107</td>
<td style="text-align: left;">120</td>
<td style="text-align: left;">100</td>
<td style="text-align: left;">114</td>
</tr>
<tr class="even">
<td style="text-align: left;">94</td>
<td style="text-align: left;">101</td>
<td style="text-align: left;">113</td>
<td style="text-align: left;">113</td>
<td style="text-align: left;">101</td>
<td style="text-align: left;">118</td>
<td style="text-align: left;">100</td>
<td style="text-align: left;">110</td>
<td style="text-align: left;">109</td>
<td style="text-align: left;">120</td>
<td style="text-align: left;">107</td>
</tr>
<tr class="odd">
<td style="text-align: left;">93</td>
<td style="text-align: left;">107</td>
<td style="text-align: left;">118</td>
<td style="text-align: left;">100</td>
<td style="text-align: left;">99</td>
<td style="text-align: left;">120</td>
<td style="text-align: left;">101</td>
<td style="text-align: left;">114</td>
<td style="text-align: left;">99</td>
<td style="text-align: left;">110</td>
<td style="text-align: left;">113</td>
</tr>
<tr class="even">
<td style="text-align: left;">90</td>
<td style="text-align: left;">113</td>
<td style="text-align: left;">101</td>
<td style="text-align: left;">118</td>
<td style="text-align: left;">114</td>
<td style="text-align: left;">101</td>
<td style="text-align: left;">113</td>
<td style="text-align: left;">100</td>
<td style="text-align: left;">118</td>
<td style="text-align: left;">99</td>
<td style="text-align: left;">99</td>
</tr>
<tr class="odd">
<td style="text-align: left;">87</td>
<td style="text-align: left;">120</td>
<td style="text-align: left;">100</td>
<td style="text-align: left;">101</td>
<td style="text-align: left;">100</td>
<td style="text-align: left;">110</td>
<td style="text-align: left;">107</td>
<td style="text-align: left;">113</td>
<td style="text-align: left;">114</td>
<td style="text-align: left;">101</td>
<td style="text-align: left;">118</td>
</tr>
<tr class="even">
<td style="text-align: left;">86</td>
<td style="text-align: left;">100</td>
<td style="text-align: left;">110</td>
<td style="text-align: left;">120</td>
<td style="text-align: left;">107</td>
<td style="text-align: left;">113</td>
<td style="text-align: left;">110</td>
<td style="text-align: left;">118</td>
<td style="text-align: left;">101</td>
<td style="text-align: left;">118</td>
<td style="text-align: left;">101</td>
</tr>
<tr class="odd">
<td style="text-align: left;">86</td>
<td style="text-align: left;">110</td>
<td style="text-align: left;">107</td>
<td style="text-align: left;">99</td>
<td style="text-align: left;">109</td>
<td style="text-align: left;">100</td>
<td style="text-align: left;">120</td>
<td style="text-align: left;">120</td>
<td style="text-align: left;">113</td>
<td style="text-align: left;">114</td>
<td style="text-align: left;">120</td>
</tr>
<tr class="even">
<td style="text-align: left;">85</td>
<td style="text-align: left;">99</td>
<td style="text-align: left;">99</td>
<td style="text-align: left;">104</td>
<td style="text-align: left;">120</td>
<td style="text-align: left;">99</td>
<td style="text-align: left;">109</td>
<td style="text-align: left;">101</td>
<td style="text-align: left;">107</td>
<td style="text-align: left;">109</td>
<td style="text-align: left;">109</td>
</tr>
<tr class="odd">
<td style="text-align: left;">81</td>
<td style="text-align: left;">118</td>
<td style="text-align: left;">120</td>
<td style="text-align: left;">114</td>
<td style="text-align: left;">110</td>
<td style="text-align: left;">114</td>
<td style="text-align: left;">99</td>
<td style="text-align: left;">99</td>
<td style="text-align: left;">100</td>
<td style="text-align: left;">107</td>
<td style="text-align: left;">109</td>
</tr>
<tr class="even">
<td style="text-align: left;">76</td>
<td style="text-align: left;">109</td>
<td style="text-align: left;">114</td>
<td style="text-align: left;">109</td>
<td style="text-align: left;">113</td>
<td style="text-align: left;">109</td>
<td style="text-align: left;">118</td>
<td style="text-align: left;">109</td>
<td style="text-align: left;">110</td>
<td style="text-align: left;">113</td>
<td style="text-align: left;">110</td>
</tr>
<tr class="odd">
<td style="text-align: left;"><strong>Trial Number</strong></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>Athletic Score</strong></td>
<td style="text-align: left;"><strong>11</strong></td>
<td style="text-align: left;"><strong>12</strong></td>
<td style="text-align: left;"><strong>13</strong></td>
<td style="text-align: left;"><strong>14</strong></td>
<td style="text-align: left;"><strong>15</strong></td>
<td style="text-align: left;"><strong>16</strong></td>
<td style="text-align: left;"><strong>17</strong></td>
<td style="text-align: left;"><strong>18</strong></td>
<td style="text-align: left;"><strong>19</strong></td>
<td style="text-align: left;"><strong>20</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;">97</td>
<td style="text-align: left;">109</td>
<td style="text-align: left;">118</td>
<td style="text-align: left;">101</td>
<td style="text-align: left;">109</td>
<td style="text-align: left;">107</td>
<td style="text-align: left;">100</td>
<td style="text-align: left;">99</td>
<td style="text-align: left;">113</td>
<td style="text-align: left;">99</td>
<td style="text-align: left;">110</td>
</tr>
<tr class="even">
<td style="text-align: left;">94</td>
<td style="text-align: left;">101</td>
<td style="text-align: left;">110</td>
<td style="text-align: left;">114</td>
<td style="text-align: left;">118</td>
<td style="text-align: left;">101</td>
<td style="text-align: left;">107</td>
<td style="text-align: left;">114</td>
<td style="text-align: left;">101</td>
<td style="text-align: left;">109</td>
<td style="text-align: left;">113</td>
</tr>
<tr class="odd">
<td style="text-align: left;">93</td>
<td style="text-align: left;">120</td>
<td style="text-align: left;">120</td>
<td style="text-align: left;">100</td>
<td style="text-align: left;">120</td>
<td style="text-align: left;">114</td>
<td style="text-align: left;">113</td>
<td style="text-align: left;">100</td>
<td style="text-align: left;">100</td>
<td style="text-align: left;">120</td>
<td style="text-align: left;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">90</td>
<td style="text-align: left;">110</td>
<td style="text-align: left;">118</td>
<td style="text-align: left;">109</td>
<td style="text-align: left;">110</td>
<td style="text-align: left;">99</td>
<td style="text-align: left;">109</td>
<td style="text-align: left;">107</td>
<td style="text-align: left;">109</td>
<td style="text-align: left;">110</td>
<td style="text-align: left;">99</td>
</tr>
<tr class="odd">
<td style="text-align: left;">87</td>
<td style="text-align: left;">100</td>
<td style="text-align: left;">100</td>
<td style="text-align: left;">120</td>
<td style="text-align: left;">99</td>
<td style="text-align: left;">118</td>
<td style="text-align: left;">114</td>
<td style="text-align: left;">110</td>
<td style="text-align: left;">110</td>
<td style="text-align: left;">107</td>
<td style="text-align: left;">101</td>
</tr>
<tr class="even">
<td style="text-align: left;">86</td>
<td style="text-align: left;">118</td>
<td style="text-align: left;">99</td>
<td style="text-align: left;">107</td>
<td style="text-align: left;">100</td>
<td style="text-align: left;">109</td>
<td style="text-align: left;">118</td>
<td style="text-align: left;">113</td>
<td style="text-align: left;">118</td>
<td style="text-align: left;">100</td>
<td style="text-align: left;">118</td>
</tr>
<tr class="odd">
<td style="text-align: left;">86</td>
<td style="text-align: left;">99</td>
<td style="text-align: left;">101</td>
<td style="text-align: left;">99</td>
<td style="text-align: left;">101</td>
<td style="text-align: left;">100</td>
<td style="text-align: left;">99</td>
<td style="text-align: left;">101</td>
<td style="text-align: left;">107</td>
<td style="text-align: left;">114</td>
<td style="text-align: left;">120</td>
</tr>
<tr class="even">
<td style="text-align: left;">85</td>
<td style="text-align: left;">107</td>
<td style="text-align: left;">114</td>
<td style="text-align: left;">110</td>
<td style="text-align: left;">114</td>
<td style="text-align: left;">120</td>
<td style="text-align: left;">110</td>
<td style="text-align: left;">120</td>
<td style="text-align: left;">120</td>
<td style="text-align: left;">118</td>
<td style="text-align: left;">100</td>
</tr>
<tr class="odd">
<td style="text-align: left;">81</td>
<td style="text-align: left;">114</td>
<td style="text-align: left;">107</td>
<td style="text-align: left;">113</td>
<td style="text-align: left;">113</td>
<td style="text-align: left;">110</td>
<td style="text-align: left;">101</td>
<td style="text-align: left;">109</td>
<td style="text-align: left;">114</td>
<td style="text-align: left;">101</td>
<td style="text-align: left;">100</td>
</tr>
<tr class="even">
<td style="text-align: left;">76</td>
<td style="text-align: left;">113</td>
<td style="text-align: left;">109</td>
<td style="text-align: left;">118</td>
<td style="text-align: left;">107</td>
<td style="text-align: left;">113</td>
<td style="text-align: left;">120</td>
<td style="text-align: left;">118</td>
<td style="text-align: left;">99</td>
<td style="text-align: left;">118</td>
<td style="text-align: left;">107</td>
</tr>
</tbody>
</table>
<p>Table 23-7</p>
<p><strong>Results of Sum Products for Above 20 Random Trials</strong></p>
<table class="table">
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Trial</strong></td>
<td style="text-align: left;"><strong>Sum of Multiplications</strong></td>
<td style="text-align: left;"><strong>Trial</strong></td>
<td style="text-align: left;"><strong>Sum of Multiplications</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">1</td>
<td style="text-align: left;">95,430</td>
<td style="text-align: left;">11</td>
<td style="text-align: left;">95,406</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2</td>
<td style="text-align: left;">95,426</td>
<td style="text-align: left;">12</td>
<td style="text-align: left;">95,622</td>
</tr>
<tr class="even">
<td style="text-align: left;">3</td>
<td style="text-align: left;">95,446</td>
<td style="text-align: left;">13</td>
<td style="text-align: left;">95,250</td>
</tr>
<tr class="odd">
<td style="text-align: left;">4</td>
<td style="text-align: left;">95,381</td>
<td style="text-align: left;">14</td>
<td style="text-align: left;">95,599</td>
</tr>
<tr class="even">
<td style="text-align: left;">5</td>
<td style="text-align: left;">95,542</td>
<td style="text-align: left;">15</td>
<td style="text-align: left;">95,323</td>
</tr>
<tr class="odd">
<td style="text-align: left;">6</td>
<td style="text-align: left;">95,362</td>
<td style="text-align: left;">16</td>
<td style="text-align: left;">95,308</td>
</tr>
<tr class="even">
<td style="text-align: left;">7</td>
<td style="text-align: left;">95,508</td>
<td style="text-align: left;">17</td>
<td style="text-align: left;">95,220</td>
</tr>
<tr class="odd">
<td style="text-align: left;">8</td>
<td style="text-align: left;">95,590</td>
<td style="text-align: left;">18</td>
<td style="text-align: left;">95,443</td>
</tr>
<tr class="even">
<td style="text-align: left;">9</td>
<td style="text-align: left;">95,379</td>
<td style="text-align: left;">19</td>
<td style="text-align: left;">95,421</td>
</tr>
<tr class="odd">
<td style="text-align: left;">10</td>
<td style="text-align: left;">95,532</td>
<td style="text-align: left;">20</td>
<td style="text-align: left;">95,528</td>
</tr>
</tbody>
</table>
<p>More specifically, by the steps:</p>
<p><strong>Step 1.</strong> Write the ten I.Q. scores on one set of cards, and the ten athletic scores on another set of cards.</p>
<p><strong>Step 2.</strong> Pair the I.Q. and athletic-score cards at random. Multiply the scores in each pair, and add the results of the ten multiplications.</p>
<p><strong>Step 3.</strong> Subtract the experimental sum in step 2 from the observed sum, 95,759.</p>
<p><strong>Step 4.</strong> Repeat steps 2 and 3 twenty times.</p>
<p><strong>Step 5.</strong> Compute the proportion of trials where the difference is negative, which estimates the probability that an association as strong as the observed would occur by chance.</p>
<p>The sums of the multiplications for 20 trials are shown in Table 23-7. No random-trial sum was as high as the observed sum, which suggests that the probability of an association this strong happening by chance is so low as to approach zero. (An empirically-observed probability is never actually zero.)</p>
<p>This program can be solved particularly easily with RESAMPLING STATS. The arrays A and B in program “Ability3” list the athletic scores and the I.Q. scores respectively of 10 “actual” students ordered from highest to lowest athletic score. We MULTIPLY the corresponding elements of these arrays and proceed to compare the sum of these multiplications to the sums of experimental multiplications in which the elements are selected randomly.</p>
<p>Finally, we COUNT the trials in which the sum of the products of the randomly-paired athletic and I.Q. scores equals or exceeds the sum of the products in the observed data.</p>
<!--- Resampling stats file; Matlab syntax closeish -->
<div class="sourceCode" id="cb6"><pre class="sourceCode matlab code-with-copy"><code class="sourceCode matlab"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="er">' Program file: "correlation_causation_03.rss"</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="va">NUMBERS</span> (<span class="fl">97</span> <span class="fl">94</span> <span class="fl">93</span> <span class="fl">90</span> <span class="fl">87</span> <span class="fl">86</span> <span class="fl">86</span> <span class="fl">85</span> <span class="fl">81</span> <span class="fl">76</span>) <span class="va">a</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="er">' Record athletic scores, highest to lowest.</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="va">NUMBERS</span> (<span class="fl">114</span> <span class="fl">120</span> <span class="fl">107</span> <span class="fl">113</span> <span class="fl">118</span> <span class="fl">101</span> <span class="fl">109</span> <span class="fl">110</span> <span class="fl">100</span> <span class="fl">99</span>) <span class="va">b</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="er">' Record corresponding IQ scores for those students.</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="va">MULTIPLY</span> <span class="va">a</span> <span class="va">b</span> <span class="va">c</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="er">' Multiply the two sets of scores together.</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="va">SUM</span> <span class="va">c</span> <span class="va">d</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="er">' Sum the results — the "observed value."</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a><span class="va">REPEAT</span> <span class="fl">1000</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>    <span class="er">' Do 1000 experiments.</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>    <span class="va">SHUFFLE</span> <span class="va">a</span> <span class="va">e</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>    <span class="er">' Shuffle the athletic scores so we can pair them against IQ scores.</span></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>    <span class="va">MULTIPLY</span> <span class="va">e</span> <span class="va">b</span> <span class="va">f</span></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>    <span class="er">' Multiply the shuffled athletic scores by the I.Q. scores. (Note that we</span></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>    <span class="er">' could shuffle the I.Q. scores too but it would not achieve any greater</span></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>    <span class="er">' randomization.)</span></span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>    <span class="va">SUM</span> <span class="va">f</span> <span class="va">j</span></span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>    <span class="er">' Sum the randomized multiplications.</span></span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>    <span class="va">SUBTRACT</span> <span class="va">d</span> <span class="va">j</span> <span class="va">k</span></span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>    <span class="er">' Subtract the sum from the sum of the "observed" multiplication.</span></span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>    <span class="va">SCORE</span> <span class="va">k</span> <span class="va">z</span></span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>    <span class="er">' Keep track of the result in z.</span></span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a><span class="va">END</span></span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a><span class="er">' End one trial, go back and repeat until 1000 trials are complete.</span></span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a><span class="va">HISTOGRAM</span> <span class="va">z</span></span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a><span class="er">' Obtain a histogram of the trial results.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>Random Sums of Products</strong></p>
<p>ATHLETES &amp; IQ SCORES</p>
<p><img src="images/27-Chap-23_004.png" class="img-fluid"></p>
<p><strong>observed sum less random sum</strong></p>
<p>We see that obtaining a chance trial result as great as that observed was rare. RESAMPLING STATS will calculate this proportion for us:</p>
<!--- Resampling stats file; Matlab syntax closeish -->
<div class="sourceCode" id="cb7"><pre class="sourceCode matlab code-with-copy"><code class="sourceCode matlab"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="er">' Program file: "ability3.rss"</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="va">COUNT</span> <span class="va">z</span> <span class="op">&lt;=</span> <span class="fl">0</span> <span class="va">k</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="er">' Determine in how many trials the random sum of products was less than</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a><span class="er">' the observed sum of products.</span></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a><span class="va">DIVIDE</span> <span class="va">k</span> <span class="fl">1000</span> <span class="va">kk</span></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a><span class="er">' Convert to a proportion.</span></span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a><span class="va">PRINT</span> <span class="va">kk</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a><span class="er">' Note: The file "ability3" on the Resampling Stats software disk contains</span></span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a><span class="er">' this set of commands.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>Example 23-3: Correlation Between Adherence to Medication Regime and Change in Cholesterol</strong></p>
<p>Efron and Tibshirani <span class="citation" data-cites="efron1993bootstrap">(<a href="references.html#ref-efron1993bootstrap" role="doc-biblioref">1993, 72</a>)</span> show data on the extents to which 164 men a) took the drug prescribed to them (cholostyramine), and b) showed a decrease in total plasma cholesterol. Table 23-8 shows these values (note that a positive value in the “decrease in cholesterol” column denotes a decrease in cholesterol, while a negative value denotes an increase.)</p>
<p>Table 23-8</p>
<table class="table">
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Taken</strong></td>
<td style="text-align: left;"><strong>Taken</strong></td>
<td style="text-align: left;"><strong>Taken</strong></td>
<td></td>
<td style="text-align: left;"><strong>Taken</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">0 -5.25</td>
<td style="text-align: left;">27</td>
<td style="text-align: left;">-1.50 71</td>
<td>59.50</td>
<td style="text-align: left;">95 32.50</td>
</tr>
<tr class="odd">
<td style="text-align: left;">0 -7.25</td>
<td style="text-align: left;">28</td>
<td style="text-align: left;">23.50 71</td>
<td>14.75</td>
<td style="text-align: left;">95 70.75</td>
</tr>
<tr class="even">
<td style="text-align: left;">0 -6.25</td>
<td style="text-align: left;">29</td>
<td style="text-align: left;">33.00 72</td>
<td>63.00</td>
<td style="text-align: left;">95 18.25</td>
</tr>
<tr class="odd">
<td style="text-align: left;">0 11.50</td>
<td style="text-align: left;">31</td>
<td style="text-align: left;">4.25 72</td>
<td>0.00</td>
<td style="text-align: left;">95 76.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">2 21.00</td>
<td style="text-align: left;">32</td>
<td style="text-align: left;">18.75 73</td>
<td>42.00</td>
<td style="text-align: left;">95 75.75</td>
</tr>
<tr class="odd">
<td style="text-align: left;">2 -23.00</td>
<td style="text-align: left;">32</td>
<td style="text-align: left;">8.50 74</td>
<td>41.25</td>
<td style="text-align: left;">95 78.75</td>
</tr>
<tr class="even">
<td style="text-align: left;">2 5.75</td>
<td style="text-align: left;">33</td>
<td style="text-align: left;">3.25 75</td>
<td>36.25</td>
<td style="text-align: left;">95 54.75</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3 3.25</td>
<td style="text-align: left;">33</td>
<td style="text-align: left;">27.75 76</td>
<td>66.50</td>
<td style="text-align: left;">95 77.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">3 8.75</td>
<td style="text-align: left;">34</td>
<td style="text-align: left;">30.75 77</td>
<td>61.75</td>
<td style="text-align: left;">96 68.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">4 8.75</td>
<td style="text-align: left;">34</td>
<td style="text-align: left;">-1.50 77</td>
<td>14.00</td>
<td style="text-align: left;">96 73.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">4 -10.25</td>
<td style="text-align: left;">34</td>
<td style="text-align: left;">1.00 78</td>
<td>36.00</td>
<td style="text-align: left;">96 28.75</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7 -10.50</td>
<td style="text-align: left;">34</td>
<td style="text-align: left;">7.75 78</td>
<td>39.50</td>
<td style="text-align: left;">96 26.75</td>
</tr>
<tr class="even">
<td style="text-align: left;">8 19.75</td>
<td style="text-align: left;">35</td>
<td style="text-align: left;">-15.75 81</td>
<td>1.00</td>
<td style="text-align: left;">96 56.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">8 -0.50</td>
<td style="text-align: left;">36</td>
<td style="text-align: left;">33.50 82</td>
<td>53.50</td>
<td style="text-align: left;">96 47.50</td>
</tr>
<tr class="even">
<td style="text-align: left;">8 29.25</td>
<td style="text-align: left;">36</td>
<td style="text-align: left;">36.25 84</td>
<td>46.50</td>
<td style="text-align: left;">96 30.25</td>
</tr>
<tr class="odd">
<td style="text-align: left;">8 36.25</td>
<td style="text-align: left;">37</td>
<td style="text-align: left;">5.50 85</td>
<td>51.00</td>
<td style="text-align: left;">96 21.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">9 10.75</td>
<td style="text-align: left;">38</td>
<td style="text-align: left;">25.50 85</td>
<td>39.00</td>
<td style="text-align: left;">97 79.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">9 19.50</td>
<td style="text-align: left;">41</td>
<td style="text-align: left;">20.25 87</td>
<td>-0.25</td>
<td style="text-align: left;">97 69.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">9 17.25</td>
<td style="text-align: left;">43</td>
<td style="text-align: left;">33.25 87</td>
<td>1.00</td>
<td style="text-align: left;">97 80.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">10 3.50</td>
<td style="text-align: left;">45</td>
<td style="text-align: left;">56.75 87</td>
<td>46.75</td>
<td style="text-align: left;">97 86.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">10 11.25</td>
<td style="text-align: left;">45</td>
<td style="text-align: left;">4.25 87</td>
<td>11.50</td>
<td style="text-align: left;">98 54.75</td>
</tr>
<tr class="odd">
<td style="text-align: left;">11 -13.00</td>
<td style="text-align: left;">47</td>
<td style="text-align: left;">32.50 87</td>
<td>2.75</td>
<td style="text-align: left;">98 26.75</td>
</tr>
<tr class="even">
<td style="text-align: left;">12 24.00</td>
<td style="text-align: left;">50</td>
<td style="text-align: left;">54.50 88</td>
<td>48.75</td>
<td style="text-align: left;">98 80.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">13 2.50</td>
<td style="text-align: left;">50</td>
<td style="text-align: left;">-4.25 89</td>
<td>56.75</td>
<td style="text-align: left;">98 42.25</td>
</tr>
<tr class="even">
<td style="text-align: left;">15 3.00</td>
<td style="text-align: left;">51</td>
<td style="text-align: left;">42.75 90</td>
<td>29.25</td>
<td style="text-align: left;">98 6.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">15 5.50</td>
<td style="text-align: left;">51</td>
<td style="text-align: left;">62.75 90</td>
<td>72.50</td>
<td style="text-align: left;">98 104.75</td>
</tr>
<tr class="even">
<td style="text-align: left;">16 21.25</td>
<td style="text-align: left;">52</td>
<td style="text-align: left;">64.25 91</td>
<td>41.75</td>
<td style="text-align: left;">98 94.25</td>
</tr>
<tr class="odd">
<td style="text-align: left;">16 29.75</td>
<td style="text-align: left;">53</td>
<td style="text-align: left;">30.25 92</td>
<td>48.50</td>
<td style="text-align: left;">98 41.25</td>
</tr>
<tr class="even">
<td style="text-align: left;">17 7.50</td>
<td style="text-align: left;">54</td>
<td style="text-align: left;">14.75 92</td>
<td>61.25</td>
<td style="text-align: left;">98 40.25</td>
</tr>
<tr class="odd">
<td style="text-align: left;">18 -16.50</td>
<td style="text-align: left;">54</td>
<td style="text-align: left;">47.25 92</td>
<td>29.50</td>
<td style="text-align: left;">99 51.50</td>
</tr>
<tr class="even">
<td style="text-align: left;">20 4.50</td>
<td style="text-align: left;">56</td>
<td style="text-align: left;">18.00 92</td>
<td>59.75</td>
<td style="text-align: left;">99 82.75</td>
</tr>
<tr class="odd">
<td style="text-align: left;">20 39.00</td>
<td style="text-align: left;">57</td>
<td style="text-align: left;">13.75 93</td>
<td>71.00</td>
<td style="text-align: left;">99 85.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">21 -5.75</td>
<td style="text-align: left;">57</td>
<td style="text-align: left;">48.75 93</td>
<td>37.75</td>
<td style="text-align: left;">99 70.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">21 -21.00</td>
<td style="text-align: left;">58</td>
<td style="text-align: left;">43.00 93</td>
<td>41.00</td>
<td style="text-align: left;">100 92.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">21 0.25</td>
<td style="text-align: left;">60</td>
<td style="text-align: left;">27.75 93</td>
<td>9.75</td>
<td style="text-align: left;">100 73.75</td>
</tr>
<tr class="odd">
<td style="text-align: left;">22 -10.25</td>
<td style="text-align: left;">62</td>
<td style="text-align: left;">44.50 93</td>
<td>53.75</td>
<td style="text-align: left;">100 54.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">24 -0.50</td>
<td style="text-align: left;">64</td>
<td style="text-align: left;">22.50 94</td>
<td>62.50</td>
<td style="text-align: left;">100 69.50</td>
</tr>
<tr class="odd">
<td style="text-align: left;">25 -19.00</td>
<td style="text-align: left;">64</td>
<td style="text-align: left;">-14.50 94</td>
<td>39.00</td>
<td style="text-align: left;">100 101.50</td>
</tr>
<tr class="even">
<td style="text-align: left;">25 15.75</td>
<td style="text-align: left;">64</td>
<td style="text-align: left;">-20.75 94</td>
<td>3.25</td>
<td style="text-align: left;">100 68.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">26 6.00</td>
<td style="text-align: left;">67</td>
<td style="text-align: left;">46.25 94</td>
<td>60.00</td>
<td style="text-align: left;">100 44.75</td>
</tr>
<tr class="even">
<td style="text-align: left;">27 10.50</td>
<td style="text-align: left;">68</td>
<td style="text-align: left;">39.50 95</td>
<td>113.25</td>
<td style="text-align: left;">100 86.75</td>
</tr>
</tbody>
</table>
<p><strong>% Prescribed Dosage</strong></p>
<p><strong>Decrease in Cholesterol</strong></p>
<p><strong>% Prescribed Dosage</strong></p>
<p><strong>Decrease in Cholesterol</strong></p>
<p><strong>% Prescribed Dosage</strong></p>
<p><strong>Decrease in Cholesterol</strong></p>
<p><strong>% Prescribed Dosage</strong></p>
<p><strong>Decrease in Cholesterol</strong></p>
<p>The aim is to assess the effect of the compliance on the improvement. There are two related issues:</p>
<ol type="1">
<li><p>What form of regression should be fitted to these data, which we address later, and</p></li>
<li><p>Is there reason to believe that the relationship is meaningful? That is, we wish to ascertain if there is any meaningful correlation between the variables — because if there is no relationship between the variables, there is no basis for regressing one on the other. Sometimes people jump ahead in the latter question to first run the regression and then ask whether the regression slope coefficient(s) is (are) different than zero, but this usually is not sound practice. The sensible way to proceed is first to graph the data to see whether there is visible indication of a relationship.</p></li>
</ol>
<p>Efron and Tibshirani do this, and they find sufficient intuitive basis in the graph to continue the analysis. The next step is to investigate whether a measure of relationship is statistically significant; this we do as follows (program “inp10”):</p>
<ol type="1">
<li><p>Multiply the observed values for each of the 164 participants on the independent x variable (cholostyramine — percent of prescribed dosage actually taken) and the dependent y variable (cholesterol), and sum the results — it’s 439,140.</p></li>
<li><p>Randomly shuffle the dependent variable y values among the participants. The sampling is being done without replacement, though an equally good argument could be made for sampling with replacement; the results do not differ meaningfully, however, because the sample size is so large.</p></li>
<li><p>Then multiply these x and y hypothetical values for each of the 164 participants, sum the results and record.</p></li>
<li><p>Repeat steps 2 and 3 perhaps 1000 times.</p></li>
<li><p>Determine how often the shuffled sum-of-products exceeds the observed value (439,140).</p></li>
</ol>
<p>The following program in RESAMPLING STATS provides the solution:</p>
<!--- Resampling stats file; Matlab syntax closeish -->
<div class="sourceCode" id="cb8"><pre class="sourceCode matlab code-with-copy"><code class="sourceCode matlab"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="er">' Program file: "correlation_causation_05.rss"</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="va">READ</span> <span class="va">FILE</span> “<span class="va">inp10</span>” <span class="va">x</span> <span class="va">y</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="er">' Data</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="va">MULTIPLY</span> <span class="va">x</span> <span class="va">y</span> <span class="va">xy</span></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="er">' Step 1 above</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="va">SUM</span> <span class="va">xy</span> <span class="va">xysum</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="er">' Note: xysum = 439,140 (4.3914e+05)</span></span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a><span class="va">REPEAT</span> <span class="fl">1000</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>    <span class="er">' Do 1000 simulations (step 4 above)</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>    <span class="va">SHUFFLE</span> <span class="va">x</span> <span class="va">xrandom</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>    <span class="er">' Step 2 above</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>    <span class="va">MULTIPLY</span> <span class="va">xrandom</span> <span class="va">y</span> <span class="va">xy</span></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>    <span class="er">' Step 3 above</span></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>    <span class="va">SUM</span> <span class="va">xy</span> <span class="va">newsum</span></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>    <span class="er">' Step 3 above</span></span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>    <span class="va">SCORE</span> <span class="va">newsum</span> <span class="va">scrboard</span></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>    <span class="er">' Step 3 above</span></span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a><span class="va">END</span></span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a><span class="er">' Step 4 above</span></span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a><span class="va">COUNT</span> <span class="va">scorboard</span> <span class="op">&gt;=</span><span class="fl">439140</span> <span class="va">prob</span></span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a><span class="er">' Step 5 above</span></span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a><span class="va">PRINT</span> <span class="va">xysum</span> <span class="va">prob</span></span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a><span class="er">' Result: prob = 0. Interpretation: 1000 simulated random shufflings never</span></span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a><span class="er">' produced a sum-of-products as high as the observed value. Hence we rule</span></span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a><span class="er">' out random chance as an explanation for the observed correlation.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>Example 23-3: Is There A Relationship Between Drinking Beer And Being In Favor of Selling Beer?</strong> (Testing for a Relationship Between Counted-Data Variables.) (Program “Beerpoll”)</p>
<p>The data for athletic ability and I.Q. were measured. Therefore, we could use them in their original “cardinal” form, or we could split them up into “high” and “low” groups. Often, however, the individual observations are recorded only as “yes” or “no,” which makes it more difficult to ascertain the existence of a relationship. Consider the poll responses in Table 23-8 to two public-opinion survey questions: “Do you drink beer?” and “Are you in favor of local option on the sale of beer?”.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<!---
Page 278 in 4th edition, example 13-5.

The actual numbers are:

Question 2  Beer Yes Beer No
==========  ======== =======
Local Yes   37       20
Local No    15        6
-->
<p>Table 23-9</p>
<p><strong>Results of Observed Sample For Problem “Beerpoll”</strong></p>
<table class="table">
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Do you favor local option on the sale of beer?</strong></td>
<td style="text-align: left;"><strong>Do you drink beer?</strong></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: left;"><strong>Yes</strong></td>
<td><strong>No</strong></td>
<td><strong>Total</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Favor</td>
<td style="text-align: left;">45</td>
<td>20</td>
<td>65</td>
</tr>
<tr class="even">
<td style="text-align: left;">Don’t Favor</td>
<td style="text-align: left;">7</td>
<td>6</td>
<td>13</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Total</td>
<td style="text-align: left;">52</td>
<td>26</td>
<td>78</td>
</tr>
</tbody>
</table>
<p>Here is the statistical question: Is a person’s opinion on “local option” related to whether or not he drinks beer? Our resampling solution begins by noting that there are seventy-eight respondents, sixty-five of whom approve local option and thirteen of whom do not. Therefore write “approve” on sixty-five index cards and “not approve” on thirteen index cards. Now take <em>another</em> set of seventy-eight index cards, preferably of a different color, and write “yes” on fifty-two of them and “no” on twenty-six of them, corresponding to the numbers of people who do and do not drink beer in the sample. Now lay them down in random <em>pairs</em> , one from each pile.</p>
<p>If there is a high association between the variables, then real life observations will bunch up in the two diagonal cells in the upper left and lower right in Table 23-8. (Ignore the “total” data for now.) Therefore, subtract one sum of two diagonal cells from the other sum for the observed data: (45 + 6) - (20 + 7) = 24. Then compare this difference to the comparable differences found in random trials. The proportion of times that the simulated-trial difference exceeds the observed difference is the probability that the observed difference of +24 might occur by chance, even if there is no relationship between the two variables. (Notice that, in this case, we are working on the assumption that beer drinking is <em>positively</em> associated with approval of local option and not the inverse. We are interested only in differences that are equal to or exceed +24 when the northeast-southwest diagonal is subtracted from the northwest-southeast diagonal.)</p>
<p>We can carry out a resampling test with this procedure:</p>
<p><strong>Step 1.</strong> Write “approve” on 65 and “disapprove” on 13 red index cards, respectively; write “Drink” and “Don’t drink” on 52 and 26 white cards, respectively.</p>
<p><strong>Step 2.</strong> Pair the two sets of cards randomly. Count the numbers of the four possible pairs: (1) “approve-drink,” (2) “disapprove-don’t drink,” (3) “disapprove-drink,” and (4) “approve-don’t drink.” Record the number of these combinations, as in Table 23-10, where columns 1-4 correspond to the four cells in Table 23-9.</p>
<p><strong>Step 3.</strong> Add (column 1 plus column 4) and (column 2 plus column 3), and subtract the result in the second parenthesis from the result in the first parenthesis. If the difference is equal to or greater than 24, record “yes,” otherwise “no.”</p>
<p><strong>Step 4.</strong> Repeat steps 2 and 3 perhaps a hundred times.</p>
<p><strong>Step 5.</strong> Calculate the proportion “yes,” which estimates the probability that an association this great or greater would be observed by chance.</p>
<p>Table 23-10</p>
<p><strong>Results of One Random Trial of the Problem “Beerpoll”</strong></p>
<table class="table">
<colgroup>
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
</colgroup>
<tbody>
<tr class="odd">
<td></td>
<td><strong>(1)</strong></td>
<td><strong>(2)</strong></td>
<td><strong>(3)</strong></td>
<td><strong>(4)</strong></td>
<td><strong>(5)</strong></td>
</tr>
<tr class="even">
<td><strong>Trial</strong></td>
<td><strong>Approve Yes</strong></td>
<td><strong>Approve No</strong></td>
<td><strong>Disappr ove Yes</strong></td>
<td><strong>Disappr ove No</strong></td>
<td><p><strong>(Col 1 + Col 4) -</strong></p>
<p><strong>(Col 2 + Col 3)</strong></p></td>
</tr>
</tbody>
</table>
<p>1 43 22 9 4 47-31=16</p>
<p>A series of ten trials in this case (see Table 23-9) indicates that the observed difference is very often exceeded, which suggests that there is no relationship between beer drinking and opinion.</p>
<p>The RESAMPLING STATS program “Beerpoll” does this repetitively. From the “actual” sample results we know that 52 respondents drink beer and 26 do not. We create the vector “drink” with 52 “1”s for those who drink beer, and 26 “2”s for those who do not. We also create the vector “sale” with 65 “1”s (approve) and 13 “2”s (disapprove). In the actual sample, 51 of the 78 respondents had “consistent” responses to the two questions — that is, people who both favor the sale of beer <em>and</em> drink beer, or who are against the sale of beer <em>and</em> do not drink beer. We want to randomly pair the responses to the two questions to compare against that observed result to test the relationship.</p>
<p>To accomplish this aim, we REPEAT the following procedure 1000 times. We SHUFFLE drink to drink$ so that the responses are randomly ordered. Now when we SUBTRACT the corresponding elements of the two arrays, a “0” will appear in each element of the new array c for which there was consistency in the response of the two questions. We therefore COUNT the times that c equals “0” and place this result in d, and the number of times c does not equal 0, and place this result in e. Find the difference (d minus e), and SCORE this to z.</p>
<p>SCORE Z stores for each trial the number of consistent responses minus inconsistent responses. To determine whether the results of the actual sample indicate a relationship between the responses to the two questions, we check how often the random trials had a difference (between consistent and inconsistent responses) as great as 24, the value in the observed sample.</p>
<!--- Resampling stats file; Matlab syntax closeish -->
<div class="sourceCode" id="cb9"><pre class="sourceCode matlab code-with-copy"><code class="sourceCode matlab"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="er">' Program file: "beerpoll.rss"</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="va">URN</span> <span class="fl">52</span>#<span class="fl">1</span> <span class="fl">26</span>#<span class="fl">0</span> <span class="va">drink</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="er">' Constitute the set of 52 beer drinkers, represented by 52 "1"s, and the</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a><span class="er">' set of 26 non-drinkers, represented by "2"s.</span></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a><span class="va">URN</span> <span class="fl">57</span>#<span class="fl">1</span> <span class="fl">21</span>#<span class="fl">0</span> <span class="va">sale</span></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="er">' The same set of individuals classified by whether they favor ("1") or</span></span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a><span class="ss">' don'</span><span class="va">t</span> <span class="va">favor</span> (<span class="st">"0"</span>) <span class="va">the</span> <span class="va">sale</span> <span class="va">of</span> <span class="va">beer</span>.</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a><span class="er">' Note: F is now the vector {1 1 1 1 1 1 \... 0 0 0 0 0 \...} where 1 =</span></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="er">' people in favor, 0 = people opposed.</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a><span class="va">REPEAT</span> <span class="fl">1000</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a>    <span class="er">' Repeat the experiment 1000 times.</span></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>    <span class="va">SHUFFLE</span> <span class="va">drink</span> <span class="va">drink</span>$</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>    <span class="er">' Shuffle the beer drinkers/non-drinker, call the shuffled set drink\*.</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>    <span class="er">' Note: drink\$ is now a vector like {1 1 1 0 1 0 0 1 0 1 1 0 0 \...}</span></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a>    <span class="er">' where 1 = drinker, 0 = non-drinker.</span></span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a><span class="va">END</span></span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a><span class="va">SUBTRACT</span> <span class="va">drink</span>$ <span class="va">sale</span> <span class="va">c</span></span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a><span class="ss">' Subtract the favor/don'</span><span class="va">t</span> <span class="va">favor</span> <span class="va">set</span> <span class="va">from</span> <span class="va">the</span> <span class="va">drink</span><span class="op">/</span><span class="va">don</span><span class="op">'</span><span class="va">t</span> <span class="va">drink</span> <span class="va">set</span>.</span>
<span id="cb9-22"><a href="#cb9-22" aria-hidden="true" tabindex="-1"></a><span class="er">' Consistent responses are someone who drinks favoring the sale of beer (a</span></span>
<span id="cb9-23"><a href="#cb9-23" aria-hidden="true" tabindex="-1"></a><span class="ss">' "1" and a "1") or someone who doesn'</span><span class="va">t</span> <span class="va">drink</span> <span class="va">opposing</span> <span class="va">the</span> <span class="va">sale</span> <span class="va">of</span> <span class="va">beer</span>.</span>
<span id="cb9-24"><a href="#cb9-24" aria-hidden="true" tabindex="-1"></a><span class="er">' When subtracted, consistent responses *(and only consistent responses)*</span></span>
<span id="cb9-25"><a href="#cb9-25" aria-hidden="true" tabindex="-1"></a><span class="er">' produce a "0."</span></span>
<span id="cb9-26"><a href="#cb9-26" aria-hidden="true" tabindex="-1"></a><span class="va">COUNT</span> <span class="va">c</span> <span class="op">=</span><span class="fl">0</span> <span class="va">d</span></span>
<span id="cb9-27"><a href="#cb9-27" aria-hidden="true" tabindex="-1"></a><span class="er">' Count the number of consistent responses (those equal to "0").</span></span>
<span id="cb9-28"><a href="#cb9-28" aria-hidden="true" tabindex="-1"></a><span class="va">COUNT</span> <span class="va">c</span> <span class="op">&lt;&gt;</span> <span class="fl">0</span> <span class="va">e</span></span>
<span id="cb9-29"><a href="#cb9-29" aria-hidden="true" tabindex="-1"></a><span class="er">' Count the "inconsistent" responses (those not equal to "0").</span></span>
<span id="cb9-30"><a href="#cb9-30" aria-hidden="true" tabindex="-1"></a><span class="va">SUBTRACT</span> <span class="va">d</span> <span class="va">e</span> <span class="va">f</span></span>
<span id="cb9-31"><a href="#cb9-31" aria-hidden="true" tabindex="-1"></a><span class="er">' Find the difference</span></span>
<span id="cb9-32"><a href="#cb9-32" aria-hidden="true" tabindex="-1"></a><span class="va">SCORE</span> <span class="va">f</span> <span class="va">z</span></span>
<span id="cb9-33"><a href="#cb9-33" aria-hidden="true" tabindex="-1"></a><span class="er">' Keep track of the results of each trial.</span></span>
<span id="cb9-34"><a href="#cb9-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-35"><a href="#cb9-35" aria-hidden="true" tabindex="-1"></a><span class="er">' End one trial, go back and repeat until all 1000 trials are complete.</span></span>
<span id="cb9-36"><a href="#cb9-36" aria-hidden="true" tabindex="-1"></a><span class="va">HISTOGRAM</span> <span class="va">z</span></span>
<span id="cb9-37"><a href="#cb9-37" aria-hidden="true" tabindex="-1"></a><span class="er">' Produce a histogram of the trial result.</span></span>
<span id="cb9-38"><a href="#cb9-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-39"><a href="#cb9-39" aria-hidden="true" tabindex="-1"></a><span class="er">' Note: The file "beerpoll" on the Resampling Stats software disk contains</span></span>
<span id="cb9-40"><a href="#cb9-40" aria-hidden="true" tabindex="-1"></a><span class="er">' this set of commands.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>Are Drinkers More Likely to Favor Local Option &amp; Vice Versa</strong></p>
<p><img src="images/27-Chap-23_005.png" class="img-fluid"></p>
<p><strong># consistent responses thru chance draw</strong></p>
<p>The actual results showed a difference of 24. In the histogram we see that a difference that large or larger happened just by chance pairing — without any relationship between the two variables — 23% of the time. Hence, we conclude that there is little evidence of a relationship between the two variables.</p>
<p>Though the test just described may <em>generally</em> be appropriate for data of this sort, it may well not be appropriate in some particular case. Let’s consider a set of data where even if the test showed that an association existed, we would not believe the test result to be meaningful.</p>
<p>Suppose the survey results had been as presented in Table 23-11. We see that non-beer drinkers have a higher rate of approval of allowing beer drinking, which does not accord with experience or reason. Hence, without additional explanation we would not believe that a meaningful relationship exists among these variables even if the test showed one to exist. (Still another reason to doubt that a relationship exists is that the absolute differences are too small — there is only a 6% difference in disapproval between drink and don’t drink groups — to mean anything to anyone. On both grounds, then, it makes sense simply to act as if there were no difference between the two groups and to run <em>no test</em> .).</p>
<p>Table 23-11</p>
<p><strong>Beer Poll In Which Results Are Not In Accord With Expectation Or Reason</strong></p>
<table class="table">
<tbody>
<tr class="odd">
<td></td>
<td style="text-align: left;"><strong>% Approve</strong></td>
<td style="text-align: left;"><strong>% Disapprove</strong></td>
<td style="text-align: left;"><strong>Total</strong></td>
</tr>
<tr class="even">
<td>Beer Drinkers</td>
<td style="text-align: left;">71%</td>
<td style="text-align: left;">29%</td>
<td style="text-align: left;">100%</td>
</tr>
<tr class="odd">
<td>Non-Beer Drinkers</td>
<td style="text-align: left;">77%</td>
<td style="text-align: left;">23%</td>
<td style="text-align: left;">100%</td>
</tr>
</tbody>
</table>
<p>The lesson to be learned from this is that one should inspect the data carefully before applying a statistical test, and only test for “significance” if the apparent relationships accord with theory, general understanding, and common sense.</p>
<p><strong>Example 23-4: Do Athletes Really Have “Slumps”?</strong> (Are Successive Events in a Series Independent, or is There a Relationship Between Them?)</p>
<p>The important concept of independent events was introduced earlier. Various scientific and statistical decisions depend upon whether or not a series of events is independent. But how does one know whether or not the events are independent? Let us consider a baseball example.</p>
<p>Baseball players and their coaches believe that on some days and during some weeks a player will bat better than on other days and during other weeks. And team managers and coaches act on the belief that there are periods in which players do poorly — slumps — by temporarily replacing the player with another after a period of poor performance. The underlying belief is that a series of failures indicates a temporary (or permanent) change in the player’s capacity to play well, and it therefore makes sense to replace him until the evil spirit passes on, either of its own accord or by some change in the player’s style.</p>
<p>But even if his hits come randomly, a player will have runs of good luck and runs of bad luck just by chance — just as does a card player. The problem, then, is to determine whether (a) the runs of good and bad batting are merely runs of chance, and the probability of success for each event remains the same throughout the series of events — which would imply that the batter’s ability is the same at all times, and coaches should not take recent performance heavily into account when deciding which players should play; or (b) whether a batter really does have a tendency to do better at some times than at others, which would imply that there is some relationship between the occurrence of success in one trial event and the probability of success in the next trial event, and therefore that it is reasonable to replace players from time to time.</p>
<p>Let’s analyze the batting of a player we shall call “Slug.” Here are the results of Slug’s first 100 times at bat during the 1987 season (“H” = hit, “X” = out):</p>
<p>X X X X X X H X X H X H H X X X X X X X X H X X X X X H X X X X H H X X X X X H X X H X H X X X H H X X X X X H X H X X X X H H X H H X X X X X X X X X X H X X X H X X H X X H X H X X H X X X H X X X.</p>
<p>Now, do Slug’s hits tend to come in bunches? That would be the case if he really did have a tendency to do better at some times than at others. Therefore, let us compare Slug’s results with those of a deck of cards or a set of random numbers that we know has no tendency to do better at some times than at others.</p>
<p>During this period of 100 times at bat, Slug has averaged one hit in every four times at bat — a .250 batting average. This average is the same as the chance of one card suit’s coming up. We designate hearts as “hits” and prepare a deck of 100 cards, twenty-five “H”s (hearts, or “hit”) and seventy-five “X”s (other suit, or “out”). Here is the sequence in which the 100 randomly-shuffled cards fell:</p>
<p>X X H X X X X H H X X X H H H X X X X X H X X X H X X H X X X X H X H H X X X X X X X X X H X X X X X X H H X X X X X H H H X X X X X X H X H X H X X H X H X X X X X X X X X H X X X X X X X H H H X X.</p>
<p>Now we can compare whether or not Slug’s hits are bunched up more than they would be by random chance; we can do so by <em>counting the clusters</em> (also called “runs”) of consecutive hits and outs for Slug and for the cards. Slug had forty-three clusters, which is more than the thirty-seven clusters in the cards; it therefore does not seem that there is a tendency for Slug’s hits to cluster together. (A larger number of clusters indicates a lower tendency to cluster.)</p>
<p>Of course, the single trial of 100 cards shown above might have an unusually high or low number of clusters. To be safer, lay out, (say,) ten trials of 100 cards each, and compare Slug’s number of clusters with the various trials. The proportion of trials with more clusters than Slug’s indicates whether or not Slug’s hits have a tendency to bunch up. (But caution: This proportion cannot be interpreted directly as a probability.)</p>
<p>Now the steps:</p>
<p><strong>Step 1.</strong> Constitute a bucket with 3 slips of paper that say “out” and one that says “hit.” Or “01-25” = hits (H), “26-00” = outs (X), Slug’s long-run average.</p>
<p><strong>Step 2.</strong> Sample 100 slips of paper, with replacement, record “hit” or “out” each time, or write a series of “H’s” or “X’s” corresponding to 100 numbers, each selected randomly between 1 and 100.</p>
<p><strong>Step 3.</strong> Count the number of “clusters,” that is, the number of “runs” of the same event, “H”s or “X”s.</p>
<p><strong>Step 4.</strong> Compare the outcome in step 3 with Slug’s outcome, 43 clusters. If 43 or fewer; write “yes,” otherwise “no.”</p>
<p><strong>Step 5.</strong> Repeat steps 2-4 a hundred times.</p>
<p><strong>Step 6.</strong> Compute the proportion “yes.” This estimates the probability that Slug’s record is not characterized by more “slumps” than would be caused by chance. A very low proportion of “yeses” indicates longer (and hence fewer) “streaks” and “slumps” than would result by chance.</p>
<p>In RESAMPLING STATS, we can do this experiment 1000 times.</p>
<!--- Resampling stats file; Matlab syntax closeish -->
<div class="sourceCode" id="cb10"><pre class="sourceCode matlab code-with-copy"><code class="sourceCode matlab"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="er">' Program file: "sluggo.rss"</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="va">REPEAT</span> <span class="fl">1000</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>    <span class="va">URN</span> <span class="fl">3</span>#<span class="fl">0</span> <span class="fl">1</span>#<span class="fl">1</span> <span class="va">a</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>    <span class="va">SAMPLE</span> <span class="fl">100</span> <span class="va">a</span> <span class="va">b</span></span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>    <span class="er">' Sample 100 "at-bats" from a</span></span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>    <span class="va">RUNS</span> <span class="va">b</span> <span class="op">&gt;=</span><span class="fl">1</span> <span class="va">c</span></span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a>    <span class="er">' How many runs (of any length \&gt;=1) are there in the 100 at-bats?</span></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a>    <span class="va">SCORE</span> <span class="va">c</span> <span class="va">z</span></span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a><span class="va">END</span></span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a><span class="va">HISTOGRAM</span> <span class="va">z</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a><span class="er">' Note: The file "sluggo" on the Resampling Stats software disk contains</span></span>
<span id="cb10-13"><a href="#cb10-13" aria-hidden="true" tabindex="-1"></a><span class="er">' this set of commands.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Examining the histogram, we see that 43 runs is not at all an unusual occurrence:</p>
<p><strong>“Runs” in 100 At-Bats</strong></p>
<p><img src="images/27-Chap-23_006.png" class="img-fluid"></p>
<p><strong># “runs” of same outcome</strong></p>
<p>The manager wants to look at this matter in a somewhat different fashion, however. He insists that the existence of slumps is proven by the fact that the player sometimes does not get a hit for an abnormally long period of time. One way of testing whether or not the coach is right is by comparing an average player’s longest slump in a 100-at-bat season with the longest run of outs in the first card trial. Assume that Slug is a player picked <em>at random</em> . Then compare Slug’s longest slump — say, 10 outs in a row — with the longest cluster of a single simulated 100-at-bat trial with the cards, 9 outs. This result suggests that Slug’s apparent slump might well have resulted by chance.</p>
<p>The estimate can be made more accurate by taking the <em>average</em> longest slump (cluster of outs) in ten simulated 400-at-bat trials. But notice that we do <em>not</em> compare Slug’s slump against the <em>longest</em> slump found in ten such simulated trials. We want to know the longest cluster of outs that would be found under <em>average</em> conditions, and the hand with the <em>longest</em> slump is <em>not</em> average or typical. Determining whether to compare Slug’s slump with the <em>average</em> longest slump or with the <em>longest</em> of the ten longest slumps is a decision of crucial importance. There are no mathematical or logical rules to help you. What is required is hard, clear thinking. Experience can help you think clearly, of course, but these decisions are not easy or obvious even to the most experienced statisticians.</p>
<p>The coach may then refer to the protracted slump of one of the twenty-five players on his team to prove that slumps really occur. But, of twenty-five random 100-at-bat trials, one will contain a slump longer than any of the other twenty-four, and that slump will be considerably longer than average. A fair comparison, then, would be between the longest slump of his longest-slumping player, and the longest run of outs found among twenty-five random trials. In fact, the longest run among twenty-five hands of 100 cards was fifteen outs in a row. And, if we had set some of the hands for lower (and higher) batting averages than .250, the longest slump in the cards would have been even longer.</p>
<p>Research by Roberts and his students at the University of Chicago shows that in fact slumps do <em>not</em> exist, as I conjectured in the first publication of this material in 1969. (Of course, a batter feels as if he has a better chance of getting a hit at some times than at other times. After a series of successful at-bats, sandlot players and professionals alike feel confident — just as gamblers often feel that they’re on a “streak.” But there seems to be no connection between a player’s performance and whether he feels hot or cold, astonishing as that may be.)</p>
<p>Averages over longer periods may vary systematically, as Ty Cobb’s annual batting average varied non-randomly from season to season, Roberts found. But short-run analyses of dayto-day and week-to-week individual and team performances in most sports have shown results similar to the outcomes that a lottery-type random-number machine would produce.</p>
<p>Remember, too, the study by Gilovich, Vallone, and Twersky of basketball mentioned in <a href="sampling_variability.html" class="quarto-xref"><span>Chapter&nbsp;14</span></a>. To repeat, their analyses “provided no evidence for a positive correlation between the outcomes of successive shots.” That is, knowing whether a shooter has or has not scored on the previous sheet — or in any previous sequence of shots — is useless for predicting whether he will score again.</p>
<p>The species homo sapiens apparently has a powerful propensity to believe that one can find a pattern even when there is no pattern to be found. Two decades ago I cooked up several series of random numbers that looked like weekly prices of publicly-traded stocks. Players in the experiment were told to buy and sell stocks as they chose. Then I repeatedly gave them “another week’s prices,” and allowed them to buy and sell again. The players did all kinds of fancy calculating, using a wild variety of assumptions — although there was no possible way that the figuring could help them.</p>
<p>When I stopped the game before completing the 10 buy-and-sell sessions they expected, subjects would ask that the game go on. Then I would tell them that there was no basis to believe that there were patterns in the data, because the “prices” were just randomly-generated numbers. Winning or losing therefore did not depend upon the subjects’ skill. Nevertheless, they demanded that the game not stop until the 10 “weeks” had been played, so they could find out whether they “won” or “lost.”</p>
<p>This study of batting illustrates how one can test for independence among various trials. The trials are independent if each observation is randomly chosen with replacement from the universe, in which case there is no reason to believe that one observation will be related to the observations directly before and after; as it is said, “the coin has no memory.”</p>
<p>The year-to-year level of Lake Michigan is an example in which observations are <em>not</em> independent. If Lake Michigan is very high in one year, it is likely to be higher than average the following year because some of the high level carries over from one year into the next.<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a> We could test this hypothesis by writing down whether the level in each year from, say, 1860 to 1975 was higher or lower than the median level for those years. We would then count the number of runs of “higher” and “lower” and compare the number of runs of “black” and “red” with a deck of that many cards; we would find fewer runs in the lake level than in an average hand of 116 (1976-1860) cards, though this test is hardly necessary. (But are the <em>changes</em> in Lake Michigan’s level independent from year to year? If the level went up last year, is there a better than 50-50 chance that the level will also go up this year? The answer to this question is not so obvious. One could compare the numbers of runs of ups and downs against an average hand of cards, just as with the hits and outs in baseball.)</p>
<p>Exercise for students: How could one check whether the successive numbers in a random-number table are independent?</p>
</section>
<section id="exercises" class="level2" data-number="29.5">
<h2 data-number="29.5" class="anchored" data-anchor-id="exercises"><span class="header-section-number">29.5</span> Exercises</h2>
<p>Solutions for problems may be found in the section titled, “Exercise Solutions” at the back of this book.</p>
<p><strong>Exercise 23-1</strong></p>
<p>Table 23-12 shows voter participation rates in the various states in the 1844 presidential election. Should we conclude that there was a negative relationship between the participation rate (a) and the vote spread (b) between the parties in the election? (Adapted from <span class="citation" data-cites="noreen1989computer">(<a href="references.html#ref-noreen1989computer" role="doc-biblioref">Noreen 1989, 20</a>, Table 2-4)</span>:</p>
<p>Table 23-12</p>
<p><strong>Voter Participation In The 1844 Presidential Election</strong></p>
<table class="table">
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>State</strong></td>
<td style="text-align: left;"><strong>Participation (a)</strong></td>
<td style="text-align: left;"><strong>Spread (b)</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">Maine</td>
<td style="text-align: left;">67.5</td>
<td style="text-align: left;">13</td>
</tr>
<tr class="odd">
<td style="text-align: left;">New Hampshire</td>
<td style="text-align: left;">65.6</td>
<td style="text-align: left;">19</td>
</tr>
<tr class="even">
<td style="text-align: left;">Vermont</td>
<td style="text-align: left;">65.7</td>
<td style="text-align: left;">18</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Massachusetts</td>
<td style="text-align: left;">59.3</td>
<td style="text-align: left;">12</td>
</tr>
<tr class="even">
<td style="text-align: left;">Rhode Island</td>
<td style="text-align: left;">39.8</td>
<td style="text-align: left;">20</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Connecticut</td>
<td style="text-align: left;">76.1</td>
<td style="text-align: left;">5</td>
</tr>
<tr class="even">
<td style="text-align: left;">New York</td>
<td style="text-align: left;">73.6</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">New Jersey</td>
<td style="text-align: left;">81.6</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Pennsylvania</td>
<td style="text-align: left;">75.5</td>
<td style="text-align: left;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Delaware</td>
<td style="text-align: left;">85.0</td>
<td style="text-align: left;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Maryland</td>
<td style="text-align: left;">80.3</td>
<td style="text-align: left;">5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Virginia</td>
<td style="text-align: left;">54.5</td>
<td style="text-align: left;">6</td>
</tr>
<tr class="even">
<td style="text-align: left;">North Carolina</td>
<td style="text-align: left;">79.1</td>
<td style="text-align: left;">5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Georgia</td>
<td style="text-align: left;">94.0</td>
<td style="text-align: left;">4</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kentucky</td>
<td style="text-align: left;">80.3</td>
<td style="text-align: left;">8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Tennessee</td>
<td style="text-align: left;">89.6</td>
<td style="text-align: left;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Louisiana</td>
<td style="text-align: left;">44.7</td>
<td style="text-align: left;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Alabama</td>
<td style="text-align: left;">82.7</td>
<td style="text-align: left;">8</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mississippi</td>
<td style="text-align: left;">89.7</td>
<td style="text-align: left;">13</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Ohio</td>
<td style="text-align: left;">83.6</td>
<td style="text-align: left;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Indiana</td>
<td style="text-align: left;">84.9</td>
<td style="text-align: left;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Illinois</td>
<td style="text-align: left;">76.3</td>
<td style="text-align: left;">12</td>
</tr>
<tr class="even">
<td style="text-align: left;">Missouri</td>
<td style="text-align: left;">74.7</td>
<td style="text-align: left;">17</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Arkansas</td>
<td style="text-align: left;">68.8</td>
<td style="text-align: left;">26</td>
</tr>
<tr class="even">
<td style="text-align: left;">Michigan</td>
<td style="text-align: left;">79.3</td>
<td style="text-align: left;">6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">National Average</td>
<td style="text-align: left;">74.9</td>
<td style="text-align: left;">9</td>
</tr>
</tbody>
</table>
<p>The observed correlation coefficient between voter participation and spread is -.37398. Is this more negative that what might occur by chance, if no correlation exists?</p>
<p><strong>Exercise 23-2</strong></p>
<p>We would like to know whether, among major-league baseball players, home runs (per 500 at-bats) and strikeouts (per 500 at-bat’s) are correlated. We first use the procedure as used above for I.Q. and athletic ability — multiplying the elements within each pair. (We will later use a more “sophisticated” measure, the correlation coefficient.)</p>
<p>The data for 18 randomly-selected players in the 1989 season are as follows, as they would appear in the first lines of the program.</p>
<!--- Resampling stats file; Matlab syntax closeish -->
<div class="sourceCode" id="cb11"><pre class="sourceCode matlab code-with-copy"><code class="sourceCode matlab"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="er">' Program file: "correlation_causation_08.rss"</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="va">NUMBERS</span> (<span class="fl">14</span> <span class="fl">20</span> <span class="fl">0</span> <span class="fl">38</span> <span class="fl">9</span> <span class="fl">38</span> <span class="fl">22</span> <span class="fl">31</span> <span class="fl">33</span> <span class="fl">11</span> <span class="fl">40</span> <span class="fl">5</span> <span class="fl">15</span> <span class="fl">32</span> <span class="fl">3</span> <span class="fl">29</span> <span class="fl">5</span> <span class="fl">32</span>) <span class="va">homeruns</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="va">NUMBERS</span> (<span class="fl">135</span> <span class="fl">153</span> <span class="fl">120</span> <span class="fl">161</span> <span class="fl">138</span> <span class="fl">175</span> <span class="fl">126</span> <span class="fl">200</span> <span class="fl">205</span> <span class="fl">147</span> <span class="fl">165</span> <span class="fl">124</span> <span class="fl">169</span> <span class="fl">156</span> <span class="fl">36</span> <span class="fl">98</span> <span class="fl">82</span> <span class="fl">131</span>) <span class="va">strikeout</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="er">' Exercise: Complete this program.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>Exercise 23-3</strong></p>
<p>In the previous example relating strikeouts and home runs, we used the procedure of multiplying the elements within each pair. Now we use a more “sophisticated” measure, the correlation coefficient, which is simply a standardized form of the multiplicands, but sufficiently well known that we calculate it with a pre-set command.</p>
<p>Exercise: Write a program that uses the correlation coefficient to test the significance of the association between home runs and strikeouts.</p>
<p><strong>Exercise 23-4</strong></p>
<p>All the other things equal, an increase in a country’s money supply is inflationary and should have a negative impact on the exchange rate for the country’s currency. The data in the following table were computed using data from tables in the 1983/1984 <em>Statistical Yearbook of the United Nations</em> :</p>
<p>Table 23-13</p>
<p><strong>Money Supply and Exchange Rate Changes</strong></p>
<p><strong>% Change % Change % Change % Change</strong></p>
<p><strong>Exch. Rate Money Supply Exch. Rate Money Supply</strong></p>
<table class="table">
<tbody>
<tr class="odd">
<td style="text-align: left;">Australia</td>
<td style="text-align: left;">0.089</td>
<td style="text-align: left;">0.035</td>
<td style="text-align: left;">Belgium</td>
<td style="text-align: left;">0.134</td>
<td style="text-align: left;">0.003</td>
</tr>
<tr class="even">
<td style="text-align: left;">Botswana</td>
<td style="text-align: left;">0.351</td>
<td style="text-align: left;">0.085</td>
<td style="text-align: left;">Burma</td>
<td style="text-align: left;">0.064</td>
<td style="text-align: left;">0.155</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Burundi</td>
<td style="text-align: left;">0.064</td>
<td style="text-align: left;">0.064</td>
<td style="text-align: left;">Canada</td>
<td style="text-align: left;">0.062</td>
<td style="text-align: left;">0.209</td>
</tr>
<tr class="even">
<td style="text-align: left;">Chile</td>
<td style="text-align: left;">0.465</td>
<td style="text-align: left;">0.126</td>
<td style="text-align: left;">China</td>
<td style="text-align: left;">0.411</td>
<td style="text-align: left;">0.555</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Costa Rica</td>
<td style="text-align: left;">0.100</td>
<td style="text-align: left;">0.100</td>
<td style="text-align: left;">Cyprus</td>
<td style="text-align: left;">0.158</td>
<td style="text-align: left;">0.044</td>
</tr>
<tr class="even">
<td style="text-align: left;">Denmark</td>
<td style="text-align: left;">0.140</td>
<td style="text-align: left;">0.351</td>
<td style="text-align: left;">Ecuador</td>
<td style="text-align: left;">0.242</td>
<td style="text-align: left;">0.356</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fiji</td>
<td style="text-align: left;">0.093</td>
<td style="text-align: left;">0.000</td>
<td style="text-align: left;">Finland</td>
<td style="text-align: left;">0.124</td>
<td style="text-align: left;">0.164</td>
</tr>
<tr class="even">
<td style="text-align: left;">France</td>
<td style="text-align: left;">0.149</td>
<td style="text-align: left;">0.090</td>
<td style="text-align: left;">Germany</td>
<td style="text-align: left;">0.156</td>
<td style="text-align: left;">0.061</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Greece</td>
<td style="text-align: left;">0.302</td>
<td style="text-align: left;">0.202</td>
<td style="text-align: left;">Hungary</td>
<td style="text-align: left;">0.133</td>
<td style="text-align: left;">0.049</td>
</tr>
<tr class="even">
<td style="text-align: left;">India</td>
<td style="text-align: left;">0.187</td>
<td style="text-align: left;">0.184</td>
<td style="text-align: left;">Indonesia</td>
<td style="text-align: left;">0.080</td>
<td style="text-align: left;">0.132</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Italy</td>
<td style="text-align: left;">0.167</td>
<td style="text-align: left;">0.124</td>
<td style="text-align: left;">Jamaica</td>
<td style="text-align: left;">0.504</td>
<td style="text-align: left;">0.237</td>
</tr>
<tr class="even">
<td style="text-align: left;">Japan</td>
<td style="text-align: left;">0.081</td>
<td style="text-align: left;">0.069</td>
<td style="text-align: left;">Jordan</td>
<td style="text-align: left;">0.092</td>
<td style="text-align: left;">0.010</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Kenya</td>
<td style="text-align: left;">0.144</td>
<td style="text-align: left;">0.141</td>
<td style="text-align: left;">Korea</td>
<td style="text-align: left;">0.040</td>
<td style="text-align: left;">0.006</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kuwait</td>
<td style="text-align: left;">0.038</td>
<td style="text-align: left;">-0.180</td>
<td style="text-align: left;">Lebanon</td>
<td style="text-align: left;">0.619</td>
<td style="text-align: left;">0.065</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Madagascar</td>
<td style="text-align: left;">0.337</td>
<td style="text-align: left;">0.244</td>
<td style="text-align: left;">Malawi</td>
<td style="text-align: left;">0.205</td>
<td style="text-align: left;">0.203</td>
</tr>
<tr class="even">
<td style="text-align: left;">Malaysia</td>
<td style="text-align: left;">0.037</td>
<td style="text-align: left;">-0.006</td>
<td style="text-align: left;">Malta</td>
<td style="text-align: left;">0.003</td>
<td style="text-align: left;">0.003</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mauritania</td>
<td style="text-align: left;">0.180</td>
<td style="text-align: left;">0.192</td>
<td style="text-align: left;">Mauritius</td>
<td style="text-align: left;">0.226</td>
<td style="text-align: left;">0.136</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mexico</td>
<td style="text-align: left;">0.338</td>
<td style="text-align: left;">0.599</td>
<td style="text-align: left;">Morocco</td>
<td style="text-align: left;">0.076</td>
<td style="text-align: left;">0.076</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Netherlands</td>
<td style="text-align: left;">0.158</td>
<td style="text-align: left;">0.078</td>
<td style="text-align: left;">New Zealand</td>
<td style="text-align: left;">0.370</td>
<td style="text-align: left;">0.098</td>
</tr>
<tr class="even">
<td style="text-align: left;">Nigeria</td>
<td style="text-align: left;">0.079</td>
<td style="text-align: left;">0.082</td>
<td style="text-align: left;">Norway</td>
<td style="text-align: left;">0.177</td>
<td style="text-align: left;">0.242</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Papua</td>
<td style="text-align: left;">0.075</td>
<td style="text-align: left;">0.209</td>
<td style="text-align: left;">Philippines</td>
<td style="text-align: left;">0.411</td>
<td style="text-align: left;">0.035</td>
</tr>
<tr class="even">
<td style="text-align: left;">Portugal</td>
<td style="text-align: left;">0.288</td>
<td style="text-align: left;">0.166</td>
<td style="text-align: left;">Romania</td>
<td style="text-align: left;">-0.029</td>
<td style="text-align: left;">0.039</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Rwanda</td>
<td style="text-align: left;">0.059</td>
<td style="text-align: left;">0.083</td>
<td style="text-align: left;">Samoa</td>
<td style="text-align: left;">0.348</td>
<td style="text-align: left;">0.118</td>
</tr>
<tr class="even">
<td style="text-align: left;">Saudi Arabia</td>
<td style="text-align: left;">0.023</td>
<td style="text-align: left;">0.023</td>
<td style="text-align: left;">Seychelles</td>
<td style="text-align: left;">0.063</td>
<td style="text-align: left;">0.031</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Singapore</td>
<td style="text-align: left;">0.024</td>
<td style="text-align: left;">0.030</td>
<td style="text-align: left;">Solomon Is</td>
<td style="text-align: left;">0.101</td>
<td style="text-align: left;">0.526</td>
</tr>
<tr class="even">
<td style="text-align: left;">Somalia</td>
<td style="text-align: left;">0.481</td>
<td style="text-align: left;">0.238</td>
<td style="text-align: left;">South Africa</td>
<td style="text-align: left;">0.624</td>
<td style="text-align: left;">0.412</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Spain</td>
<td style="text-align: left;">0.107</td>
<td style="text-align: left;">0.086</td>
<td style="text-align: left;">Sri Lanka</td>
<td style="text-align: left;">0.051</td>
<td style="text-align: left;">0.141</td>
</tr>
<tr class="even">
<td style="text-align: left;">Switzerland</td>
<td style="text-align: left;">0.186</td>
<td style="text-align: left;">0.186</td>
<td style="text-align: left;">Tunisia</td>
<td style="text-align: left;">0.193</td>
<td style="text-align: left;">0.068</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Turkey</td>
<td style="text-align: left;">0.573</td>
<td style="text-align: left;">0.181</td>
<td style="text-align: left;">UK</td>
<td style="text-align: left;">0.255</td>
<td style="text-align: left;">0.154</td>
</tr>
<tr class="even">
<td style="text-align: left;">USA</td>
<td style="text-align: left;">0.000</td>
<td style="text-align: left;">0.156</td>
<td style="text-align: left;">Vanatuva</td>
<td style="text-align: left;">0.008</td>
<td style="text-align: left;">0.331</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Yemen</td>
<td style="text-align: left;">0.253</td>
<td style="text-align: left;">0.247</td>
<td style="text-align: left;">Yugoslavia</td>
<td style="text-align: left;">0.685</td>
<td style="text-align: left;">0.432</td>
</tr>
<tr class="even">
<td style="text-align: left;">Zaire</td>
<td style="text-align: left;">0.343</td>
<td style="text-align: left;">0.244</td>
<td style="text-align: left;">Zambia</td>
<td style="text-align: left;">0.457</td>
<td style="text-align: left;">0.094</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Zimbabwe</td>
<td style="text-align: left;">0.359</td>
<td style="text-align: left;">0.164</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
<p>Percentage changes in exchange rates and money supply between 1983 and 1984 for various countries.</p>
<p>Are changes in the exchange rates and in money supplies related to each other? That is, are they correlated?</p>
<!---
Original text has "(Adapted from Noreen (1990)".  It isn't obvious how it
would be adapted from Noreen (1989), and otherwise, what Noreen (1990) might
be.
-->
<p>Exercise: Should the algorithm of non-computer resampling steps be similar to the algorithm for I.Q. and athletic ability shown in the text? One can also work with the correlation coefficient rather then the sum-of-products method, and expect to get the same result.</p>
<ol type="1">
<li><p>Write a series of non-computer resampling steps to solve this problem.</p></li>
<li><p>Write a computer program to implement those steps.</p></li>
</ol>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-dixon1983introduction" class="csl-entry" role="listitem">
Dixon, Wilfrid J, and Frank J Massey Jr. 1983. <span>“Introduction to Statistical Analysis.”</span>
</div>
<div id="ref-efron1993bootstrap" class="csl-entry" role="listitem">
Efron, Bradley, and Robert J Tibshirani. 1993. <span>“An Introduction to the Bootstrap.”</span> In <em>Monographs on Statistics and Applied Probability</em>, edited by David R Cox, David V Hinkley, Nancy Reid, Donald B Rubin, and Bernard W Silverman. Vol. 57. New York: <span>Chapman &amp; Hall</span>.
</div>
<div id="ref-noreen1989computer" class="csl-entry" role="listitem">
Noreen, Eric W. 1989. <em>Computer-Intensive Methods for Testing Hypotheses</em>. New York: John Wiley &amp; Sons. <a href="https://archive.org/details/computerintensiv0000nore">https://archive.org/details/computerintensiv0000nore</a>.
</div>
<div id="ref-simon1985basic" class="csl-entry" role="listitem">
Simon, Julian Lincoln, and Paul Burstein. 1985. <em>Basic Research Methods in Social Science</em>. 3rd ed. New York: Random House.
</div>
<div id="ref-wallis1956statistics" class="csl-entry" role="listitem">
Wallis, Wilson Allen, and Harry V Roberts. 1956. <em>Statistics, a New Approach.</em> New York: The Free Press.
</div>
</div>
</section>
<aside id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>For a much fuller discussion on causality and causation, see Simon and Burstein <span class="citation" data-cites="simon1985basic">(<a href="references.html#ref-simon1985basic" role="doc-biblioref">1985</a>)</span>.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>These data are from an example in <span class="citation" data-cites="dixon1983introduction">(<a href="references.html#ref-dixon1983introduction" role="doc-biblioref">Dixon and Massey Jr 1983, 278</a>)</span>, in which the problem is tackled conventionally with a chi-square test.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Example from <span class="citation" data-cites="wallis1956statistics">(<a href="references.html#ref-wallis1956statistics" role="doc-biblioref">Wallis and Roberts 1956, 565</a> – 556)</span>.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</aside>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./reliability_average.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Some Last Words About the Reliability of Sample Averages</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./how_big_sample.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">How Large a Sample?</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>