<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.51">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Resampling statistics - 10&nbsp; Two puzzles and more tools</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./probability_theory_2_compound.html" rel="next">
<link href="./probability_theory_1b.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<script type="text/javascript">
  $(document).ready(function() {
    $("table").addClass('lightable-paper lightable-striped lightable-hover')
  });
</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="style.css">
<link rel="stylesheet" href="font-awesome.min.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./more_sampling_tools.html"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Two puzzles and more tools</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Resampling statistics</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R edition</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface_third.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface to the third edition</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface_second.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface to the second edition</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./resampling_method.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The resampling method</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./what_is_probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">What is probability?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./about_technology.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Introducing R and the RStudio notebook</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./resampling_with_code.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Resampling with code</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./resampling_with_code2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">More resampling with code</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sampling_tools.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Tools for samples and sampling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability_theory_1a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Probability Theory, Part 1</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability_theory_1b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Probability Theory Part I (continued)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./more_sampling_tools.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Two puzzles and more tools</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability_theory_2_compound.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Probability Theory, Part 2: Compound Probability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability_theory_3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Probability Theory, Part 3</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability_theory_4_finite.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Probability Theory, Part 4: Estimating Probabilities from Finite Universes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sampling_variability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">On Variability in Sampling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./monte_carlo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">The Procedures of Monte Carlo Simulation (and Resampling)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./standard_scores.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Ranks, Quantiles and Standard Scores</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference_ideas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">The Basic Ideas in Statistical Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Introduction to Statistical Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./point_estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Point Estimation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./framing_questions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Framing Statistical Questions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./testing_counts_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Hypothesis-Testing with Counted Data, Part 1</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./significance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">The Concept of Statistical Significance in Testing Hypotheses</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./testing_counts_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">The Statistics of Hypothesis-Testing with Counted Data, Part 2</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./testing_measured.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">The Statistics of Hypothesis-Testing With Measured Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./testing_procedures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">General Procedures for Testing Hypotheses</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./confidence_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Confidence Intervals, Part 1: Assessing the Accuracy of Samples</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./confidence_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Confidence Intervals, Part 2: The Two Approaches to Estimating Confidence Intervals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./reliability_average.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Some Last Words About the Reliability of Sample Averages</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./correlation_causation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Correlation and Causation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./how_big_sample.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">How Large a Sample?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bayes_simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Bayesian Analysis by Simulation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./exercise_solutions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Exercise Solutions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./acknowlegements.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Acknowledgements</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./technical_note.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Technical Note to the Professional Reader</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">10.1</span> Introduction</a></li>
  <li><a href="#the-treasure-fleet-recovered" id="toc-the-treasure-fleet-recovered" class="nav-link" data-scroll-target="#the-treasure-fleet-recovered"><span class="header-section-number">10.2</span> The treasure fleet recovered</a></li>
  <li><a href="#back-to-boolean-s" id="toc-back-to-boolean-s" class="nav-link" data-scroll-target="#back-to-boolean-s"><span class="header-section-number">10.3</span> Back to Boolean vectors</a></li>
  <li><a href="#sec-ships-booleans" id="toc-sec-ships-booleans" class="nav-link" data-scroll-target="#sec-ships-booleans"><span class="header-section-number">10.4</span> Boolean vectors and another take on the ships problem</a></li>
  <li><a href="#the-monty-hall-problem" id="toc-the-monty-hall-problem" class="nav-link" data-scroll-target="#the-monty-hall-problem"><span class="header-section-number">10.6</span> The Monty Hall problem</a></li>
  <li><a href="#monty-hall-with" id="toc-monty-hall-with" class="nav-link" data-scroll-target="#monty-hall-with"><span class="header-section-number">10.7</span> Monty Hall with R</a></li>
  <li><a href="#why-use-simulation" id="toc-why-use-simulation" class="nav-link" data-scroll-target="#why-use-simulation"><span class="header-section-number">10.8</span> Why use simulation?</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-more-sampling-tools" class="quarto-section-identifier"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Two puzzles and more tools</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="introduction" class="level2" data-number="10.1">
<h2 data-number="10.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">10.1</span> Introduction</h2>
<p>In the next chapter we will deal with some more involved problems in <em>probability</em>, as a preparation for <em>statistics</em>, where we use reasoning from probability to draw conclusions about a world like our own, where variation often appears to be more or less random.</p>
<p>Before we get down to the business of complex probabilistic problems in the next few chapters, let’s consider a couple of peculiar puzzles. These puzzles allow us to introduce some more of the key tools in R for Monte Carlo resampling, and show the power of such simulation to help solve, and then reason about, problems in probability.</p>
</section>
<section id="the-treasure-fleet-recovered" class="level2" data-number="10.2">
<h2 data-number="10.2" class="anchored" data-anchor-id="the-treasure-fleet-recovered"><span class="header-section-number">10.2</span> The treasure fleet recovered</h2>
<p>This is a classic problem in probability:<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<blockquote class="blockquote">
<p>A Spanish treasure fleet of three ships was sunk at sea off Mexico. One ship had a chest of gold forward and another aft, another ship had a chest of gold forward and a chest of silver aft, while a third ship had a chest of silver forward and another chest of silver aft. Divers just found one of the ships and a chest of gold in it, but they don’t know whether it was from forward or aft. They are now taking bets about whether the other chest found on the same ship will contain silver or gold. What are fair odds?</p>
</blockquote>
<p>These are the logical steps one may distinguish in arriving at a correct answer with deductive logic (portrayed in <a href="#fig-ships-gold-silver" class="quarto-xref">Figure&nbsp;<span>10.1</span></a>).</p>
<ol type="1">
<li><p>Postulate three ships — Ship I with two gold chests (G-G), ship II with one gold and one silver chest (G-S), and ship III with S-S. (Choosing notation might well be considered one or more additional steps.)</p></li>
<li><p>Assert equal probabilities of each ship being found.</p></li>
<li><p>Step 2 implies equal probabilities of being found for each of the six chests.</p></li>
<li><p>Fact: Diver finds a chest of gold.</p></li>
<li><p>Step 4 implies that S-S ship III was not found; hence remove it from subsequent analysis.</p></li>
<li><p>Three possibilities: 6a) Diver found chest I-Ga, 6b) diver found I-Gb, 6c) diver found II-Gc.</p>
<p>From step 2, the cases a, b, and c in step 6 have equal probabilities.</p></li>
<li><p>If possibility 6a is the case, then the other chest is I-Gb; the comparable statements for cases 6b and 6c are I-Ga and II-S.</p></li>
<li><p>From steps 6 and 7: From equal probabilities of the three cases, and no other possible outcome, <span class="math inline">\(P(6a) = 1/3\)</span>, <span class="math inline">\(P(6b) = 1/3\)</span>, <span class="math inline">\(P(6c) = 1/3\)</span>.</p></li>
<li><p>So <span class="math inline">\(P(G) = P(6a) + P(6b)\)</span> = 1/3 + 1/3 = 2/3.</p></li>
</ol>
<p>See <a href="#fig-ships-gold-silver" class="quarto-xref">Figure&nbsp;<span>10.1</span></a>.</p>
<div class="cell" data-layout-align="center" data-opts.label="svg_fig" data-hash="more_sampling_tools_cache/html/fig-ships-gold-silver_d1be610f16f2ac1ab3a6e9ef0cb6d92c">
<div class="cell-output-display">
<div id="fig-ships-gold-silver" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="diagrams/ships_gold_silver.svg" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;10.1: Ships with Gold and Silver</figcaption>
</figure>
</div>
</div>
</div>
<p>The following simulation arrives at the correct answer.</p>
<ol type="1">
<li>Write “Gold” on three pieces of paper and “Silver” on three pieces of paper. These represent the chests.</li>
<li>Get three buckets each with two pieces of paper. Each bucket represents a ship, each piece of paper represents a chest in that ship. One bucket has two pieces of paper with “Gold” written on them; one has pieces of paper with “Gold” and “Silver”, and one has “Silver” and “Silver”.</li>
<li>Choose a bucket at random, to represent choosing a ship at random.</li>
<li>Shuffle the pieces of paper in the bucket and pick one, to represent choosing the first chest from that ship at random.</li>
<li>If the piece of paper says “Silver”, the first chest we found in this ship was silver, and we stop the trial and make no further record. If “Gold”, continue.</li>
<li>Get the second piece of paper from the bucket, representing the second chest on the chosen ship. Record whether this was “Silver” or “Gold” on the scoreboard.</li>
<li>Repeat steps (3 - 6) many times, and calculate the proportion of “Gold”s on the scoreboard. (The answer should be about <span class="math inline">\(\frac{2}{3}\)</span>.)</li>
</ol>
<!---
Consider introducing elif here.
-->
<p>Here is a notebook simulation with R:</p>
<div class="notebook" name="gold_silver_ships" title="Ships with gold and silver">
<p>Start of <code>gold_silver_ships</code> notebook</p>
<div class="nb-links">
<a class="notebook-link" href="notebooks/gold_silver_ships.Rmd">Download notebook</a>
<a class="interact-button" href="https://mybinder.org/v2/gh/resampling-stats/r-book/main?filepath=/notebooks/gold_silver_ships.Rmd">Interact</a>
</div>

<div class="cell" data-layout-align="center" data-hash="more_sampling_tools_cache/html/unnamed-chunk-4_27d79934f7ece38a0e275af64f88fa29">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The 3 buckets.  Each bucket represents a ship.  Each has two chests.</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>bucket1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'Gold'</span>, <span class="st">'Gold'</span>)  <span class="co"># Chests in first ship.</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a>bucket2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'Gold'</span>,  <span class="st">'Silver'</span>)  <span class="co"># Chests in second ship.</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>bucket3 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'Silver'</span>, <span class="st">'Silver'</span>)  <span class="co"># Chests in third ship.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center" data-hash="more_sampling_tools_cache/html/unnamed-chunk-5_d1cd2cb4105269353300346dc9e54445">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Mark trials as not valid to start with.</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Trials where we don't get a gold chest first will</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># keep this 'No gold in chest 1, chest 2 never opened' marker.</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>second_chests <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="st">'No gold in chest 1, chest 2 never opened'</span>, <span class="dv">10000</span>)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10000</span>) {</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Select a ship at random from the three ships.</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    ship_no <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="at">size=</span><span class="dv">1</span>)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Get the chests from this ship (represented by a bucket).</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (ship_no <span class="sc">==</span> <span class="dv">1</span>) {</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>        bucket <span class="ot">&lt;-</span> bucket1</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (ship_no <span class="sc">==</span> <span class="dv">2</span>) {</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>        bucket <span class="ot">&lt;-</span> bucket2</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (ship_no <span class="sc">==</span> <span class="dv">3</span>) {</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>        bucket <span class="ot">&lt;-</span> bucket3</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>    <span class="co"># We shuffle the order of the chests in this ship, to simulate</span></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>    <span class="co"># the fact that we don't know which of the two chests we have</span></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>    <span class="co"># found first.</span></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>    shuffled <span class="ot">&lt;-</span> <span class="fu">sample</span>(bucket)</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (shuffled[<span class="dv">1</span>] <span class="sc">==</span> <span class="st">'Gold'</span>) {  <span class="co"># We found a gold chest first.</span></span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Store whether the Second chest was silver or gold.</span></span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>        second_chests[i] <span class="ot">&lt;-</span> shuffled[<span class="dv">2</span>]</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>}  <span class="co"># End loop, go back to beginning.</span></span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Number of times we found gold in the second chest.</span></span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>n_golds <span class="ot">&lt;-</span> <span class="fu">sum</span>(second_chests <span class="sc">==</span> <span class="st">'Gold'</span>)</span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a><span class="co"># Number of times we found silver in the second chest.</span></span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a>n_silvers <span class="ot">&lt;-</span> <span class="fu">sum</span>(second_chests <span class="sc">==</span> <span class="st">'Silver'</span>)</span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a><span class="co"># As a ratio of golds to all second chests (where the first was gold).</span></span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a><span class="fu">message</span>(n_golds <span class="sc">/</span> (n_golds <span class="sc">+</span> n_silvers))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>0.655882352941176</code></pre>
</div>
</div>
<p>End of <code>gold_silver_ships</code> notebook</p>
</div>
<p>In the code above, we have first chosen the ship number at random, and then used a set of <code>if ...</code> statements to get the pair of chests corresponding to the given ship. There are simpler and more elegant ways of writing this code, but they would need some R features that we haven’t covered yet.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
</section>
<section id="back-to-boolean-s" class="level2" data-number="10.3">
<h2 data-number="10.3" class="anchored" data-anchor-id="back-to-boolean-s"><span class="header-section-number">10.3</span> Back to Boolean vectors</h2>
<p>The code above implements the procedure we might well use if we were simulating the problem physically. We do a trial, and we record the result. We do this on a piece of paper if we are doing a physical simulation, and in the <code>second_chests</code> vector in code.</p>
<p>Finally we tally up the results. If we are doing a physical simulation, we go back over the all the trial results and counting up the “Gold” and “Silver” outcomes. In code we use the comparisons <code>== 'Gold'</code> and <code>== 'Silver'</code> to find the trials of interest, and then count them up with <code>sum</code>.</p>
<p>Boolean vectors are a fundamental tool in R, and we will use them in nearly all our simulations.</p>
<p>Here is a remind of how those vectors work.</p>
<p>First, let’s slice out the first 10 values of the <code>second_chests</code> trial-by-trial results tally from the simulation above:</p>
<div class="cell" data-layout-align="center" data-hash="more_sampling_tools_cache/html/unnamed-chunk-7_98aa017e66859a2193a9aadf3c0ab8fc">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Get values at positions 1 through 10</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>first_10_chests <span class="ot">&lt;-</span> second_chests[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>]</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>first_10_chests</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Gold"                                    
 [2] "No gold in chest 1, chest 2 never opened"
 [3] "No gold in chest 1, chest 2 never opened"
 [4] "Silver"                                  
 [5] "Gold"                                    
 [6] "No gold in chest 1, chest 2 never opened"
 [7] "Silver"                                  
 [8] "Silver"                                  
 [9] "Gold"                                    
[10] "No gold in chest 1, chest 2 never opened"</code></pre>
</div>
</div>
<p>Before we started the simulation, we set <code>second_chests</code> to contain 10,000 strings, where each string was “No gold in chest 1, chest 2 never opened”. In the simulation, we check whether there was gold in the first chest, and, if not, we don’t change the value in <code>second_chest</code>, and the value remains as “No gold in chest 1, chest 2 never opened”.</p>
<p>Only if there was gold in the first chest, do we go on to check whether the second chest contains silver or gold. Therefore, we only set a new value in <code>second_chests</code> where there was gold in the first chest.</p>
<p>Now let’s show the effect of running a comparison on <code>first_10_chests</code>:</p>
<div class="cell" data-layout-align="center" data-hash="more_sampling_tools_cache/html/unnamed-chunk-9_90995a616818ed36ed7c18db85d24542">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>were_gold <span class="ot">&lt;-</span> (first_10_chests <span class="sc">==</span> <span class="st">'Gold'</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>were_gold</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  TRUE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE  TRUE FALSE</code></pre>
</div>
</div>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Parentheses and Boolean comparisons
</div>
</div>
<div class="callout-body-container callout-body">
<p>Notice the round brackets (parentheses) around <code>(first_10_chests == 'Gold')</code>. In this particular case, we would get the same result without the parentheses, so the paretheses are optional. In general, you will see we put parentheses around all expressions that generate Boolean vectors, and we recommend you do too. It is good habit to get into, to make it clear that this is an expression that generates a value.</p>
</div>
</div>
<p>The <code>== 'Gold'</code> <em>comparison</em> is asking a question. It is asking that question of a vector, and the vector contains multiple values. R treats this comparison as asking the question <em>of each element in the vector</em>. We get an answer for the question <em>for each element</em>. The answer for position <span class="r">1</span> is <code>TRUE</code> if the element at position <span class="r">1</span> is equal to <code>'Gold'</code> and <code>FALSE</code> otherwise, and so on, for positions <span class="r">2</span>, <span class="r">3</span> and so on. We started with 10 strings. After the comparison <code>== 'Gold'</code> we have 10 Boolean values, where a Boolean value can either be <code>TRUE</code> or <code>FALSE</code>.</p>

<!---
We need an illustration here of form:

True        "Gold"
True        "Gold"
False       "No gold in chest 1, chest 2 never opened"
True        "Gold"
False   =   "Silver"                     == 'Gold'
...

Any takers?  Good techniques?   Maybe generated Markdown table with transparent boerder for second and fourth column?
-->
<p>Now we have an array with <code>TRUE</code> for the “Gold” results and <code>FALSE</code> otherwise, we can count the number of “Gold” results by using <code>sum</code> on the vector. As you remember (<a href="resampling_with_code.html#sec-count-with-sum" class="quarto-xref"><span>Section&nbsp;5.13</span></a>) <code>sum</code> counts <code>TRUE</code> as 1 and <code>FALSE</code> as 0, so the sum of the Boolean vector is just the number of <code>TRUE</code> values in the vector — the count that we need.</p>
<div class="cell" data-layout-align="center" data-hash="more_sampling_tools_cache/html/unnamed-chunk-11_fd24e53d0a2e3ee3ac0dcd48c6f70c5c">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The number of True values — so the number of "Gold" chests.</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sum</span>(were_gold)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
</div>
</section>
<section id="sec-ships-booleans" class="level2" data-number="10.4">
<h2 data-number="10.4" class="anchored" data-anchor-id="sec-ships-booleans"><span class="header-section-number">10.4</span> Boolean vectors and another take on the ships problem</h2>
<p>If we are doing a physical simulation, we usually want to finish up all the work for the trial during the trial, so we have one outcome from the trial. This makes it easier to tally up the results in the end.</p>
<p>We have no such constraint when we are using code, so it is sometimes easier to record several results from the trial, and do the final combinations and tallies at the end. We will show you what we mean with a slight variation on the two-ships code you saw above.</p>
<div class="notebook" name="gold_silver_booleans" title="Another approach to ships with gold and silver">
<p>Start of <code>gold_silver_booleans</code> notebook</p>
<div class="nb-links">
<a class="notebook-link" href="notebooks/gold_silver_booleans.Rmd">Download notebook</a>
<a class="interact-button" href="https://mybinder.org/v2/gh/resampling-stats/r-book/main?filepath=/notebooks/gold_silver_booleans.Rmd">Interact</a>
</div>

<p>Notice that the first part of the code is identical to the first approach to this problem. There are two key differences — see the comments for an explanation.</p>
<div class="cell" data-layout-align="center" data-hash="more_sampling_tools_cache/html/unnamed-chunk-15_2f3b05ac8c927703f5708c4be6753a00">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The 3 buckets, each representing two chests on a ship.</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="co"># As before.</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>bucket1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'Gold'</span>, <span class="st">'Gold'</span>)  <span class="co"># Chests in first ship.</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>bucket2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'Gold'</span>,  <span class="st">'Silver'</span>)  <span class="co"># Chests in second ship.</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>bucket3 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'Silver'</span>, <span class="st">'Silver'</span>)  <span class="co"># Chests in third ship.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell" data-layout-align="center" data-hash="more_sampling_tools_cache/html/unnamed-chunk-16_14474031c822393339155a9bd83708af">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Here is where the difference starts.  We are now going to fill in</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co"># the result for the first chest _and_ the result for the second chest.</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="co">#</span></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Later we will fill in all these values, so the string we put here</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a><span class="co"># does not matter.</span></span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Whether the first chest was Gold or Silver.</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>first_chests <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="st">'To be announced'</span>, <span class="dv">10000</span>)</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>second_chests <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="st">'To be announced'</span>, <span class="dv">10000</span>)</span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10000</span>) {</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Select a ship at random from the three ships.</span></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>    <span class="co"># As before.</span></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>    ship_no <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="at">size=</span><span class="dv">1</span>)</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Get the chests from this ship.</span></span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>    <span class="co"># As before.</span></span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (ship_no <span class="sc">==</span> <span class="dv">1</span>) {</span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>        bucket <span class="ot">&lt;-</span> bucket1</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (ship_no <span class="sc">==</span> <span class="dv">2</span>) {</span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a>        bucket <span class="ot">&lt;-</span> bucket2</span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (ship_no <span class="sc">==</span> <span class="dv">3</span>) {</span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a>        bucket <span class="ot">&lt;-</span> bucket3</span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb13-26"><a href="#cb13-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-27"><a href="#cb13-27" aria-hidden="true" tabindex="-1"></a>    <span class="co"># As before.</span></span>
<span id="cb13-28"><a href="#cb13-28" aria-hidden="true" tabindex="-1"></a>    shuffled <span class="ot">&lt;-</span> <span class="fu">sample</span>(bucket)</span>
<span id="cb13-29"><a href="#cb13-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-30"><a href="#cb13-30" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Here is the big difference - we store the result for the first and second</span></span>
<span id="cb13-31"><a href="#cb13-31" aria-hidden="true" tabindex="-1"></a>    <span class="co"># chests.</span></span>
<span id="cb13-32"><a href="#cb13-32" aria-hidden="true" tabindex="-1"></a>    first_chests[i] <span class="ot">&lt;-</span> shuffled[<span class="dv">1</span>]</span>
<span id="cb13-33"><a href="#cb13-33" aria-hidden="true" tabindex="-1"></a>    second_chests[i] <span class="ot">&lt;-</span> shuffled[<span class="dv">2</span>]</span>
<span id="cb13-34"><a href="#cb13-34" aria-hidden="true" tabindex="-1"></a>}  <span class="co"># End loop, go back to beginning.</span></span>
<span id="cb13-35"><a href="#cb13-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-36"><a href="#cb13-36" aria-hidden="true" tabindex="-1"></a><span class="co"># We will do the calculation we need in the next cell.  For now</span></span>
<span id="cb13-37"><a href="#cb13-37" aria-hidden="true" tabindex="-1"></a><span class="co"># just display the first 10 values.</span></span>
<span id="cb13-38"><a href="#cb13-38" aria-hidden="true" tabindex="-1"></a>ten_first_chests <span class="ot">&lt;-</span> first_chests[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>]</span>
<span id="cb13-39"><a href="#cb13-39" aria-hidden="true" tabindex="-1"></a><span class="fu">message</span>(<span class="st">'The first 10 values of "first_chests:'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>The first 10 values of "first_chests:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(ten_first_chests)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Gold"   "Silver" "Silver" "Silver" "Gold"   "Gold"   "Gold"   "Gold"  
 [9] "Gold"   "Gold"  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>ten_second_chests <span class="ot">&lt;-</span> second_chests[<span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>]</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="fu">message</span>(<span class="st">'The first 10 values of "second_chests:'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>The first 10 values of "second_chests:</code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(ten_second_chests)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Gold"   "Gold"   "Silver" "Silver" "Gold"   "Silver" "Gold"   "Silver"
 [9] "Gold"   "Silver"</code></pre>
</div>
</div>
<p>In this variant, we recorded the type of first chest for each trial (“Gold” or “Silver”), and the type of second chest of the second chest (“Gold” or “Silver”).</p>
<p><strong>We would like to count the number of times there was “Gold” in the first chest <em>and</em> “Gold” in the second.</strong></p>
<section id="sec-combine-booleans" class="level2" data-number="10.5">
<h2 data-number="10.5" class="anchored" data-anchor-id="sec-combine-booleans"><span class="header-section-number">10.5</span> Combining Boolean arrays</h2>
<p>We can do the count we need by <em>combining</em> the Boolean vectors with the <code>&amp;</code> operator. <code>&amp;</code> combines Boolean vectors with a <em>logical and</em>. <em>Logical and</em> is a rule for combining two Boolean values, where the rule is: the result is <code>TRUE</code> if the first value is <code>TRUE</code> <em>and</em> the second value if <code>TRUE</code>.</p>
<p>Here we use the <code>&amp;</code> <em>operator</em> to combine some Boolean values on the left and right of the operator:</p>
<p>Above you saw that the <code>==</code> operator (as in <code>== 'Gold'</code>), when applied to vectors, asks the question of every element in the vector.</p>
<p>First make the Boolean vectors.</p>
<div class="cell" data-layout-align="center" data-hash="more_sampling_tools_cache/html/unnamed-chunk-27_388bc0648cc7748ca29bee2b485e70fd">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>ten_first_gold <span class="ot">&lt;-</span> ten_first_chests <span class="sc">==</span> <span class="st">'Gold'</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">message</span>(<span class="st">"Ten first == 'Gold'"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Ten first == 'Gold'</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(ten_first_gold)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  TRUE FALSE FALSE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>ten_second_gold <span class="ot">&lt;-</span> ten_second_chests <span class="sc">==</span> <span class="st">'Gold'</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">message</span>(<span class="st">"Ten second == 'Gold'"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Ten second == 'Gold'</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(ten_second_gold)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  TRUE  TRUE FALSE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE</code></pre>
</div>
</div>
<p>Now let us use <code>&amp;</code> to combine Boolean vectors:</p>
<div class="cell" data-layout-align="center" data-hash="more_sampling_tools_cache/html/unnamed-chunk-29_8379c26a4eee35a89c1bc0a97cfde225">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>ten_both <span class="ot">&lt;-</span> (ten_first_gold <span class="sc">&amp;</span> ten_second_gold)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a>ten_both</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1]  TRUE FALSE FALSE FALSE  TRUE FALSE  TRUE FALSE  TRUE FALSE</code></pre>
</div>
</div>
<p>Notice that R does the comparison <em>elementwise</em> — element by element.</p>
<p>You saw that when we did <code>second_chests == 'Gold'</code> this had the effect of asking the <code>== 'Gold'</code> question of <em>each element</em>, so there will be one answer per element in <code>second_chests</code>. In that case there was a vector to the <em>left</em> of <code>==</code> and a single value to the <em>right</em>. We were comparing a vector to a value.</p>
<p>Here we are asking the <code>&amp;</code> question of <code>ten_first_gold</code> and <code>ten_second_gold</code>. Here there is a vector to the <em>left</em> and a vector to the <em>right</em>. We are asking the <code>&amp;</code> question 10 times, but the first question we are asking is:</p>
<div class="cell" data-layout-align="center" data-hash="more_sampling_tools_cache/html/unnamed-chunk-31_1cab8cf237ad68e9a19721abaf31978b">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># First question, giving first element of result.</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>(ten_first_gold[<span class="dv">1</span>] <span class="sc">&amp;</span> ten_second_gold[<span class="dv">1</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<p>The second question is:</p>
<div class="cell" data-layout-align="center" data-hash="more_sampling_tools_cache/html/unnamed-chunk-33_e9ca91fc3779d654c5c0744718b9950f">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Second question, giving second element of result.</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>(ten_first_gold[<span class="dv">2</span>] <span class="sc">&amp;</span> ten_second_gold[<span class="dv">2</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] FALSE</code></pre>
</div>
</div>
<p>and so on. We have ten elements on <em>each side</em>, and 10 answers, giving a vector (<code>ten_both</code>) of 10 elements. Each element in <code>ten_both</code> is the answer to the <code>&amp;</code> question for the elements at the corresponding positions in <code>ten_first_gold</code> and <code>ten_second_gold</code>.</p>
<p>We could also create the Boolean vectors and do the <code>&amp;</code> operation all in one step, like this:</p>
<!---
Another illustration here, of form (matching the text):

True          True          True
False         False         True
False         False         True
True          True          False
False    =    False    &    True
...
-->
<p>Remember, we wanted the answer to the question: how many trials had “Gold” in the first chest <em>and</em> “Gold” in the second. We can answer that question for the first 10 trials with <code>sum</code>:</p>
<div class="cell" data-layout-align="center" data-hash="more_sampling_tools_cache/html/unnamed-chunk-36_74fdea56e0a88de127f2c8ad3b35a89a">
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>n_ten_both <span class="ot">&lt;-</span> <span class="fu">sum</span>(ten_both)</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>n_ten_both</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4</code></pre>
</div>
</div>
<p>We can answer the same question for <em>all</em> the trials, in the same way:</p>
<div class="cell" data-layout-align="center" data-hash="more_sampling_tools_cache/html/unnamed-chunk-38_ccbabf44421cd564efee4f08a68c5d85">
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>first_gold <span class="ot">&lt;-</span> first_chests <span class="sc">==</span> <span class="st">'Gold'</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>second_gold <span class="ot">&lt;-</span> second_chests <span class="sc">==</span> <span class="st">'Gold'</span></span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>n_both_gold <span class="ot">&lt;-</span> <span class="fu">sum</span>(first_gold <span class="sc">&amp;</span> second_gold)</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>n_both_gold</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3328</code></pre>
</div>
</div>
<p>We could also do the same calculation all in one line:</p>
<div class="cell" data-layout-align="center" data-hash="more_sampling_tools_cache/html/unnamed-chunk-40_1e096126c8f24041009a124341656c98">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>n_both_gold <span class="ot">&lt;-</span> <span class="fu">sum</span>((first_chests <span class="sc">==</span> <span class="st">'Gold'</span>) <span class="sc">&amp;</span> (second_chests <span class="sc">==</span> <span class="st">'Gold'</span>))</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>n_both_gold</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3328</code></pre>
</div>
</div>
<p>We can then count all the ships where the first chest was gold:</p>
<div class="cell" data-layout-align="center" data-hash="more_sampling_tools_cache/html/unnamed-chunk-42_8899cfea4da52f9cba65541ddc5e0225">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>n_first_gold <span class="ot">&lt;-</span> <span class="fu">sum</span>(first_chests <span class="sc">==</span> <span class="st">'Gold'</span>)</span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>n_first_gold</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5021</code></pre>
</div>
</div>
<p>The final calculation is the proportion of second chests that are gold, given the first chest was also gold:</p>
<div class="cell" data-layout-align="center" data-hash="more_sampling_tools_cache/html/unnamed-chunk-44_d93cdffc78a7eb223861c4b5ae66a497">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>p_g_given_g <span class="ot">&lt;-</span> n_both_gold <span class="sc">/</span> n_first_gold</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>p_g_given_g</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.663</code></pre>
</div>
</div>
<p>Of course we won’t get exactly the same results from the two simulations, in the same way that we won’t get exactly the same results from any two runs of the same simulation, because of the random values we are using. But the logic for the two simulations are the same, and we are doing many trials (10,000), so the results will be very similar.</p>
<p>End of <code>gold_silver_booleans</code> notebook</p>
</section>
</div>
</section>
<section id="the-monty-hall-problem" class="level2" data-number="10.6">
<h2 data-number="10.6" class="anchored" data-anchor-id="the-monty-hall-problem"><span class="header-section-number">10.6</span> The Monty Hall problem</h2>
<p>The Monty Hall Problem is a puzzle in probability that is famous for its deceptive simplicity. It has its own long Wikipedia page: <a href="https://en.wikipedia.org/wiki/Monty_Hall_problem" class="uri">https://en.wikipedia.org/wiki/Monty_Hall_problem</a>.</p>
<p>Here is the problem in the form it is best known; a letter to the columnist <a href="https://en.wikipedia.org/wiki/Marilyn_vos_Savant">Marilyn vos Savant</a>, published in Parade Magazine <span class="citation" data-cites="savant1990monty">(<a href="references.html#ref-savant1990monty" role="doc-biblioref">1990</a>)</span>:</p>
<blockquote class="blockquote">
<p>Suppose you’re on a game show, and you’re given the choice of three doors. Behind one door is a car, behind the others, goats. You pick a door, say #1, and the host, who knows what’s behind the doors, opens another door, say #3, which has a goat. He says to you, “Do you want to pick door #2?” Is it to your advantage to switch your choice of doors?</p>
</blockquote>
<p>In fact the first person to propose (and solve) this problem was Steve Selvin, a professor of public health at the University of California, Berkeley <span class="citation" data-cites="slevin1975monty">(<a href="references.html#ref-slevin1975monty" role="doc-biblioref">Selvin 1975</a>)</span>.</p>
<p>Most people, including at least one of us, your humble authors, quickly come to the wrong conclusion. The most common but incorrect answer is that it will make no difference if you switch doors or stay with your original choice. The obvious intuition is that, after Monty opens his door, there are two doors that might have the car behind them, and therefore, there is a 50% chance it will be behind any one of the two. It turns out that answer is wrong; you will double your chances of winning by switching doors. Did you get the answer right?</p>
<p>If you got the answer wrong, you are in excellent company. As you can see from the commentary in <span class="citation" data-cites="savant1990monty">Savant (<a href="references.html#ref-savant1990monty" role="doc-biblioref">1990</a>)</span>, many mathematicians wrote to Parade magazine to assert that the (correct) solution was wrong. <a href="https://en.wikipedia.org/wiki/Paul_Erdős">Paul Erdős</a> was one of the most famous mathematicians of the 20th century; he could not be convinced of the correct solution until he had seen a computer simulation <span class="citation" data-cites="vazsonyi1999door">(<a href="references.html#ref-vazsonyi1999door" role="doc-biblioref">Vazsonyi 1999</a>)</span>, of the type we will do below.</p>
<p>To simulate a trial of this problem, we need to select a door at random to house the car, and another door at random, to be the door the contestant chooses. We number the doors 1, 2 and 3. Now we need two random choices from the options 1, 2 or 3, one for the door with the car, the other for the contestant door. To chose a door for the car, we could throw a die, and chose door 1 if the die shows 1 or 4, door 2 if the die shows 2 or 5, and door 3 for 3 or 6. Then we throw the die again to chose the contestant door.</p>
<p>But throwing dice is a little boring; we have to find the die, then throw it many times, and record the results. Instead we can ask the computer to chose the doors at random.</p>
<p>For this simulation, let us do 25 trials. We ask the computer to create two sets of 25 random numbers from 1 through 3. The first set is the door with the car behind it (“Car door”). The second set have the door that the contestant chose at random (“Our door”). We put these in a table, and make some new, empty columns to fill in later. The first new column is “Monty opens”. In due course, we will use this column to record the door that Monty Hall will open on this trial. The last two columns express the outcome. The first is “Stay wins”. This has “Yes” if we win on this trial by sticking to our original choice of door, and “No” otherwise. The last column is “Switch wins”. This has “Yes” if we win by switching doors, and “No” otherwise. See table <a href="#tbl-montyblank" class="quarto-xref">Table&nbsp;<span>10.1</span></a>).</p>
<div class="cell" data-layout-align="center" data-hash="more_sampling_tools_cache/html/montyblank_074759883797d2eb83d35fcdbb18a74b">
<div class="cell-output-display">
<div id="tbl-montyblank" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;10.1: 25 simulations of the Monty Hall problem </caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Car door</th>
<th style="text-align: right;">Our door</th>
<th style="text-align: left;">Monty opens</th>
<th style="text-align: left;">Stay wins</th>
<th style="text-align: left;">Switch wins</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">7</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">8</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">9</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">10</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">11</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">12</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">13</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">14</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">15</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">16</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">17</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">18</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">19</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">20</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">21</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">22</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">23</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">24</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">25</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>In the first trial in <a href="#tbl-montyblank" class="quarto-xref">Table&nbsp;<span>10.1</span></a>), the computer selected door 3 for car, and door 3 for the contestant. Now Monty must open a door, and he cannot open our door (door 3) so he has the choice of opening door 1 or door 2; he chooses randomly, and opens door 2. On this trial, we win if we stay with our original choice, and we lose if we change to the remaining door, door 1.</p>
<p>Now we go the second trial. The computer chose door 3 for the car, and door 1 for our choice. Monty cannot choose our door (door 1) or the door with the car behind it (door 3), so he must open door 2. Now if we stay with our original choice, we lose, but if we switch, we win.</p>
<p>You may want to print out table <a href="#tbl-montyblank" class="quarto-xref">Table&nbsp;<span>10.1</span></a>, and fill out the blank columns, to work through the logic.</p>
<p>After doing a few more trials, and some reflection, you may see that there are two different situations here: the situation when our <em>initial guess was right</em>, and the situation where our <em>initial guess was wrong</em>. When our initial guess was right, we win by staying with our original choice, but when it was wrong, we always win by switching. The chance of our <em>initial guess</em> being correct is 1/3 (one door out of three). So the chances of winning by staying are 1/3, and the chances of winning by switching are 2/3. But remember, you don’t need to follow this logic to get the right answer. As you will see below, the resampling simulation shows us that the Switch strategy wins.</p>
<p>Table <a href="#tbl-montyfull" class="quarto-xref">Table&nbsp;<span>10.2</span></a> is a version of table <a href="#tbl-montyblank" class="quarto-xref">Table&nbsp;<span>10.1</span></a> for which we have filled in the blank columns using the logic above.</p>
<div class="cell" data-layout-align="center" data-hash="more_sampling_tools_cache/html/montyfull_3cd895b1fa966ad0c1038b95f00b36e4">
<div class="cell-output-display">
<div id="tbl-montyfull" class="anchored">
<table class="table table-sm table-striped small">
<caption>Table&nbsp;10.2: 25 simulations of the Monty Hall problem, filled out </caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Car door</th>
<th style="text-align: right;">Our door</th>
<th style="text-align: right;">Monty opens</th>
<th style="text-align: left;">Stay wins</th>
<th style="text-align: left;">Switch wins</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Yes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Yes</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Yes</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Yes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">8</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Yes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">9</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Yes</td>
</tr>
<tr class="even">
<td style="text-align: left;">10</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Yes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">11</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">12</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Yes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">13</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">14</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Yes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">15</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Yes</td>
</tr>
<tr class="even">
<td style="text-align: left;">16</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Yes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">17</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">18</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Yes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">19</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">20</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Yes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">21</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">22</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Yes</td>
</tr>
<tr class="odd">
<td style="text-align: left;">23</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Yes</td>
</tr>
<tr class="even">
<td style="text-align: left;">24</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: left;">Yes</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="odd">
<td style="text-align: left;">25</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">No</td>
<td style="text-align: left;">Yes</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
<p>The proportion of times “Stay” wins in these 25 trials is 0.36. The proportion of times “Switch” wins is 0.64; the Switch strategy wins about twice as often as the Stay strategy.</p>
</section>
<section id="monty-hall-with" class="level2" data-number="10.7">
<h2 data-number="10.7" class="anchored" data-anchor-id="monty-hall-with"><span class="header-section-number">10.7</span> Monty Hall with R</h2>
<p>Now you have seen what the results might look like for a physical simulation, you can exercise some of your newly-strengthened R muscles to do the simulation with code.</p>
<div class="notebook" name="monty_hall" title="The Monty Hall problem">
<p>Start of <code>monty_hall</code> notebook</p>
<div class="nb-links">
<a class="notebook-link" href="notebooks/monty_hall.Rmd">Download notebook</a>
<a class="interact-button" href="https://mybinder.org/v2/gh/resampling-stats/r-book/main?filepath=/notebooks/monty_hall.Rmd">Interact</a>
</div>

<p>The Monty Hall problem has a slightly complicated structure, so we will start by looking at the procedure for one trial. When we have that clear, we will put that procedure into a <code>for</code> loop for the simulation.</p>
<p>Let’s start with some variables. Let’s call the door I choose <code>my_door</code>.</p>
<p>We choose that door at random from a sequence of all possible doors. Call the doors 1, 2 and 3 from left to right.</p>
<div class="cell" data-layout-align="center" data-hash="more_sampling_tools_cache/html/unnamed-chunk-50_5db6157ffadaf738ab1734aa162c8e8d">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Vector of doors to chose from.</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>doors <span class="ot">=</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>)</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a><span class="co"># We choose one door at random.</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>my_door <span class="ot">&lt;-</span> <span class="fu">sample</span>(doors, <span class="at">size=</span><span class="dv">1</span>)</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Show the result</span></span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>my_door</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
</div>
<p>We choose one of the doors to be the door with the car behind it:</p>
<div class="cell" data-layout-align="center" data-hash="more_sampling_tools_cache/html/unnamed-chunk-52_8ef68c1d06b8ac98e41e93ce2c8b3485">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># One door at random has the car behind it.</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>car_door <span class="ot">&lt;-</span> <span class="fu">sample</span>(doors, <span class="at">size=</span><span class="dv">1</span>)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Show the result</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>car_door</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<p>Now we need to decide which door Monty will open.</p>
<p>By our set up, Monty cannot open our door (<code>my_door</code>). By the set up, he has not opened (and cannot open) the door with the car behind it (<code>car_door</code>).</p>
<p><code>my_door</code> and <code>car_door</code> might be the same.</p>
<p>So, to get Monty’s choices, we want to take all doors (<code>doors</code>) and remove <code>my_door</code> and <code>car_door</code>. That leaves the door or doors Monty can open.</p>
<p>Here are the doors Monty cannot open. Remember, a third of the time <code>my_door</code> and <code>car_door</code> will be the same, so we will include the same door twice, as doors Monty can’t open.</p>
<div class="cell" data-layout-align="center" data-hash="more_sampling_tools_cache/html/unnamed-chunk-54_d7be657761bc6ffe4d7a1c63328298d6">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>cant_open <span class="ot">=</span> <span class="fu">c</span>(my_door, car_door)</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>cant_open</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3 1</code></pre>
</div>
</div>
<p>We want to find the remaining doors from <code>doors</code> after removing the doors named in <code>cant_open</code>.</p>
<p>R has a good function for this, called <span class="r"><code>setdiff</code></span>. It calculates the <em>set difference</em> between two sequences, such as vectors.</p>
<p>The set difference between two sequences is the members that <em>are</em> in the first sequence, but are <em>not</em> in the second sequence. Here are a few examples of this set difference function in R.</p>
<div class="cell" data-layout-align="center" data-hash="more_sampling_tools_cache/html/unnamed-chunk-58_003035b1aa109c4c9b84b84a830d29e9">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Members in c(1, 2, 3) that are *not* in c(1)</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 1, 2, 3, removing 1, if present.</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="fu">setdiff</span>(<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>), <span class="fu">c</span>(<span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2 3</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center" data-hash="more_sampling_tools_cache/html/unnamed-chunk-59_45363afb76bc040f8518316ed1392e86">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Members in c(1, 2, 3) that are *not* in c(2, 3)</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 1, 2, 3, removing 2 and 3, if present.</span></span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a><span class="fu">setdiff</span>(<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>), <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">3</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center" data-hash="more_sampling_tools_cache/html/unnamed-chunk-60_4b24b876114623007d122f5bdaee1fda">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Members in c(1, 2, 3) that are *not* in c(2, 2)</span></span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 1, 2, 3, removing 2 and 2 again, if present.</span></span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a><span class="fu">setdiff</span>(<span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>), <span class="fu">c</span>(<span class="dv">2</span>, <span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1 3</code></pre>
</div>
</div>
<p>This logic allows us to choose the doors Monty can open:</p>
<div class="cell" data-layout-align="center" data-hash="more_sampling_tools_cache/html/unnamed-chunk-62_b6c3102da802a812b02e7d66e0620a08">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>montys_choices <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(doors, <span class="fu">c</span>(my_door, car_door))</span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>montys_choices</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
</div>
<p>Notice that <code>montys_choices</code> will only have one element left when <code>my_door</code> and <code>car_door</code> were different, but it will have two elements if <code>my_door</code> and <code>car_door</code> were the same.</p>
<p>Let’s play out those two cases:</p>
<div class="cell" data-layout-align="center" data-hash="more_sampling_tools_cache/html/unnamed-chunk-65_721197725bb3693c6238323268ebceac">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a>my_door <span class="ot">&lt;-</span> <span class="dv">1</span>  <span class="co"># For example.</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>car_door <span class="ot">&lt;-</span> <span class="dv">2</span>  <span class="co"># For example.</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Monty can only choose door 3 now.</span></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>montys_choices <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(doors, <span class="fu">c</span>(my_door, car_door))</span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>montys_choices</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center" data-hash="more_sampling_tools_cache/html/unnamed-chunk-66_d9a385953da72b51d18b4ebe8a3c61d6">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a>my_door <span class="ot">&lt;-</span> <span class="dv">1</span>  <span class="co"># For example.</span></span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a>car_door <span class="ot">&lt;-</span> <span class="dv">1</span>  <span class="co"># For example.</span></span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Monty can choose either door 2 or door 3.</span></span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a>montys_choices <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(doors, <span class="fu">c</span>(my_door, car_door))</span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a>montys_choices</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2 3</code></pre>
</div>
</div>
<p>If Monty can only choose one door, we’ll take that. Otherwise we’ll chose a door at random from the two doors available.</p>
<div class="cell" data-layout-align="center" data-hash="more_sampling_tools_cache/html/unnamed-chunk-68_df5ef6cf3de1d8a98ad3e3a879c63985">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">length</span>(montys_choices) <span class="sc">==</span> <span class="dv">1</span>) {  <span class="co"># Only one door available.</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>    montys_door <span class="ot">&lt;-</span> montys_choices[<span class="dv">1</span>]  <span class="co"># Take the first (of 1!).</span></span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {  <span class="co"># Two doors to choose from:</span></span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Choose at random.</span></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>    montys_door <span class="ot">&lt;-</span> <span class="fu">sample</span>(montys_choices, <span class="at">size=</span><span class="dv">1</span>)</span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a>montys_door</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
</div>
<p>Now we know Monty’s door, we can identify the other door, by removing our door, and Monty’s door, from the available options:</p>
<div class="cell" data-layout-align="center" data-hash="more_sampling_tools_cache/html/unnamed-chunk-72_c61514276bf95cb0473916f1c38bcda5">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>remaining_doors <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(doors, <span class="fu">c</span>(my_door, montys_door))</span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a><span class="co"># There is only one remaining door, take that.</span></span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>other_door <span class="ot">&lt;-</span> remaining_doors[<span class="dv">1</span>]</span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a>other_door</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3</code></pre>
</div>
</div>
<p>The logic above gives us the full procedure for one trial.</p>
<div class="cell" data-layout-align="center" data-hash="more_sampling_tools_cache/html/unnamed-chunk-74_c25eee06e782851fd95db87673984e1a">
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a>my_door <span class="ot">&lt;-</span> <span class="fu">sample</span>(doors, <span class="at">size=</span><span class="dv">1</span>)</span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>car_door <span class="ot">&lt;-</span> <span class="fu">sample</span>(doors, <span class="at">size=</span><span class="dv">1</span>)</span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Which door will Monty open?</span></span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a>montys_choices <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(doors, <span class="fu">c</span>(my_door, car_door))</span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Choose single door left to choose, or door at random if two.</span></span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (<span class="fu">length</span>(montys_choices) <span class="sc">==</span> <span class="dv">1</span>) {  <span class="co"># Only one door available.</span></span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a>    montys_door <span class="ot">&lt;-</span> montys_choices[<span class="dv">1</span>]  <span class="co"># Take the first (of 1!).</span></span>
<span id="cb67-8"><a href="#cb67-8" aria-hidden="true" tabindex="-1"></a>} <span class="cf">else</span> {  <span class="co"># Two doors to choose from:</span></span>
<span id="cb67-9"><a href="#cb67-9" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Choose at random.</span></span>
<span id="cb67-10"><a href="#cb67-10" aria-hidden="true" tabindex="-1"></a>    montys_door <span class="ot">&lt;-</span> <span class="fu">sample</span>(montys_choices, <span class="at">size=</span><span class="dv">1</span>)</span>
<span id="cb67-11"><a href="#cb67-11" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb67-12"><a href="#cb67-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Now find the door we'll open if we switch.</span></span>
<span id="cb67-13"><a href="#cb67-13" aria-hidden="true" tabindex="-1"></a><span class="co"># There is only one door left.</span></span>
<span id="cb67-14"><a href="#cb67-14" aria-hidden="true" tabindex="-1"></a>remaining_doors <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(doors, <span class="fu">c</span>(my_door, montys_door))</span>
<span id="cb67-15"><a href="#cb67-15" aria-hidden="true" tabindex="-1"></a>other_door <span class="ot">&lt;-</span> remaining_doors[<span class="dv">1</span>]</span>
<span id="cb67-16"><a href="#cb67-16" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the result of this trial.</span></span>
<span id="cb67-17"><a href="#cb67-17" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (my_door <span class="sc">==</span> car_door) {</span>
<span id="cb67-18"><a href="#cb67-18" aria-hidden="true" tabindex="-1"></a>    stay_wins <span class="ot">&lt;-</span> <span class="cn">TRUE</span></span>
<span id="cb67-19"><a href="#cb67-19" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb67-20"><a href="#cb67-20" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> (other_door <span class="sc">==</span> car_door) {</span>
<span id="cb67-21"><a href="#cb67-21" aria-hidden="true" tabindex="-1"></a>    switch_wins <span class="ot">&lt;-</span> <span class="cn">TRUE</span></span>
<span id="cb67-22"><a href="#cb67-22" aria-hidden="true" tabindex="-1"></a>}</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>All that remains is to put that trial procedure into a loop, and collect the results as we repeat the procedure many times.</p>
<div class="cell" data-layout-align="center" data-hash="more_sampling_tools_cache/html/unnamed-chunk-76_8c4866ddad5faa8b22488bb3f3c1c92b">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Vectors to store the results for each trial.</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a>stay_wins <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">FALSE</span>, <span class="dv">10000</span>)</span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a>switch_wins <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="cn">FALSE</span>, <span class="dv">10000</span>)</span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Doors to chose from.</span></span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a>doors <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>)</span>
<span id="cb68-7"><a href="#cb68-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-8"><a href="#cb68-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10000</span>) {</span>
<span id="cb68-9"><a href="#cb68-9" aria-hidden="true" tabindex="-1"></a>    <span class="co"># You will recognize the below as the single-trial procedure above.</span></span>
<span id="cb68-10"><a href="#cb68-10" aria-hidden="true" tabindex="-1"></a>    my_door <span class="ot">&lt;-</span> <span class="fu">sample</span>(doors, <span class="at">size=</span><span class="dv">1</span>)</span>
<span id="cb68-11"><a href="#cb68-11" aria-hidden="true" tabindex="-1"></a>    car_door <span class="ot">&lt;-</span> <span class="fu">sample</span>(doors, <span class="at">size=</span><span class="dv">1</span>)</span>
<span id="cb68-12"><a href="#cb68-12" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Which door will Monty open?</span></span>
<span id="cb68-13"><a href="#cb68-13" aria-hidden="true" tabindex="-1"></a>    montys_choices <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(doors, <span class="fu">c</span>(my_door, car_door))</span>
<span id="cb68-14"><a href="#cb68-14" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Choose single door left to choose, or door at random if two.</span></span>
<span id="cb68-15"><a href="#cb68-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="fu">length</span>(montys_choices) <span class="sc">==</span> <span class="dv">1</span>) {  <span class="co"># Only one door available.</span></span>
<span id="cb68-16"><a href="#cb68-16" aria-hidden="true" tabindex="-1"></a>        montys_door <span class="ot">&lt;-</span> montys_choices[<span class="dv">1</span>]  <span class="co"># Take the first (of 1!).</span></span>
<span id="cb68-17"><a href="#cb68-17" aria-hidden="true" tabindex="-1"></a>    } <span class="cf">else</span> {  <span class="co"># Two doors to choose from:</span></span>
<span id="cb68-18"><a href="#cb68-18" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Choose at random.</span></span>
<span id="cb68-19"><a href="#cb68-19" aria-hidden="true" tabindex="-1"></a>        montys_door <span class="ot">&lt;-</span> <span class="fu">sample</span>(montys_choices, <span class="at">size=</span><span class="dv">1</span>)</span>
<span id="cb68-20"><a href="#cb68-20" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb68-21"><a href="#cb68-21" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Now find the door we'll open if we switch.</span></span>
<span id="cb68-22"><a href="#cb68-22" aria-hidden="true" tabindex="-1"></a>    <span class="co"># There is only one door left.</span></span>
<span id="cb68-23"><a href="#cb68-23" aria-hidden="true" tabindex="-1"></a>    remaining_doors <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(doors, <span class="fu">c</span>(my_door, montys_door))</span>
<span id="cb68-24"><a href="#cb68-24" aria-hidden="true" tabindex="-1"></a>    other_door <span class="ot">&lt;-</span> remaining_doors[<span class="dv">1</span>]</span>
<span id="cb68-25"><a href="#cb68-25" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Calculate the result of this trial.</span></span>
<span id="cb68-26"><a href="#cb68-26" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (my_door <span class="sc">==</span> car_door) {</span>
<span id="cb68-27"><a href="#cb68-27" aria-hidden="true" tabindex="-1"></a>        stay_wins[i] <span class="ot">&lt;-</span> <span class="cn">TRUE</span></span>
<span id="cb68-28"><a href="#cb68-28" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb68-29"><a href="#cb68-29" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (other_door <span class="sc">==</span> car_door) {</span>
<span id="cb68-30"><a href="#cb68-30" aria-hidden="true" tabindex="-1"></a>        switch_wins[i] <span class="ot">&lt;-</span> <span class="cn">TRUE</span></span>
<span id="cb68-31"><a href="#cb68-31" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb68-32"><a href="#cb68-32" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb68-33"><a href="#cb68-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-34"><a href="#cb68-34" aria-hidden="true" tabindex="-1"></a>p_for_stay <span class="ot">&lt;-</span> <span class="fu">sum</span>(stay_wins) <span class="sc">/</span> <span class="dv">10000</span></span>
<span id="cb68-35"><a href="#cb68-35" aria-hidden="true" tabindex="-1"></a>p_for_switch <span class="ot">&lt;-</span> <span class="fu">sum</span>(switch_wins) <span class="sc">/</span> <span class="dv">10000</span></span>
<span id="cb68-36"><a href="#cb68-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-37"><a href="#cb68-37" aria-hidden="true" tabindex="-1"></a><span class="fu">message</span>(<span class="st">'p for stay: '</span>, p_for_stay)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>p for stay: 0.3293</code></pre>
</div>
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="fu">message</span>(<span class="st">'p for switch: '</span>, p_for_switch)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>p for switch: 0.6707</code></pre>
</div>
</div>
<p>We can also follow the same strategy as we used for the second implementation of the two-ships problem (<a href="#sec-ships-booleans" class="quarto-xref"><span>Section&nbsp;10.4</span></a>).</p>
<p>Here, as in the second two-ships implementation, we do not calculate the trial results (<code>stay_wins</code>, <code>switch_wins</code>) in each trial. Instead, we store the <em>doors</em> for each trial, and then use Boolean vectors to calculate the results for all trials, at the end.</p>
<div class="cell" data-layout-align="center" data-hash="more_sampling_tools_cache/html/unnamed-chunk-78_cf1c3e557c82271db31d7d693ef8c796">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Instead of storing the trial results, we store the doors for each trial.</span></span>
<span id="cb72-2"><a href="#cb72-2" aria-hidden="true" tabindex="-1"></a>my_doors <span class="ot">&lt;-</span> <span class="fu">numeric</span>(<span class="dv">10000</span>)</span>
<span id="cb72-3"><a href="#cb72-3" aria-hidden="true" tabindex="-1"></a>car_doors <span class="ot">&lt;-</span> <span class="fu">numeric</span>(<span class="dv">10000</span>)</span>
<span id="cb72-4"><a href="#cb72-4" aria-hidden="true" tabindex="-1"></a>other_doors <span class="ot">&lt;-</span> <span class="fu">numeric</span>(<span class="dv">10000</span>)</span>
<span id="cb72-5"><a href="#cb72-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-6"><a href="#cb72-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Doors to chose from.</span></span>
<span id="cb72-7"><a href="#cb72-7" aria-hidden="true" tabindex="-1"></a>doors <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>)</span>
<span id="cb72-8"><a href="#cb72-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-9"><a href="#cb72-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10000</span>) {</span>
<span id="cb72-10"><a href="#cb72-10" aria-hidden="true" tabindex="-1"></a>    my_door <span class="ot">&lt;-</span> <span class="fu">sample</span>(doors, <span class="at">size=</span><span class="dv">1</span>)</span>
<span id="cb72-11"><a href="#cb72-11" aria-hidden="true" tabindex="-1"></a>    car_door <span class="ot">&lt;-</span> <span class="fu">sample</span>(doors, <span class="at">size=</span><span class="dv">1</span>)</span>
<span id="cb72-12"><a href="#cb72-12" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Which door will Monty open?</span></span>
<span id="cb72-13"><a href="#cb72-13" aria-hidden="true" tabindex="-1"></a>    montys_choices <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(doors, <span class="fu">c</span>(my_door, car_door))</span>
<span id="cb72-14"><a href="#cb72-14" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Choose single door left to choose, or door at random if two.</span></span>
<span id="cb72-15"><a href="#cb72-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (<span class="fu">length</span>(montys_choices) <span class="sc">==</span> <span class="dv">1</span>) {  <span class="co"># Only one door available.</span></span>
<span id="cb72-16"><a href="#cb72-16" aria-hidden="true" tabindex="-1"></a>        montys_door <span class="ot">&lt;-</span> montys_choices[<span class="dv">1</span>]  <span class="co"># Take the first (of 1!).</span></span>
<span id="cb72-17"><a href="#cb72-17" aria-hidden="true" tabindex="-1"></a>    } <span class="cf">else</span> {  <span class="co"># Two doors to choose from:</span></span>
<span id="cb72-18"><a href="#cb72-18" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Choose at random.</span></span>
<span id="cb72-19"><a href="#cb72-19" aria-hidden="true" tabindex="-1"></a>        montys_door <span class="ot">&lt;-</span> <span class="fu">sample</span>(montys_choices, <span class="at">size=</span><span class="dv">1</span>)</span>
<span id="cb72-20"><a href="#cb72-20" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb72-21"><a href="#cb72-21" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Now find the door we'll open if we switch.</span></span>
<span id="cb72-22"><a href="#cb72-22" aria-hidden="true" tabindex="-1"></a>    <span class="co"># There is only one door left.</span></span>
<span id="cb72-23"><a href="#cb72-23" aria-hidden="true" tabindex="-1"></a>    remaining_doors <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(doors, <span class="fu">c</span>(my_door, montys_door))</span>
<span id="cb72-24"><a href="#cb72-24" aria-hidden="true" tabindex="-1"></a>    other_door <span class="ot">&lt;-</span> remaining_doors[<span class="dv">1</span>]</span>
<span id="cb72-25"><a href="#cb72-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-26"><a href="#cb72-26" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Store the doors we chose.</span></span>
<span id="cb72-27"><a href="#cb72-27" aria-hidden="true" tabindex="-1"></a>    my_doors[i] <span class="ot">&lt;-</span> my_door</span>
<span id="cb72-28"><a href="#cb72-28" aria-hidden="true" tabindex="-1"></a>    car_doors[i] <span class="ot">&lt;-</span> car_door</span>
<span id="cb72-29"><a href="#cb72-29" aria-hidden="true" tabindex="-1"></a>    other_doors[i] <span class="ot">&lt;-</span> other_door</span>
<span id="cb72-30"><a href="#cb72-30" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb72-31"><a href="#cb72-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-32"><a href="#cb72-32" aria-hidden="true" tabindex="-1"></a><span class="co"># Now - at the end of all the trials, we use Boolean vectors to calculate the</span></span>
<span id="cb72-33"><a href="#cb72-33" aria-hidden="true" tabindex="-1"></a><span class="co"># results.</span></span>
<span id="cb72-34"><a href="#cb72-34" aria-hidden="true" tabindex="-1"></a>stay_wins <span class="ot">&lt;-</span> my_doors <span class="sc">==</span> car_doors</span>
<span id="cb72-35"><a href="#cb72-35" aria-hidden="true" tabindex="-1"></a>switch_wins <span class="ot">&lt;-</span> other_doors <span class="sc">==</span> car_doors</span>
<span id="cb72-36"><a href="#cb72-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-37"><a href="#cb72-37" aria-hidden="true" tabindex="-1"></a>p_for_stay <span class="ot">&lt;-</span> <span class="fu">sum</span>(stay_wins) <span class="sc">/</span> <span class="dv">10000</span></span>
<span id="cb72-38"><a href="#cb72-38" aria-hidden="true" tabindex="-1"></a>p_for_switch <span class="ot">&lt;-</span> <span class="fu">sum</span>(switch_wins) <span class="sc">/</span> <span class="dv">10000</span></span>
<span id="cb72-39"><a href="#cb72-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb72-40"><a href="#cb72-40" aria-hidden="true" tabindex="-1"></a><span class="fu">message</span>(<span class="st">'p for stay: '</span>, p_for_stay)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>p for stay: 0.3336</code></pre>
</div>
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a><span class="fu">message</span>(<span class="st">'p for switch: '</span>, p_for_switch)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>p for switch: 0.6664</code></pre>
</div>
</div>
<section id="insight-from-the-monty-hall-simulation" class="level3" data-number="10.7.1">
<h3 data-number="10.7.1" class="anchored" data-anchor-id="insight-from-the-monty-hall-simulation"><span class="header-section-number">10.7.1</span> Insight from the Monty Hall simulation</h3>
<p>The code simulation gives us an estimate of the right answer, but it also forces us to set out the exact mechanics of the problem. For example, by looking at the code, we see that we can calculate “stay_wins” with this code alone:</p>
<div class="cell" data-layout-align="center" data-hash="more_sampling_tools_cache/html/unnamed-chunk-80_8ebf361d6e4ca583f7c6a2dd6f7c54c7">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Just choose my door and the car door for each trial.</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>my_doors <span class="ot">&lt;-</span> <span class="fu">numeric</span>(<span class="dv">10000</span>)</span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>car_doors <span class="ot">&lt;-</span> <span class="fu">numeric</span>(<span class="dv">10000</span>)</span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>doors <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>)</span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-6"><a href="#cb76-6" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10000</span>) {</span>
<span id="cb76-7"><a href="#cb76-7" aria-hidden="true" tabindex="-1"></a>    my_doors[i] <span class="ot">&lt;-</span> <span class="fu">sample</span>(doors, <span class="at">size=</span><span class="dv">1</span>)</span>
<span id="cb76-8"><a href="#cb76-8" aria-hidden="true" tabindex="-1"></a>    car_doors[i] <span class="ot">&lt;-</span> <span class="fu">sample</span>(doors, <span class="at">size=</span><span class="dv">1</span>)</span>
<span id="cb76-9"><a href="#cb76-9" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb76-10"><a href="#cb76-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-11"><a href="#cb76-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate whether I won by staying.</span></span>
<span id="cb76-12"><a href="#cb76-12" aria-hidden="true" tabindex="-1"></a>stay_wins <span class="ot">&lt;-</span> my_doors <span class="sc">==</span> car_doors</span>
<span id="cb76-13"><a href="#cb76-13" aria-hidden="true" tabindex="-1"></a>p_for_stay <span class="ot">&lt;-</span> <span class="fu">sum</span>(stay_wins) <span class="sc">/</span> <span class="dv">10000</span></span>
<span id="cb76-14"><a href="#cb76-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb76-15"><a href="#cb76-15" aria-hidden="true" tabindex="-1"></a><span class="fu">message</span>(<span class="st">'p for stay: '</span>, p_for_stay)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>p for stay: 0.3363</code></pre>
</div>
</div>
<p>This calculation, on its own, tells us the answer, but it also points to another insight — whatever Monty does with the doors, it doesn’t change the probability that our <em>initial guess</em> is right, and that must be 1 in 3 (0.333). If the probability of <code>stay_win</code> is 1 in 3, and we only have one other door to switch to, the probability of winning after switching must be 2 in 3 (0.666).</p>
</section>
<section id="simulation-and-a-variant-of-monty-hall" class="level3" data-number="10.7.2">
<h3 data-number="10.7.2" class="anchored" data-anchor-id="simulation-and-a-variant-of-monty-hall"><span class="header-section-number">10.7.2</span> Simulation and a variant of Monty Hall</h3>
<p>You have seen that you can avoid the silly mistakes that many of us make with probability — by asking the computer to tell you the result <em>before</em> you start to reason from first principles.</p>
<p>As an example, consider the following variant of the Monty Hall problem.</p>
<p>The set up to the problem has us choosing a door (<code>my_door</code> above), and then Monty opens one of the other two doors.</p>
<p>Sometimes (in fact, 2/3 of the time) there is a car behind one of Monty’s doors. We’ve obliged Monty to open the <em>other</em> door, and his choice is forced.</p>
<p>When his choice was not forced, we had Monty choose the door at random.</p>
<p>For example, let us say we chose door 1.</p>
<p>Let us say that the car is also under door 1.</p>
<p>Monty has the option of choosing door 2 or door 3, and he chooses randomly between them.</p>
<div class="cell" data-layout-align="center" data-hash="more_sampling_tools_cache/html/unnamed-chunk-82_1c3986d189f4cb541cb5b62cd0f32cdd">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>my_door <span class="ot">&lt;-</span> <span class="dv">1</span>  <span class="co"># We chose door 1 at random.</span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>car_door <span class="ot">&lt;-</span> <span class="dv">1</span>  <span class="co"># This trial, by chance, the car door is 1.</span></span>
<span id="cb78-3"><a href="#cb78-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Monty is left with doors 2 and 3 to choose from.</span></span>
<span id="cb78-4"><a href="#cb78-4" aria-hidden="true" tabindex="-1"></a>montys_choices <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(doors, <span class="fu">c</span>(my_door, car_door))</span>
<span id="cb78-5"><a href="#cb78-5" aria-hidden="true" tabindex="-1"></a><span class="co"># He chooses randomly.</span></span>
<span id="cb78-6"><a href="#cb78-6" aria-hidden="true" tabindex="-1"></a>montys_door <span class="ot">&lt;-</span> <span class="fu">sample</span>(montys_choices, <span class="at">size=</span><span class="dv">1</span>)</span>
<span id="cb78-7"><a href="#cb78-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Show the result</span></span>
<span id="cb78-8"><a href="#cb78-8" aria-hidden="true" tabindex="-1"></a>montys_door</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
</div>
<p>Now — let us say we happen to know that Monty is rather lazy, and he will always choose the left-most (lower-numbered) door of the two options.</p>
<p>In the previous example, Monty had the option of choosing door 2 and 3. In this new scenario, we know that he will always choose door 2 (the left-most door).</p>
<div class="cell" data-layout-align="center" data-hash="more_sampling_tools_cache/html/unnamed-chunk-84_526f57f4c5574badcc08961cf2c1a02e">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a>my_door <span class="ot">&lt;-</span> <span class="dv">1</span>  <span class="co"># We chose door 1 at random.</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>car_door <span class="ot">&lt;-</span> <span class="dv">1</span>  <span class="co"># This trial, by chance, the car door is 1.</span></span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Monty is left with doors 2 and 3 to choose from.</span></span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a>montys_choices <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(doors, <span class="fu">c</span>(my_door, car_door))</span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a><span class="co"># He chooses the left-most door, always.</span></span>
<span id="cb80-6"><a href="#cb80-6" aria-hidden="true" tabindex="-1"></a>montys_door <span class="ot">&lt;-</span> montys_choices[<span class="dv">1</span>]</span>
<span id="cb80-7"><a href="#cb80-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Show the result</span></span>
<span id="cb80-8"><a href="#cb80-8" aria-hidden="true" tabindex="-1"></a>montys_door</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
</div>
<p>It feels as if we have more information about where the car is, when we know this. Consider the situation where we have chosen door 1, and Monty opens door 3. We know that he would have preferred to open door 2, if he was allowed. We therefore know he wasn’t allowed to open door 2, and that means the car is definitely under door 2.</p>
<div class="cell" data-layout-align="center" data-hash="more_sampling_tools_cache/html/unnamed-chunk-86_03b52bd975427d0e32ee2ad69582d568">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>my_door <span class="ot">&lt;-</span> <span class="dv">1</span>  <span class="co"># We chose door 1 at random.</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>car_door <span class="ot">&lt;-</span> <span class="dv">1</span>  <span class="co"># This trial, by chance, the car door is 1.</span></span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Monty is left with door 3 only to choose from.</span></span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a>montys_choices <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(doors, <span class="fu">c</span>(my_door, car_door))</span>
<span id="cb82-5"><a href="#cb82-5" aria-hidden="true" tabindex="-1"></a><span class="co"># He chooses the left-most door, always.  But in this case, the left-most</span></span>
<span id="cb82-6"><a href="#cb82-6" aria-hidden="true" tabindex="-1"></a><span class="co"># available door is 3 (he can't choose 2, it is the car_door).</span></span>
<span id="cb82-7"><a href="#cb82-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Notice the doors were in order, so the left-most door is the first door</span></span>
<span id="cb82-8"><a href="#cb82-8" aria-hidden="true" tabindex="-1"></a><span class="co"># in the vector.</span></span>
<span id="cb82-9"><a href="#cb82-9" aria-hidden="true" tabindex="-1"></a>montys_door <span class="ot">&lt;-</span> montys_choices[<span class="dv">1</span>]</span>
<span id="cb82-10"><a href="#cb82-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Show the result</span></span>
<span id="cb82-11"><a href="#cb82-11" aria-hidden="true" tabindex="-1"></a>montys_door</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2</code></pre>
</div>
</div>
<p>To take that into account, we might try a different strategy. We will stick to our own choice if Monty has chosen the left-most of the two doors he had available to him, because he might have chosen that door because there was a car underneath the other door, or because there was a car under neither, but he preferred the left door. But, if Monty chooses the right-most of the two-doors available to him, we will switch from our own choice to the other (unopened) door, because we can be sure that the car is under the other (unopened) door.</p>
<p>Call this the “switch if Monty chooses right door” strategy, or “switch if right” for short.</p>
<p>Can you see quickly whether this will be better than the “always stay” strategy? Will it be better than the “always switch” strategy? Take a moment to think it through, and write down your answers.</p>
<p>If you can quickly see the answer to both questions — well done — but, are you sure you are right?</p>
<p>We can test by simulation.</p>
<p>For our test of the “switch is right” strategy, we can tell if one door is to the right of another door by comparison; higher numbers mean further to the right: 2 is right of 1, and 3 is right of 2.</p>
<div class="cell" data-layout-align="center" data-hash="more_sampling_tools_cache/html/unnamed-chunk-88_f3a915ceed7955dba61b5bca609ec80c">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Door 3 is right of door 1.</span></span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a><span class="dv">3</span> <span class="sc">&gt;</span> <span class="dv">1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center" data-hash="more_sampling_tools_cache/html/unnamed-chunk-90_f6bd7f8234435e363a9a2a37e4261adc">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="co"># A test of the switch-if-right strategy.</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a><span class="co"># The car doors.</span></span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>car_doors <span class="ot">&lt;-</span> <span class="fu">numeric</span>(<span class="dv">10000</span>)</span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a><span class="co"># The door we chose using the strategy.</span></span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a>strategy_doors <span class="ot">&lt;-</span> <span class="fu">numeric</span>(<span class="dv">10000</span>)</span>
<span id="cb86-6"><a href="#cb86-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-7"><a href="#cb86-7" aria-hidden="true" tabindex="-1"></a>doors <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>)</span>
<span id="cb86-8"><a href="#cb86-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-9"><a href="#cb86-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">10000</span>) {</span>
<span id="cb86-10"><a href="#cb86-10" aria-hidden="true" tabindex="-1"></a>    my_door <span class="ot">&lt;-</span> <span class="fu">sample</span>(doors, <span class="at">size=</span><span class="dv">1</span>)</span>
<span id="cb86-11"><a href="#cb86-11" aria-hidden="true" tabindex="-1"></a>    car_door <span class="ot">&lt;-</span> <span class="fu">sample</span>(doors, <span class="at">size=</span><span class="dv">1</span>)</span>
<span id="cb86-12"><a href="#cb86-12" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Which door will Monty open?</span></span>
<span id="cb86-13"><a href="#cb86-13" aria-hidden="true" tabindex="-1"></a>    montys_choices <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(doors, <span class="fu">c</span>(my_door, car_door))</span>
<span id="cb86-14"><a href="#cb86-14" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Choose Monty's door from the remaining options.</span></span>
<span id="cb86-15"><a href="#cb86-15" aria-hidden="true" tabindex="-1"></a>    <span class="co"># This time, he always prefers the left door.</span></span>
<span id="cb86-16"><a href="#cb86-16" aria-hidden="true" tabindex="-1"></a>    montys_door <span class="ot">&lt;-</span> montys_choices[<span class="dv">1</span>]</span>
<span id="cb86-17"><a href="#cb86-17" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Now find the door we'll open if we switch.</span></span>
<span id="cb86-18"><a href="#cb86-18" aria-hidden="true" tabindex="-1"></a>    remaining_doors <span class="ot">&lt;-</span> <span class="fu">setdiff</span>(doors, <span class="fu">c</span>(my_door, montys_door))</span>
<span id="cb86-19"><a href="#cb86-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># There is only one door remaining - but is Monty's door</span></span>
<span id="cb86-20"><a href="#cb86-20" aria-hidden="true" tabindex="-1"></a>    <span class="co"># to the right of this one?  Then Monty had to shift.</span></span>
<span id="cb86-21"><a href="#cb86-21" aria-hidden="true" tabindex="-1"></a>    other_door <span class="ot">&lt;-</span> remaining_doors[<span class="dv">1</span>]</span>
<span id="cb86-22"><a href="#cb86-22" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> (montys_door <span class="sc">&gt;</span> other_door) {</span>
<span id="cb86-23"><a href="#cb86-23" aria-hidden="true" tabindex="-1"></a>        <span class="co"># Monty's door was the right-hand door, the car is under the other one.</span></span>
<span id="cb86-24"><a href="#cb86-24" aria-hidden="true" tabindex="-1"></a>        strategy_doors[i] <span class="ot">&lt;-</span> other_door</span>
<span id="cb86-25"><a href="#cb86-25" aria-hidden="true" tabindex="-1"></a>    } <span class="cf">else</span> {  <span class="co"># We stick with the door we first thought of.</span></span>
<span id="cb86-26"><a href="#cb86-26" aria-hidden="true" tabindex="-1"></a>        strategy_doors[i] <span class="ot">&lt;-</span> my_door</span>
<span id="cb86-27"><a href="#cb86-27" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb86-28"><a href="#cb86-28" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Store the car door for this trial.</span></span>
<span id="cb86-29"><a href="#cb86-29" aria-hidden="true" tabindex="-1"></a>    car_doors[i] <span class="ot">&lt;-</span> car_door</span>
<span id="cb86-30"><a href="#cb86-30" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb86-31"><a href="#cb86-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-32"><a href="#cb86-32" aria-hidden="true" tabindex="-1"></a>strategy_wins <span class="ot">&lt;-</span> strategy_doors <span class="sc">==</span> car_doors</span>
<span id="cb86-33"><a href="#cb86-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-34"><a href="#cb86-34" aria-hidden="true" tabindex="-1"></a>p_for_strategy <span class="ot">&lt;-</span> <span class="fu">sum</span>(strategy_wins) <span class="sc">/</span> <span class="dv">10000</span></span>
<span id="cb86-35"><a href="#cb86-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-36"><a href="#cb86-36" aria-hidden="true" tabindex="-1"></a><span class="fu">message</span>(<span class="st">'p for strategy: '</span>, p_for_strategy)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>p for strategy: 0.6668</code></pre>
</div>
</div>
<p>We find that the “switch-if-right” has around the same chance of success as the “always-switch” strategy — of about 66.6%, or 2 in 3. Were your initial answers right? Now you’ve seen the result, can you see why it should be so? It may not be obvious — the Monty Hall problem is deceptively difficult. But our case here is that the simulation first gives you an estimate of the correct answer, and then, gives you a good basis for thinking more about the problem. That is:</p>
<ul>
<li>simulation is useful for estimation and</li>
<li>simulation is useful for reflection.</li>
</ul>
<p>End of <code>monty_hall</code> notebook</p>
</section>
</div>
</section>
<section id="why-use-simulation" class="level2" data-number="10.8">
<h2 data-number="10.8" class="anchored" data-anchor-id="why-use-simulation"><span class="header-section-number">10.8</span> Why use simulation?</h2>
<p>Doing these simulations has two large benefits. First, it gives us the right answer, saving us from making a mistake. Second, the process of simulation forces us to think about how the problem works. This can give us better understanding, and make it easier to reason about the solution.</p>
<p>We will soon see that these same advantages also apply to reasoning about statistics.</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-goldberg1986probability" class="csl-entry" role="listitem">
Goldberg, Samuel. 1986. <em>Probability: An Introduction</em>. Courier Corporation. <a href="https://www.google.co.uk/books/edition/Probability/CmzFx9rB_FcC">https://www.google.co.uk/books/edition/Probability/CmzFx9rB_FcC</a>.
</div>
<div id="ref-savant1990monty" class="csl-entry" role="listitem">
Savant, Marilyn vos. 1990. <span>“Ask Marilyn.”</span> 1990. <a href="https://web.archive.org/web/20160318182523/http://marilynvossavant.com/game-show-problem">https://web.archive.org/web/20160318182523/http://marilynvossavant.com/game-show-problem</a>.
</div>
<div id="ref-slevin1975monty" class="csl-entry" role="listitem">
Selvin, Steve. 1975. <span>“Letters to the Editor.”</span> <em>The American Statistician</em> 29 (1): 67. <a href="http://www.jstor.org/stable/2683689">http://www.jstor.org/stable/2683689</a>.
</div>
<div id="ref-vazsonyi1999door" class="csl-entry" role="listitem">
Vazsonyi, Andrew. 1999. <span>“Which Door Has the Cadillac.”</span> <em>Decision Line</em> 30 (1): 17–19. <a href="https://web.archive.org/web/20140413131827/http://www.decisionsciences.org/DecisionLine/Vol30/30_1/vazs30_1.pdf">https://web.archive.org/web/20140413131827/http://www.decisionsciences.org/DecisionLine/Vol30/30_1/vazs30_1.pdf</a>.
</div>
</div>
</section>
<aside id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>The treasure fleet problem is a restatement of <a href="https://en.wikipedia.org/wiki/Bertrand's_box_paradox">a problem that Joseph Bertrand posed</a> early in the 19th century.) Here is a variation from <span class="citation" data-cites="goldberg1986probability">(<a href="references.html#ref-goldberg1986probability" role="doc-biblioref">Goldberg 1986, 99</a>)</span>:</p>
<blockquote class="blockquote">
<p>Three identical boxes each contain two coins. In one box both are pennies, in the second both are nickels, and in the third there is one penny and one nickel.</p>
<p>A man chooses a box at random and takes out a coin. If the coin is a penny, what is the probability that the other coin in the box is also a penny?</p>
</blockquote>
<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></li>
<li id="fn2"><p>Although we have used multiple <code>if</code> statements to set the chests for each ship in the code for the ship problem, it would have been more elegant to store the definitions of ships and chests as <span class="r">an R list</span>. We haven’t covered these, but to give you a taste of what that would look like, for a single trial.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We define the ships and their respective chests, using a list of lists.</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Remember, list has elements, where the elements can be any type of value.</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co"># In this case, the elements in the list are themselves - lists.</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>ship_chests <span class="op">=</span> [  <span class="co"># Create list, with lists as elements.</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>    [<span class="st">'Gold'</span>, <span class="st">'Gold'</span>],  <span class="co"># List for ship 1; element 0 of the list of lists.</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>    [<span class="st">'Gold'</span>, <span class="st">'Silver'</span>],  <span class="co"># List for ship 2; element 1 of the list of lists.</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    [<span class="st">'Silver'</span>, <span class="st">'Silver'</span>]  <span class="co"># Ship 3; element 2.</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>]</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Choose a ship at random.</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>ship_no <span class="op">=</span> rnd.choice([<span class="dv">0</span>, <span class="dv">1</span>, <span class="dv">2</span>])</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the corresponding chests for this ship.</span></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>chests <span class="op">=</span> ship_chests[ship_no]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="sourceCode" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We define the ships and their respective chests, using an R list.</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co"># An R list has elements, where the elements can be any type of value.</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co"># In this case, the elements in the list are vectors, one vector for each</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="co"># ship.</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>ship_chests <span class="ot">&lt;-</span> <span class="fu">list</span>(  <span class="co"># Create list, with vectors as elements.</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">c</span>(<span class="st">'Gold'</span>, <span class="st">'Gold'</span>),  <span class="co"># Vector for ship 1</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">c</span>(<span class="st">'Gold'</span>, <span class="st">'Silver'</span>),  <span class="co"># Ship 2</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a>    <span class="fu">c</span>(<span class="st">'Silver'</span>, <span class="st">'Silver'</span>)  <span class="co"># Ship 3</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Choose a ship at random.</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>ship_no <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>, <span class="at">size=</span><span class="dv">1</span>)</span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Get the corresponding chests for this ship.</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Notice the double square brackets to get the list item.</span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>chests <span class="ot">&lt;-</span> ship_chests[[ship_no]]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></li>
</ol>
</aside>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./probability_theory_1b.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Probability Theory Part I (continued)</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./probability_theory_2_compound.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Probability Theory, Part 2: Compound Probability</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>