<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.1">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>14&nbsp; On Variability in Sampling – Resampling statistics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./monte_carlo.html" rel="next">
<link href="./probability_theory_4_finite.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script type="text/javascript">
  $(document).ready(function() {
    $("table").addClass('lightable-paper lightable-striped lightable-hover')
  });
</script>


<link rel="stylesheet" href="style.css">
<link rel="stylesheet" href="font-awesome.min.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./sampling_variability.html"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">On Variability in Sampling</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Resampling statistics</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R edition</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface_third.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface to the third edition</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface_second.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface to the second edition</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./resampling_method.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The resampling method</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./what_is_probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">What is probability?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./about_technology.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Introducing R and the RStudio notebook</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./resampling_with_code.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Resampling with code</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./resampling_with_code2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">More resampling with code</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sampling_tools.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Tools for samples and sampling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability_theory_1a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Probability Theory, Part 1</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability_theory_1b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Probability Theory Part I (continued)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./more_sampling_tools.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Two puzzles and more tools</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability_theory_2_compound.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Probability Theory, Part 2: Compound Probability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability_theory_3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Probability Theory, Part 3</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability_theory_4_finite.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Probability Theory, Part 4: Estimating Probabilities from Finite Universes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sampling_variability.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">On Variability in Sampling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./monte_carlo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">The Procedures of Monte Carlo Simulation (and Resampling)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./standard_scores.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Ranks, Quantiles and Standard Scores</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference_ideas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">The Basic Ideas in Statistical Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Introduction to Statistical Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./point_estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Point Estimation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./framing_questions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Framing Statistical Questions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./testing_counts_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Hypothesis-Testing with Counted Data, Part 1</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./significance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">The Concept of Statistical Significance in Testing Hypotheses</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./testing_counts_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">The Statistics of Hypothesis-Testing with Counted Data, Part 2</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./testing_measured.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">The Statistics of Hypothesis-Testing With Measured Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./testing_procedures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">General Procedures for Testing Hypotheses</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./confidence_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Confidence Intervals, Part 1: Assessing the Accuracy of Samples</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./confidence_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Confidence Intervals, Part 2: The Two Approaches to Estimating Confidence Intervals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./reliability_average.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Some Last Words About the Reliability of Sample Averages</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./correlation_causation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Correlation and Causation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./how_big_sample.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">How Large a Sample?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bayes_simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Bayesian Analysis by Simulation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./exercise_solutions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Exercise Solutions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./acknowlegements.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Acknowledgements</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./technical_note.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Technical Note to the Professional Reader</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#variability-and-small-samples" id="toc-variability-and-small-samples" class="nav-link active" data-scroll-target="#variability-and-small-samples"><span class="header-section-number">14.1</span> Variability and small samples</a></li>
  <li><a href="#regression-to-the-mean" id="toc-regression-to-the-mean" class="nav-link" data-scroll-target="#regression-to-the-mean"><span class="header-section-number">14.2</span> Regression to the mean</a></li>
  <li><a href="#summary-and-conclusion" id="toc-summary-and-conclusion" class="nav-link" data-scroll-target="#summary-and-conclusion"><span class="header-section-number">14.3</span> Summary and conclusion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-sampling-variability" class="quarto-section-identifier"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">On Variability in Sampling</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p>[Debra said]: “I’ve had such good luck with Japanese cars and poor luck with American...”</p>
</blockquote>
<blockquote class="blockquote">
<p>The ’65 Ford Mustang: “It was fun, but I had to put two new transmissions in it.”</p>
</blockquote>
<blockquote class="blockquote">
<p>The Ford Torino: “That got two transmissions too. That finished me with Ford.”</p>
</blockquote>
<blockquote class="blockquote">
<p>The Plymouth Horizon: “The disaster of all disasters. That should’ve been painted bright yellow. What a lemon.”</p>
</blockquote>
<p>(From <em>Washington Post Magazine</em> , May 17, 1992, p.&nbsp;19)</p>
<p>Do the quotes above convince you that Japanese cars are better than American? Has Debra got enough evidence to reach the conclusion she now holds? That sort of question, and the reasoning we use to address it, is the subject of this chapter.</p>
<p>More generally, how should one go about using the available data to test the hypothesis that Japanese cars are better? That is an example of the questions that are the subject of statistics.</p>
<section id="variability-and-small-samples" class="level2" data-number="14.1">
<h2 data-number="14.1" class="anchored" data-anchor-id="variability-and-small-samples"><span class="header-section-number">14.1</span> Variability and small samples</h2>
<p>Perhaps the most important idea for sound statistical inference — the section of the book we are now beginning, in contrast to problems in probability, which we have studied in the previous chapters — is recognition of the <em>presence of variability in the results of small samples</em> . The fatal error of relying on too-small samples is all too common among economic forecasters, journalists, and others who deal with trends and public opinion. Athletes, sports coaches, sportswriters, and fans too frequently disregard this principle both in their decisions and in their discussion.</p>
<p>Our intuitions often carry us far astray when the results vary from situation to situation — that is, when there is variability in outcomes — and when we have only a small sample of outcomes to look at.</p>
<p>To motivate the discussion, I’ll tell you something that almost no American sports fan will believe: There is no such thing as a slump in baseball batting. That is, a batter often goes an alarming number of at-bats without getting a hit, and everyone — the manager, the sportswriters, and the batter himself — assumes that something has changed, and the probability of the batter getting a hit is now lower than it was before the slump. It is common for the manager to replace the player for a while, and for the player and coaches to change the player’s hitting style so as to remedy the defect. But the chance of a given batter getting a hit is just the same after he has gone many at-bats without a hit as when he has been hitting well. A belief in slumps causes managers to play line-ups which may not be their best.</p>
<p>By “slump” I mean that a player’s probability of getting a hit in a given at-bat is lower during a period than during average periods. And when I say there is no such thing as a slump, I mean that the chances of getting a hit after any sequence of at-bats without a hit is <em>not</em> different than the long-run average.</p>
<p>The “hot hand” in basketball is another illusion. In practical terms, the hot hand does not exist — or rather — if it does, the effect is weak.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a> The chance of a shooter scoring is more or less the same after they have just missed a flock of shots as when they have just sunk a long string. That is, the chance of scoring a basket is not appreciably higher after a run of successes than after a run of failures. But even professional teams choose plays on the basis of who supposedly has a hot hand.</p>
<p>Managers who substitute for the “slumping” or “cold-handed” players with other players who, in the long run, have lower batting averages, or set up plays for the shooter who supposedly has a hot hand, make a mistake. The supposed hot hand in basketball, and the slump in baseball, are illusions because the observed long runs of outs, or of baskets, are statistical artifacts, due to ordinary random variability. The identification of slumps and hot hands is superstitious behavior, classic cases of the assignment of pattern to a series of events when there really is no pattern.</p>
<p>How do statisticians ascertain that slumps and hot hands are very weak effects, or do not exist? In brief, in baseball we simulate a hitter with a given average — say .250 — and compare the results with actual hitters of that average, to see whether they have “slumps” longer than the computer. The method of investigation is roughly as follows. You program a computer or other machine to behave the way a player would, given the player’s long-run average, on the assumption that each trial is a random drawing. For example, if a player has a .250 season-long batting average, the machine is programmed like a bucket containing three black balls and one white ball. Then for each simulated at bat, the machine shuffles the “balls” and draws one; it then records whether the result is black or white, after which the ball is replaced in the bucket. To study a season with four hundred at-bats, a simulated ball is drawn four hundred times.</p>
<p>The records of the player’s real season and the simulated season are then compared. If there really is such a thing as a non-random slump or streak, there will be fewer but longer “runs” of hits or outs in the real record than in the simulated record. On the other hand, if performance is independent from at-bat trial to at-bat trial, the actual record will change from hit to out and from out to hit as often as does the random simulated record. I suggested this sort of test for the existence of slumps in my 1969 book that first set forth the resampling method, a predecessor of this book.</p>
<p>For example, <a href="#tbl-at-bats" class="quarto-xref">Table&nbsp;<span>14.1</span></a> shows the results of one 400 at-bat season for a simulated .250 hitter. (H = hit, O = out, sequential at-bats ordered vertically) Note the “slump” — 1 for 24 — in columns 7 &amp; 8 (in bold).</p>
<div id="tbl-at-bats" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-at-bats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;14.1: 400 simulated at-bats (ordered vertically)
</figcaption>
<div aria-describedby="tbl-at-bats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<tbody>
<tr class="odd">
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;"><strong>O</strong></td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
</tr>
<tr class="even">
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;"><strong>O</strong></td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
</tr>
<tr class="odd">
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;"><strong>O</strong></td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
</tr>
<tr class="even">
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;"><strong>O</strong></td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;"><strong>O</strong></td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
</tr>
<tr class="even">
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
</tr>
<tr class="odd">
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;"><strong>O</strong></td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
</tr>
<tr class="even">
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;"><strong>O</strong></td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
</tr>
<tr class="odd">
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;"><strong>O</strong></td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
</tr>
<tr class="even">
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;"><strong>O</strong></td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
</tr>
<tr class="odd">
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;"><strong>O</strong></td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
</tr>
<tr class="even">
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;"><strong>O</strong></td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
</tr>
<tr class="odd">
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;"><strong>O</strong></td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">H</td>
</tr>
<tr class="even">
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;"><strong>H</strong></td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
</tr>
<tr class="odd">
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;"><strong>O</strong></td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
</tr>
<tr class="even">
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;"><strong>O</strong></td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
</tr>
<tr class="odd">
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;"><strong>O</strong></td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
</tr>
<tr class="even">
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;"><strong>O</strong></td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
</tr>
<tr class="odd">
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;"><strong>O</strong></td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
</tr>
<tr class="even">
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;"><strong>O</strong></td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
</tr>
<tr class="odd">
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;"><strong>O</strong></td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
</tr>
<tr class="even">
<td style="text-align: left;">H</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;"><strong>O</strong></td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
</tr>
<tr class="odd">
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;"><strong>O</strong></td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
</tr>
<tr class="even">
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;"><strong>O</strong></td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
</tr>
<tr class="odd">
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;"><strong>O</strong></td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">H</td>
<td style="text-align: left;">O</td>
<td style="text-align: left;">O</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Harry Roberts investigated the batting records of a sample of major leaguers.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> He compared players’ season-long records against the behavior of random-number drawings. If slumps existed rather than being a fiction of the imagination, the real players’ records would shift from a string of hits to a string of outs less frequently than would the random-number sequences. But in fact the number of shifts, and the average lengths of strings of hits and outs, are on average the same for players as for player-simulating random-number devices.</p>
<p>Over long periods, averages may vary systematically, as Ty Cobb’s annual batting averages varied non-randomly from season to season, Roberts found. But in the short run, most individual and team performances have shown results similar to the outcomes that a lottery-type random number machine would produce.</p>
<p>Thomas Gilovich, Robert Vallone and Amos Twersky <span class="citation" data-cites="gilovich1985hot">(<a href="references.html#ref-gilovich1985hot" role="doc-biblioref">1985</a>)</span> performed a similar study of basketball shooting. They examined the records of shots from the floor by the Philadelphia 76’ers, foul shots by the Boston Celtics, and a shooting experiment of Cornell University teams. They found that “basketball players and fans alike tend to believe that a player’s chance of hitting a shot are greater following a hit than following a miss on the previous shot. However, detailed analyses…provided no evidence for a positive correlation between the outcomes of successive shots.”</p>
<p>To put their conclusion differently, knowing whether a shooter has scored or not scored on the previous shot — or in any previous sequence of shots — is of absolutely no use in predicting whether the shooter will or will not score on the next shot. Similarly, knowledge of the past series of at-bats in baseball does not improve a prediction of whether a batter will get a hit this time.</p>
<p>Of course a batter <em>feels</em> — and intensely — as if she or he has a better chance of getting a hit at some times than at other times. After a series of successful at-bats, both sandlot players and professionals feel confident that this time will be a hit, too. And after you have hit a bunch of baskets from all over the court, you feel as if you can’t miss.</p>
<p>But notice that card players get the same poignant feeling of being “hot” or “cold,” too. After a poker player “fills” several straights and flushes in a row, s/he feels s/he will hit the next one too. (Of course there are some players who feel just the opposite, that the “law of averages” is about to catch up with them.)</p>
<p>You will agree, I’m sure, that the cards don’t have any memory, and a player’s chance of filling a straight or flush remains the same no matter how he or she has done in the last series of hands. Clearly, then, a person can have a strong feeling that something is about to happen even when that feeling has no foundation. This supports the idea that even though a player in sports “feels” that s/he is in a slump or has a hot hand, this does not imply that the feeling has any basis in reality.</p>
<p>Why, when a batter is low in his/her mind because s/he has been making a lot of outs or for personal reasons, does her/ his batting not suffer? And why the opposite? Apparently at any given moment there are many influences operating upon a player’s performance in a variety of directions, with none of them clearly dominant. Hence there is no simple convincing explanation why a player gets a hit or an out, a basket or a miss, on any given attempt.</p>
<p>But though science cannot provide an explanation, the sports commentators always are ready to offer their analyses. Listen, for example, to how they tell you that Joe Zilch must have been trying extra hard <em>just because of</em> his slump. There is a sportswriter’s explanation for <em>anything</em> that happens.</p>
<p>Why do we believe the nonsense we hear about “momentum,” “comeback,” “she’s due this time,” and so on? The adult of the human species has a powerful propensity to believe that he or she can find a pattern even when there is no pattern to be found. Two decades ago I cooked up series of numbers with a random-number machine that looked as if they were prices on the stock market. Subjects in the experiment were told to buy and sell whichever stocks they chose. Then I gave them “another day’s prices,” and asked them to buy and sell again. The subjects did all kinds of fancy figuring, using an incredible variety of assumptions — even though there was no way for the figuring to help them. That is, people sought patterns even though there was no reason to believe that there were any patterns to be found.</p>
<p>When I stopped the game before the ten buy-and-sell sessions the participants expected, people asked that the game continue. Then I would tell them that there was no basis for any patterns in the data. “Winning” or “losing” had no meaning. But the subjects demanded to continue anyway. They continued believing that they could find patterns even after I told them that the numbers were randomly looked up and not real stock prices.</p>
<p>The illusions in our thinking about sports have important counterparts in our thinking about such real-world phenomena as the climate, the stock market, and trends in the prices of raw materials such as mercury, copper and wheat. And private and public decisions made on the basis of faulty understanding of these real situations, caused by illusory thinking on the order of belief in slumps and hot hands, are often costly and sometimes disastrous.</p>
<p>An example of the belief that there are patterns when there are none: Systems for finding patterns in the stock market are peddled that have about the same reliability as advice from a racetrack tout — and millions buy them.</p>
<p>One of the scientific strands leading into research on variability was the body of studies that considers the behavior of stock prices as a “random walk.” That body of work asserts that a stock broker or chartist who claims to be able to find patterns in past price movements of stocks that will predict future movements should be listened to with about the same credulity as a racetrack tout or an astrologer. A second strand was the work in psychology in the last decade or two which has recognized that people’s estimates of uncertain events are systematically biased in a variety of interesting and knowable ways.</p>
<p>The U.S. government has made — and continues to make — blunders costing the public scores of billions of dollars, using slump-type fallacious reasoning about resources and energy. Forecasts are issued and policies are adopted based on the belief that a short-term increase in price constitutes a long-term trend. But the “experts” employed by the government to make such forecasts do no better on average than do private forecasters, and often the system of forecasting that they use is much more misleading than would be a random-number generating machine of the sort used in the baseball slump experiments.</p>
<p>Please look at the data in <a href="#fig-nile_height" class="quarto-xref">Figure&nbsp;<span>14.1</span></a> for the height of the Nile River over about half a century. Is it not natural to think that those data show a decline in the height of the river? One can imagine that if our modern communication technology existed then, the Cairo newspapers would have been calling for research to be done on the fall of the Nile, and the television anchors would have been warning the people to change their ways and use less water.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-nile_height" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-nile_height-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="diagrams/nile_height.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-nile_height-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.1: Height of the Nile River Over Half of a Century
</figcaption>
</figure>
</div>
</div>
</div>
<p>Let’s look at <a href="#fig-nile_long" class="quarto-xref">Figure&nbsp;<span>14.2</span></a> which represents the data over an even longer period. What now would you say about the height of the Nile? Clearly the “threat” was non-existent, and only appeared threatening because the time span represented by the data was too short. The point of this display is that looking at too-short a segment of experience frequently leads us into error. And “too short” may be as long as a century.</p>
<div id="fig-nile_long" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-nile_long-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/nile_levels.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-nile_long-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.2: Variations in the height of Nile Flood in centimeters. The sloping line indicates the secular raising of the bed of the Nile by deposition of silt. From <span class="citation" data-cites="brooks1928periodicities">Brooks (<a href="references.html#ref-brooks1928periodicities" role="doc-biblioref">1928</a>)</span>
</figcaption>
</figure>
</div>
<p>Another example is the price of mercury, which is representative of all metals. <a href="#fig-mercury_prediction" class="quarto-xref">Figure&nbsp;<span>14.3</span></a> shows a forecast made in 1976 by natural-scientist Earl Cook <span class="citation" data-cites="cook1976limits">(<a href="references.html#ref-cook1976limits" role="doc-biblioref">1976</a>)</span>. He combined a then-recent upturn in prices with the notion that there is a finite amount of mercury on the earth’s surface, plus the mathematical charm of plotting a second-degree polynomial with the computer. <a href="#fig-mercury_reserves" class="quarto-xref">Figure&nbsp;<span>14.4</span></a> and <a href="#fig-mercury_price_indexes" class="quarto-xref">Figure&nbsp;<span>14.5</span></a> show how the forecast was almost immediately falsified, and the price continued its long-run decline.</p>
<div id="fig-mercury_prediction" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mercury_prediction-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/mercury_prices.png" class="img-fluid figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mercury_prediction-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.3: The Price of Mercury from <span class="citation" data-cites="cook1976limits">Cook (<a href="references.html#ref-cook1976limits" role="doc-biblioref">1976</a>)</span>
</figcaption>
</figure>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-mercury_reserves" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mercury_reserves-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="diagrams/mercury_reserves.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mercury_reserves-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.4: Mercury Reserves, 1950-1990
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-mercury_price_indexes" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-mercury_price_indexes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="diagrams/mercury_price_indexes.svg" class="img-fluid quarto-figure quarto-figure-center figure-img" style="width:70.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-mercury_price_indexes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;14.5: Mercury Price Indexes, 1950-1990
</figcaption>
</figure>
</div>
</div>
</div>
<p>Lack of sound statistical intuition about variability can lead to manipulation of the public being by unscrupulous persons. Commodity funds sellers use a device of this sort to make their results look good (<em>The Washington Post</em>, Sep 28, 1987, p.&nbsp;71). Some individual commodity traders inevitably do well in their private trading, just by chance. A firm then hires one of them, builds a public fund around him, and claims the private record for the fund’s own history. But of course the private record has no predictive power, any more than does the record of someone who happened to get ten heads in a row flipping coins.</p>
<p>How can we avoid falling into such traps? It is best to look at the longest possible sweep of history. That is, use the largest possible sample of observations to avoid sampling error. For copper we have data going back to the 18th century B.C. In Babylonia, over a period of 1000 years, the price of iron fell to one fifth of what it was under Hammurabi (almost 4000 years ago), and the price of copper then cost about a thousand times its current price in the U.S., relative to wages. So the inevitable short-run increases in price should be considered in this long-run context to avoid drawing unsound conclusions due to small-sample variability.</p>
<p>Proof that it is sound judgment to rely on the longest possible series is given by the accuracy of predictions one would have made in the past. In the context of copper, mercury, and other raw materials, we can refer to a sample of years in the past, and from those years imagine ourselves forecasting the following year. If you had bet every time that prices would go down in consonance with the long-run trend, you would have been a big winner on average.</p>
</section>
<section id="regression-to-the-mean" class="level2" data-number="14.2">
<h2 data-number="14.2" class="anchored" data-anchor-id="regression-to-the-mean"><span class="header-section-number">14.2</span> Regression to the mean</h2>
<blockquote class="blockquote">
<p>UP, DOWN “The Dodgers demoted last year’s NL rookie of the year, OF Todd Hollandsworth (.237, 1 HR, 18 RBI) to AAA Albuquerque...” (Item in <em>Washington Post</em> , 6/14/97)</p>
</blockquote>
<p>It is a well-known fact that the Rookie of the Year in a sport such as baseball seldom has as outstanding a season in their sophomore year. Why is this so? Let’s use the knowledge we have acquired of probability and simulation to explain this phenomenon.</p>
<p>The matter at hand might be thought of as a problem in pure probability — if one simply asks about the chance that a given player (the Rookie of the Year) will repeat. Or it could be considered a problem in statistics, as discussed in coming chapters. Let’s consider the matter in the context of baseball.</p>
<p>Imagine 10 mechanical “ball players,” each a machine that has three white balls (hits) and 7 black balls. Every time the machine goes to bat, you take a ball out of the machine, look to see if it is a hit or an out, and put it back. For each “ball player” you do this 100 times. One of them is going to do better than the others, and that one becomes the Rookie of the Year. See <a href="#tbl-rookie-seasons" class="quarto-xref">Table&nbsp;<span>14.2</span></a>.</p>
<div id="tbl-rookie-seasons" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-rookie-seasons-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;14.2: Rookie Seasons (100 at bats)
</figcaption>
<div aria-describedby="tbl-rookie-seasons-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th># of Hits</th>
<th>Batting Average</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>32</td>
<td>.320</td>
</tr>
<tr class="even">
<td>34</td>
<td>.340</td>
</tr>
<tr class="odd">
<td>33</td>
<td>.330</td>
</tr>
<tr class="even">
<td>30</td>
<td>.300</td>
</tr>
<tr class="odd">
<td>35</td>
<td>.350</td>
</tr>
<tr class="even">
<td>33</td>
<td>.330</td>
</tr>
<tr class="odd">
<td>30</td>
<td>.300</td>
</tr>
<tr class="even">
<td>31</td>
<td>.310</td>
</tr>
<tr class="odd">
<td>28</td>
<td>.280</td>
</tr>
<tr class="even">
<td>25</td>
<td>.250</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>Would you now expect that the player who happened to be the best among the top ten in the first year to again be the best among the top ten in the next year, also? The sports writers do. But of course this seldom happens. The Rookie of the Year in major-league baseball seldom has as outstanding a season in their sophomore year as in their rookie year. You can expect them to do better than the average of all sophomores, but not necessarily better than all of the rest of the group of talented players who are now sophomores. (Please notice that we are not saying that there is no long-run difference among the top ten rookies. But suppose there is. <a href="#tbl-true-rookie" class="quarto-xref">Table&nbsp;<span>14.3</span></a> shows the season’s performance for ten batters of differing performances).</p>
<div id="tbl-true-rookie" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-true-rookie-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;14.3: Simulated season’s performance for 10 batters of differing “true” averages
</figcaption>
<div aria-describedby="tbl-true-rookie-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>“True”</th>
<th>Rookie</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>.270</td>
<td>.340</td>
</tr>
<tr class="even">
<td>.270</td>
<td>.240</td>
</tr>
<tr class="odd">
<td>.280</td>
<td>.330</td>
</tr>
<tr class="even">
<td>.280</td>
<td>.300</td>
</tr>
<tr class="odd">
<td>.300</td>
<td>.280</td>
</tr>
<tr class="even">
<td>.300</td>
<td>.420</td>
</tr>
<tr class="odd">
<td>.320</td>
<td>.340</td>
</tr>
<tr class="even">
<td>.320</td>
<td>.350</td>
</tr>
<tr class="odd">
<td>.330</td>
<td>.260</td>
</tr>
<tr class="even">
<td>.330</td>
<td>.330</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>We see from <a href="#tbl-true-rookie" class="quarto-xref">Table&nbsp;<span>14.3</span></a> that we have ten batters whose “true” batting averages range from .270 to .330. Their rookie year performance (400 at bats), simulated on the basis of their “true”average is on the right. Which one is the rookie of the year? It’s #6, who hit .420 during the rookie session. Will they do as well next year? Not likely — their “true” average is only .300.</p>
<div class="notebook" name="sampling_variability" title="Experiment in sampling variability">
<p>Start of <code>sampling_variability</code> notebook</p>
<div class="nb-links">
<a class="notebook-link" href="notebooks/sampling_variability.Rmd">Download notebook</a>
<a class="interact-button" href="https://resampling-stats.github.io/r-book/interact/lab/index.html?path=sampling_variability.ipynb">Interact</a>
</div>

<p>Try generating some rookie “seasons” yourself with the following commands, ranging the batter’s “true” performance by changing the value of <code>p_hit</code> (the probability of a hit).</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate a rookie season of 400 at-bats.</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># You might try changing the value below and rerunning.</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># This is the true (long-run) probability of a hit for this batter.</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>p_hit <span class="ot">&lt;-</span> <span class="fl">0.4</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">message</span>(<span class="st">'True average is: '</span>, p_hit)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>True average is: 0.4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We resample _with_ replacement here; the chances of a hit do not change</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># From at-bat to at-bat.</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>at_bats <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">'Hit'</span>, <span class="st">'Out'</span>), <span class="at">prob=</span><span class="fu">c</span>(p_hit, <span class="dv">1</span> <span class="sc">-</span> p_hit), <span class="at">size=</span><span class="dv">400</span>, <span class="at">replace=</span><span class="cn">TRUE</span>)</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>simulated_average <span class="ot">&lt;-</span> <span class="fu">sum</span>(at_bats <span class="sc">==</span> <span class="st">'Hit'</span>) <span class="sc">/</span> <span class="dv">400</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Show the result</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="fu">message</span>(<span class="st">'Simulated average is: '</span>, simulated_average)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Simulated average is: 0.445</code></pre>
</div>
</div>
<p>Simulate a set of 10 or 20 such rookie seasons, and look at the one who did best. How did their rookie season compare to their “true” average?</p>
<p>End of <code>sampling_variability</code> notebook</p>
</div>
<p>The explanation is the presence of <em>variability</em> . And lack of recognition of the role of variability is at the heart of much fallacious reasoning. Being alert to the role of variability is crucial.</p>
<p>Or consider the example of having a superb meal at a restaurant — the best meal you have ever eaten. That fantastic meal is almost surely the combination of the restaurant being better than average, plus a lucky night for the chef and the dish you ordered. The next time you return you can expect a meal better than average, because the restaurant is better than average in the long run. But the meal probably will be less good than the superb one you had the first time, because there is no reason to believe that the chef will get so lucky again and that the same sort of variability will happen this time.</p>
<p>These examples illustrate the concept of “regression to the mean” — a confusingly-titled and very subtle effect caused by variability in results among successive samples drawn from the same population. This phenomenon was given its title more than a century ago by Francis Galton, one of the great founders of modern statistics, when at first he thought that the height of the human species was becoming more uniform, after he noticed that the children of the tallest and shortest parents usually are closer to the average of all people than their parents are. But later he discovered his fallacy — that the variability in heights of children of quite short and quite tall parents also causes some people to be even more exceptionally tall or short than their parents. So the spread in heights among humans remains much the same from generation to generation; there is no “regression to the mean.” The heart of the matter is that any exceptional observed case in a group is likely to be the result of two forces — a) an <em>underlying propensity</em> to differ from the average in one direction or the other, plus b) <em>some chance sampling variability</em> that happens (in the observed case) to push even further in the exceptional direction.</p>
<p>A similar phenomenon arises in direct-mail marketing. When a firm tests many small samples of many lists of names and then focuses its mass mailings on the lists that performed best in the tests, the full list “rollouts” usually do not perform as well as the samples did in the initial tests. It took many years before mail-order experts (see especially <span class="citation" data-cites="burnett1988complete">(<a href="references.html#ref-burnett1988complete" role="doc-biblioref">Burnett 1988</a>)</span>) finally understood that regression to the mean <em>inevitably</em> causes an important part of the dropoff from sample to rollout observed in the set of lists that give the very best results in a multi-list test.</p>
<p>The larger the test samples, the less the dropoff, of course, because larger samples reduce variability in results. But larger samples risk more money. So the test-sample-size decision for the marketer inevitably is a trade-off between accuracy and cost.</p>
<p>And one last amusing example: After I (JLS) lectured to the class on this material, the student who had gotten the best grade on the first mid-term exam came up after class and said: “Does that mean that on the second mid-term I should expect to do well but not the best in the class?” And that’s exactly what happened: He had the second-best score in the class on the next midterm.</p>
<p>A related problem arises when one conducts multiple tests, as when testing thousands of drugs for therapeutic value. Some of the drugs may appear to have a therapeutic effect just by chance. We will discuss this problem later when discussing hypothesis testing.</p>
</section>
<section id="summary-and-conclusion" class="level2" data-number="14.3">
<h2 data-number="14.3" class="anchored" data-anchor-id="summary-and-conclusion"><span class="header-section-number">14.3</span> Summary and conclusion</h2>
<p>The heart of statistics is clear thinking. One of the key elements in being a clear thinker is to have a sound gut understanding of statistical processes and variability. This chapter amplifies this point.</p>
<p>A great benefit to using simulations rather than formulas to deal with problems in probability and statistics is that the presence and importance of variability becomes manifest in the course of the simulation work.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-brooks1928periodicities" class="csl-entry" role="listitem">
Brooks, Charles Ernest Pelham. 1928. <span>“Periodicities in the Nile Floods.”</span> <em>Memoirs of the Royal Meteorological Society</em> 2 (12): 9--26. <a href="https://www.rmets.org/sites/default/files/papers/brooksmem2-12.pdf">https://www.rmets.org/sites/default/files/papers/brooksmem2-12.pdf</a>.
</div>
<div id="ref-burnett1988complete" class="csl-entry" role="listitem">
Burnett, Ed. 1988. <em>The Complete Direct Mail List Handbook: Everything You Need to Know about Lists and How to Use Them for Greater Profit</em>. Englewood Cliffs, New Jersey: Prentice Hall. <a href="https://archive.org/details/completedirectma00burn">https://archive.org/details/completedirectma00burn</a>.
</div>
<div id="ref-cook1976limits" class="csl-entry" role="listitem">
Cook, Earl. 1976. <span>“Limits to Exploitation of Nonrenewable Resources.”</span> <em>Science</em> 191 (4228): 677–82. <a href="https://www.jstor.org/stable/pdf/1741483.pdf">https://www.jstor.org/stable/pdf/1741483.pdf</a>.
</div>
<div id="ref-gilovich1985hot" class="csl-entry" role="listitem">
Gilovich, Thomas, Robert Vallone, and Amos Tversky. 1985. <span>“The Hot Hand in Basketball: On the Misperception of Random Sequences.”</span> <em>Cognitive Psychology</em> 17 (3): 295–314. <a href="https://www.joelvelasco.net/teaching/122/Gilo.Vallone.Tversky.pdf">https://www.joelvelasco.net/teaching/122/Gilo.Vallone.Tversky.pdf</a>.
</div>
</div>
</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>We are simplifying here; the Hot-Hand is a controversial topic, and it has its own Wikipedia page with information and discussion: <a href="https://en.wikipedia.org/wiki/Hot_hand" class="uri">https://en.wikipedia.org/wiki/Hot_hand</a>. It may be overstating to say the effect does not exist, but if it does exist, the effect is much smaller than most sports fans believe it to be.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>See Simon’s description of these experiments in <a href="https://www.washingtonpost.com/archive/opinions/1987/08/09/batters-slump-other-illusions/72964746-cd59-4e0b-a941-e1cdfca917d6/">Batter’s slump and other illusions</a>, Washington Post, August 9th, 1987.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./probability_theory_4_finite.html" class="pagination-link" aria-label="Probability Theory, Part 4: Estimating Probabilities from Finite Universes">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Probability Theory, Part 4: Estimating Probabilities from Finite Universes</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./monte_carlo.html" class="pagination-link" aria-label="The Procedures of Monte Carlo Simulation (and Resampling)">
        <span class="nav-page-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">The Procedures of Monte Carlo Simulation (and Resampling)</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>