<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.51">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Resampling statistics - 24&nbsp; The Statistics of Hypothesis-Testing With Measured Data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./testing_procedures.html" rel="next">
<link href="./testing_counts_2.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<script type="text/javascript">
  $(document).ready(function() {
    $("table").addClass('lightable-paper lightable-striped lightable-hover')
  });
</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="style.css">
<link rel="stylesheet" href="font-awesome.min.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./testing_measured.html"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">The Statistics of Hypothesis-Testing With Measured Data</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Resampling statistics</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R edition</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface_third.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface to the third edition</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface_second.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface to the second edition</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./resampling_method.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The resampling method</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./what_is_probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">What is probability?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./about_technology.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Introducing R and the RStudio notebook</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./resampling_with_code.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Resampling with code</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sampling_tools.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Tools for samples and sampling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./resampling_with_code2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">More resampling with code</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability_theory_1a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Probability Theory, Part 1</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability_theory_1b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Probability Theory Part I (continued)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./more_sampling_tools.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Two puzzles and more tools</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability_theory_2_compound.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Probability Theory, Part 2: Compound Probability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability_theory_3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Probability Theory, Part 3</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability_theory_4_finite.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Probability Theory, Part 4: Estimating Probabilities from Finite Universes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sampling_variability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">On Variability in Sampling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./monte_carlo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">The Procedures of Monte Carlo Simulation (and Resampling)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./standard_scores.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Ranks, Quantiles and Standard Scores</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference_ideas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">The Basic Ideas in Statistical Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Introduction to Statistical Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./point_estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Point Estimation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./framing_questions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Framing Statistical Questions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./testing_counts_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Hypothesis-Testing with Counted Data, Part 1</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./significance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">The Concept of Statistical Significance in Testing Hypotheses</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./testing_counts_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">The Statistics of Hypothesis-Testing with Counted Data, Part 2</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./testing_measured.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">The Statistics of Hypothesis-Testing With Measured Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./testing_procedures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">General Procedures for Testing Hypotheses</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./confidence_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Confidence Intervals, Part 1: Assessing the Accuracy of Samples</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./confidence_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Confidence Intervals, Part 2: The Two Approaches to Estimating Confidence Intervals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./reliability_average.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Some Last Words About the Reliability of Sample Averages</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./correlation_causation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Correlation and Causation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./how_big_sample.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">How Large a Sample?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bayes_simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Bayesian Analysis by Simulation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./exercise_solutions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Exercise Solutions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./acknowlegements.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Acknowledgements</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./technical_note.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Technical Note to the Professional Reader</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#sec-pig-rations-measured" id="toc-sec-pig-rations-measured" class="nav-link active" data-scroll-target="#sec-pig-rations-measured"><span class="header-section-number">24.0.1</span> Example: The Pig Rations Still Once Again, Using Measured Data</a></li>
  <li><a href="#sec-liquor-public-measured" id="toc-sec-liquor-public-measured" class="nav-link" data-scroll-target="#sec-liquor-public-measured"><span class="header-section-number">24.0.2</span> Example: Is There a Difference in Liquor Prices Between State-Run and Privately-Run Systems?</a></li>
  <li><a href="#sec-eg-bootstrap-sampling" id="toc-sec-eg-bootstrap-sampling" class="nav-link" data-scroll-target="#sec-eg-bootstrap-sampling"><span class="header-section-number">24.0.3</span> Example: Bootstrap Sampling with Replacement</a></li>
  <li><a href="#differences-among-four-means" id="toc-differences-among-four-means" class="nav-link" data-scroll-target="#differences-among-four-means"><span class="header-section-number">24.1</span> Differences among four means</a></li>
  <li><a href="#using-squared-differences" id="toc-using-squared-differences" class="nav-link" data-scroll-target="#using-squared-differences"><span class="header-section-number">24.2</span> Using Squared Differences</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"><span class="header-section-number">24.3</span> Exercises</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-testing-measured" class="quarto-section-identifier"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">The Statistics of Hypothesis-Testing With Measured Data</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Draft page partially ported from original PDF
</div>
</div>
<div class="callout-body-container callout-body">
<p>This page is an automated and partial import from the <a href="https://resample.com/content/text/22-Chap-18.pdf">original second-edition PDF</a>.</p>
<p>We are in the process of updating this page for formatting, and porting any code from the original <a href="http://www.statistics101.net">RESAMPLING-STATS language</a> to Python and R.</p>
<p>Feel free to read this version for the sense, but expect there to be multiple issues with formatting.</p>
<p>We will remove this warning when the page has adequate formatting, and we have ported the code.</p>
</div>
</div>
<!---
Discussion here of dispersion - have we discussed this before?

Methods of estimating dispersion.
-->
<p><a href="testing_counts_1.html" class="quarto-xref"><span>Chapter&nbsp;21</span></a> and <a href="point_estimation.html" class="quarto-xref"><span>Chapter&nbsp;19</span></a> discussed testing a hypothesis with data that either arrive in dichotomized (yes-no) form, or come as data in situations where it is convenient to dichotomize. We next consider hypothesis testing using measured data. Conventional statistical practice employs such devices as the “t-test” and “analysis of variance.” In contrast to those complex devices, the resampling method does not differ greatly from what has been discussed in previous chapters.</p>
<section id="sec-pig-rations-measured" class="level3" data-number="24.0.1">
<h3 data-number="24.0.1" class="anchored" data-anchor-id="sec-pig-rations-measured"><span class="header-section-number">24.0.1</span> Example: The Pig Rations Still Once Again, Using Measured Data</h3>
<p><strong>Testing for the Difference Between Means of Two Equal-Sized Samples of Measured-Data Observations) (Program “Pigs3”)</strong></p>
<p>Let us now treat the pig-food problem without converting the quantitative data into qualitative data, because a conversion always loses information.</p>
<p>The term “lose information” can be understood intuitively. Consider two sets of three sacks of corn. Set A includes sacks containing, respectively, one pound, two pounds, and three pounds. Set B includes sacks of one pound, two pounds, and a hundred pounds. If we <em>rank</em> the sacks by weight, the two sets can no longer be distinguished. The one-pound and two-pound sacks have ranks one and two in both cases, and their relative places in their sets are the same. But if we know <em>not only</em> that the one-pound sack is the smallest of its set and the three-pound or hundred-pound sack is the largest, but <em>also</em> that the largest sack is three pounds (or a hundred pounds), we have more information about a set than if we only know the ranks of its sacks.</p>
<p>Rank data are also known as “ordinal” data, whereas data measured in (say) pounds are known as “cardinal” data. Even though converting from cardinal (measured) to ordinal (ranked) data loses information, the conversion may increase convenience, and may therefore be worth doing in some cases.</p>
<p><img src="images/22-Chap-18_000.png" class="img-fluid"></p>
<p>We begin a measured-data procedure by noting that if the two pig foods are the same, then each of the observed weight gains came from the <em>same benchmark universe</em> . This is the basic tactic in our statistical strategy. That is, if the two foods came from the same universe, <em>our best guess about the composition of that universe is that it includes weight gains just like the twenty-four we have observed</em> , and in the same proportions, because that is all the information that we have about the universe; this is the bootstrap method. Since ours is (by definition) a sample from an infinite (or at least, a very large) universe of possible weight gains, we assume that there are <em>many</em> weight gains in the universe just like the ones we have observed, in the same proportion as we have observed them. For example, we assume that 2/24 of the universe is composed of 34-pound weight gains, as seen in Figure 18-1:</p>
<p><strong>Figure 18-1</strong></p>
<p>We recognize, of course, that weight gains other than the exact ones we observed certainly would occur in repeated experiments. And if we thought it reasonable to do so, we could assume that the “distribution” of the weight gains would follow a regular “smooth” shape such as Figure 18-2. But deciding just how to draw Figure 18-2 from the data in Figure 18-1 requires that we make arbitrary assumptions about unknown conditions. And if we were to draw Figure 18-2 in a form that would be sufficiently regular for conventional mathematical analysis, we might have to make some <em>very strong</em> assumptions going far beyond the observed data.</p>
<p>Drawing a smooth curve such as Figure 18-2 from the raw data in Figure 18-1 might be satisfactory — if done with wisdom and good judgment. But there is no necessity to draw such a smooth curve, in this case or in most cases. We can proceed by assuming simply that the benchmark universe — the universe to which we shall compare our samples, conventionally</p>
<p>Relative Probability</p>
<p>called the “null” or “hypothetical” universe — is composed only of elements similar to the observations we have in hand. We thereby lose no efficiency and avoid making unsound assumptions.</p>
<p><img src="images/22-Chap-18_001.png" class="img-fluid"></p>
<p>Size of Weight Gain, 30.2 = Mean</p>
<p><strong>Figure 18-2</strong></p>
<p>To carry out our procedure in practice: 1) Write down each of the twenty-four weight gains on a blank index card. We then have one card each for 31, 34, 29, 26, and so on. 2) Shuffle the twenty-four cards thoroughly, and pick one card. 3) Record the weight gain, and replace the card. (Recall that we are treating the weight gains as if they come from an infinite universe — that is, as if the probability of selecting any amount is the same no matter which others are selected randomly. Another way to say this is to state that each selection is independent of each other selection. If we did not replace the card before selecting the next weight gain, the selections would no longer be independent. See <a href="probability_theory_2_compound.html" class="quarto-xref"><span>Chapter&nbsp;11</span></a> for further discussion of this issue.) 4) Repeat this process until you have made two sets of 12 observations. 5) Call the first hand “food A” and the second hand “food B.” Determine the average weight gain for the two hands, and record it as in Table 18-1. Repeat this procedure many times.</p>
<p>In operational steps:</p>
<p><strong>Step 1.</strong> Write down each observed weight gain on a card, e.g.&nbsp;31, 34, 29...</p>
<p><strong>Step 2.</strong> Shuffle and deal a card.</p>
<p><strong>Step 3.</strong> Record the weight and replace the card.</p>
<p><strong>Step 4.</strong> Repeat steps 2 and 3 eleven more times; call this group A.</p>
<p><strong>Step 5.</strong> Repeat steps 2-3 another twelve times; call this group B.</p>
<p><strong>Step 6.</strong> Calculate the mean weight gain of each group.</p>
<p><strong>Step 7.</strong> Subtract the mean of group A from the mean of group B and record. If larger (more positive) than 3.16 (the difference between the observed means) or more negative than -3.16, record “more.” Otherwise record “less.”</p>
<p><strong>Step 8.</strong> Repeat this procedure perhaps fifty times, and calculate the proportion “more.” This estimates the probability sought.</p>
<p>In none of the first ten simulated trials did the difference in the means of the random hands exceed the observed difference (3.16 pounds, in the top line in the table) between foods A and B. (The difference between group <em>totals</em> tells the same story and is faster, requiring no division calculations.)</p>
<p>In the old days before a computer was always easily available, I would quit making trials at such a point, confident that a difference in means as great as observed is not likely to happen by chance. (Using the convenient “multiplication rule” described in <a href="probability_theory_1b.html" class="quarto-xref"><span>Chapter&nbsp;9</span></a>, we can estimate the probability of such an occurrence happening by chance in 10 successive trials as <span class="math inline">\(\frac{1}{2} * \frac{1}{2} * \frac{1}{2} ... = \frac{1}{2}^{10} = 1/1024 \approx .001\)</span> = .1 percent, a small chance indeed.) Nevertheless, let us press on to do 50 trials.</p>
<p>Table 18-1</p>
<table class="table">
<colgroup>
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 19%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>Trial #</strong></td>
<td><strong>Mean of First 12 Observation s (First Hand)</strong></td>
<td><strong>Mean of Second 12 Observation s (Second Hand)</strong></td>
<td><p><strong>Differenc e Greater or</strong></p>
<p><strong>Less Than Observed Differenc</strong></p></td>
<td></td>
</tr>
<tr class="even">
<td>Observed</td>
<td>382 / 12=31.83</td>
<td>344 / 12=28.67</td>
<td>3.16</td>
<td></td>
</tr>
<tr class="odd">
<td>1</td>
<td>368 / 12=30.67</td>
<td>357 / 12=29.75</td>
<td>.87</td>
<td>Less</td>
</tr>
<tr class="even">
<td>2</td>
<td>364 / 12=30.33</td>
<td>361 / 12=30.08</td>
<td>.25</td>
<td>Less</td>
</tr>
<tr class="odd">
<td>3</td>
<td>352 / 12=29.33</td>
<td>373 / 12=31.08</td>
<td>(1.75)</td>
<td>Less</td>
</tr>
<tr class="even">
<td>4</td>
<td>378 / 12=31.50</td>
<td>347 / 12=28.92</td>
<td>2.58</td>
<td>Less</td>
</tr>
<tr class="odd">
<td>5</td>
<td>365 / 12=30.42</td>
<td>360 / 12=30.00</td>
<td>.42</td>
<td>Less</td>
</tr>
<tr class="even">
<td>6</td>
<td>352 / 12=29.33</td>
<td>373 / 12=31.08</td>
<td>(1.75)</td>
<td>Less</td>
</tr>
<tr class="odd">
<td>7</td>
<td>355 / 12=29.58</td>
<td>370 / 12=30.83</td>
<td>(1.25)</td>
<td>Less</td>
</tr>
<tr class="even">
<td>8</td>
<td>366 / 12=30.50</td>
<td>359 / 12=29.92</td>
<td>.58</td>
<td>Less</td>
</tr>
<tr class="odd">
<td>9</td>
<td>360 / 12=30.00</td>
<td>365 / 12=30.42</td>
<td>(.42)</td>
<td>Less</td>
</tr>
<tr class="even">
<td>10</td>
<td>355 / 12=29.58</td>
<td>370 / 12=30.83</td>
<td>(1.25)</td>
<td>Less</td>
</tr>
<tr class="odd">
<td>11</td>
<td>359 / 12=29.92</td>
<td>366 / 12=30.50</td>
<td>(.58)</td>
<td>Less</td>
</tr>
<tr class="even">
<td>12</td>
<td>369 / 12=30.75</td>
<td>356 / 12=29.67</td>
<td>1.08</td>
<td>”</td>
</tr>
</tbody>
</table>
<p><strong>Results of Fifty Random Samples for the Problem “PIGS3”</strong></p>
<p><strong>e</strong></p>
<table class="table">
<colgroup>
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 19%">
<col style="width: 19%">
</colgroup>
<tbody>
<tr class="odd">
<td><strong>Trial #</strong></td>
<td><strong>Mean of First 12 Observation s (First Hand)</strong></td>
<td><strong>Mean of Second 12 Observation s (Second Hand)</strong></td>
<td><p><strong>Differenc e Greater or</strong></p>
<p><strong>Less Than Observed Differenc</strong></p></td>
<td></td>
</tr>
<tr class="even">
<td>Observed</td>
<td>382 / 12=31.83</td>
<td>344 / 12=28.67</td>
<td>3.16</td>
<td></td>
</tr>
<tr class="odd">
<td>13</td>
<td>360 / 12=30.00</td>
<td>365 / 12=30.42</td>
<td>(.42)</td>
<td>Less</td>
</tr>
<tr class="even">
<td>14</td>
<td>377 / 12=31.42</td>
<td>348 / 12=29.00</td>
<td>2.42</td>
<td>Less</td>
</tr>
<tr class="odd">
<td>15</td>
<td>365 / 12=30.42</td>
<td>360 / 12=30.00</td>
<td>.42</td>
<td>Less</td>
</tr>
<tr class="even">
<td>16</td>
<td>364 / 12=30.33</td>
<td>361 / 12=30.08</td>
<td>.25</td>
<td>Less</td>
</tr>
<tr class="odd">
<td>17</td>
<td>363 / 12=30.25</td>
<td>362 / 12=30.17</td>
<td>.08</td>
<td>Less</td>
</tr>
<tr class="even">
<td>18</td>
<td>365 / 12=30.42</td>
<td>360 / 12=30.00</td>
<td>.42</td>
<td>Less</td>
</tr>
<tr class="odd">
<td>19</td>
<td>369 / 12=30.75</td>
<td>356 / 12=29.67</td>
<td>1.08</td>
<td>Less</td>
</tr>
<tr class="even">
<td>20</td>
<td>369 / 12=30.75</td>
<td>356 / 12=29.67</td>
<td>1.08</td>
<td>Less</td>
</tr>
<tr class="odd">
<td>21</td>
<td>369 / 12=30.75</td>
<td>356 / 12=29.67</td>
<td>1.08</td>
<td>Less</td>
</tr>
<tr class="even">
<td>22</td>
<td>364 / 12=30.33</td>
<td>361 / 12=30.08</td>
<td>.25</td>
<td>Less</td>
</tr>
<tr class="odd">
<td>23</td>
<td>363 / 12=30.25</td>
<td>362 / 12=30.17</td>
<td>.08</td>
<td>Less</td>
</tr>
<tr class="even">
<td>24</td>
<td>363 / 12=30.25</td>
<td>362 / 12=30.17</td>
<td>.08</td>
<td>Less</td>
</tr>
<tr class="odd">
<td>25</td>
<td>364 / 12=30.33</td>
<td>361 / 12=30.08</td>
<td>.25</td>
<td>Less</td>
</tr>
<tr class="even">
<td>26</td>
<td>359 / 12=29.92</td>
<td>366 / 12=30.50</td>
<td>(.58)</td>
<td>Less</td>
</tr>
<tr class="odd">
<td>27</td>
<td>362 / 12=30.17</td>
<td>363 / 12=30.25</td>
<td>(.08)</td>
<td>Less</td>
</tr>
<tr class="even">
<td>28</td>
<td>362 / 12=30.17</td>
<td>363 / 12=30.25</td>
<td>(.08)</td>
<td>Less</td>
</tr>
<tr class="odd">
<td>29</td>
<td>373 / 12=31.08</td>
<td>352 / 12=29.33</td>
<td>1.75</td>
<td>Less</td>
</tr>
<tr class="even">
<td>30</td>
<td>367 / 12=30.58</td>
<td>358 / 12=29.83</td>
<td>.75</td>
<td>Less</td>
</tr>
<tr class="odd">
<td>31</td>
<td>376 / 12=31.33</td>
<td>349 / 12=29.08</td>
<td>2.25</td>
<td>Less</td>
</tr>
<tr class="even">
<td>32</td>
<td>365 / 12=30.42</td>
<td>360 / 12=30.00</td>
<td>.42</td>
<td>Less</td>
</tr>
<tr class="odd">
<td>33</td>
<td>357 / 12=29.75</td>
<td>368 / 12=30.67</td>
<td>(1.42)</td>
<td>Less</td>
</tr>
<tr class="even">
<td>34</td>
<td>349 / 12=29.08</td>
<td>376 / 12=31.33</td>
<td>2.25</td>
<td>Less</td>
</tr>
<tr class="odd">
<td>35</td>
<td>356 / 12=29.67</td>
<td>396 / 12=30.75</td>
<td>(1.08)</td>
<td>Less</td>
</tr>
<tr class="even">
<td>36</td>
<td>359 / 12=29.92</td>
<td>366 / 12=30.50</td>
<td>(.58)</td>
<td>Less</td>
</tr>
<tr class="odd">
<td>37</td>
<td>372 / 12=31.00</td>
<td>353 / 12=29.42</td>
<td>1.58</td>
<td>Less</td>
</tr>
<tr class="even">
<td>38</td>
<td>368 / 12=30.67</td>
<td>357 / 12=29.75</td>
<td>.92</td>
<td>Less</td>
</tr>
<tr class="odd">
<td>39</td>
<td>344 / 12=28.67</td>
<td>382 / 12=31.81</td>
<td>(3.16)</td>
<td>Equal</td>
</tr>
<tr class="even">
<td>40</td>
<td>365 / 12=30.42</td>
<td>360 / 12=30.00</td>
<td>.42</td>
<td>Less</td>
</tr>
<tr class="odd">
<td>41</td>
<td>375 / 12=31.25</td>
<td>350 / 12=29.17</td>
<td>2.08</td>
<td>Less</td>
</tr>
<tr class="even">
<td>42</td>
<td>353 / 12=29.42</td>
<td>372 / 12=31.00</td>
<td>(1.58)</td>
<td>Less</td>
</tr>
<tr class="odd">
<td>43</td>
<td>357 / 12=29.75</td>
<td>368 / 12=30.67</td>
<td>(.92)</td>
<td>Less</td>
</tr>
<tr class="even">
<td>44</td>
<td>363 / 12=30.25</td>
<td>362 / 12=30.17</td>
<td>.08</td>
<td>Less</td>
</tr>
<tr class="odd">
<td>45</td>
<td>353 / 12=29.42</td>
<td>372 / 12=31.00</td>
<td>(1.58)</td>
<td>Less</td>
</tr>
<tr class="even">
<td>46</td>
<td>354 / 12=29.50</td>
<td>371 / 12=30.92</td>
<td>(1.42)</td>
<td>Less</td>
</tr>
<tr class="odd">
<td>47</td>
<td>353 / 12=29.42</td>
<td>372 / 12=31.00</td>
<td>(1.58)</td>
<td>Less</td>
</tr>
<tr class="even">
<td>48</td>
<td>366 / 12=30.50</td>
<td>350 / 12=29.92</td>
<td>.58</td>
<td>Less</td>
</tr>
<tr class="odd">
<td>49</td>
<td>364 / 12=30.53</td>
<td>361 / 12=30.08</td>
<td>.25</td>
<td>Less</td>
</tr>
<tr class="even">
<td>50</td>
<td>370 / 12=30.83</td>
<td>355 / 12=29.58</td>
<td>1.25</td>
<td>Less</td>
</tr>
</tbody>
</table>
<p><strong>Table 18-1</strong> <strong><em>(continued)</em></strong></p>
<p><strong>e</strong></p>
<p>Table 18-1 shows fifty trials of which only one (the thirty-ninth) is as “far out” as the observed samples. These data give us an estimate of the probability that, if the two foods come from the same universe, a difference this great or greater would occur just by chance. (Compare this 2 percent estimate with the probability of roughly 1 percent estimated with the conventional <em>t</em> test — a “significance level” of 1 percent.) On the average, the test described in this section yields a significance level as high as such mathematical-probability tests as the <em>t</em> test — that is, it is just as efficient — though the tests described in Examples 15-6 and 17-1 are likely to be less efficient because they convert measured data to ranked or classified data. <a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<p>It is <em>not</em> appropriate to say that these data give us an estimate of the probability that the foods “do not come” from the same universe. This is because we can <em>never</em> state a probability that a sample came from a given universe unless the alternatives are fully specified in advance.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a></p>
<p>This example also illustrates how the <em>dispersion within samples</em> affects the difficulty of finding out whether the samples differ from each other. For example, the average weight gain for food A was 32 pounds, versus 29 pounds for food B. If <em>all</em> the food A-fed pigs had gained weight within a range of say 29.9 and 30.1 pounds, and if all the food B-fed pigs had gained weight within a range of 28.9 and 29.1 pounds — that is, if the highest weight gain in food B had been lower than the lowest weight gain in food A — then there would be no question that food A is better, and even fewer observations would have made this statistically conclusive. Variation (dispersion) is thus of great importance in statistics and in the social sciences. The larger the dispersion among the observations <em>within</em> the samples, the larger the <em>sample size</em> necessary to make a conclusive comparison between two groups or reliable estimates of summarization statistics. (The dispersion might be measured by the mean absolute deviation (the average absolute difference between the mean and the individual observations, treating both plus and minus differences as positive), the variance (the average <em>squared</em> difference between the mean and the observations), the standard deviation (the square root of the variance), the range (the difference between the smallest and largest observations), or some other device.)</p>
<!---
Lots about dispersion here.  Needs better introduction?
-->
<p>If you are performing your tests by hand rather than using a computer (a good exercise even nowadays when computers are so accessible), you might prefer to work with the median instead of the mean, because the median requires less computation. (The median also has the advantage of being less influenced by a single far-out observation that might be quite atypical; all measures have their special advantages and disadvantages.) Simply compare the difference in medians of the twelve-pig resamples to the difference in medians of the actual samples, just as was done with the means. The only operational difference is to substitute the word “median” for the word “mean” in the steps listed above. You may need a somewhat larger number of trials when working with medians, however, for they tend to be less precise than means.</p>
<!---
Discussion of bootstrap and median?
-->
<p>The RESAMPLING STATS program compares the difference in the sums of the weight gains for the actual pigs against the difference resulting from two randomly-chosen groups of pigs, using the same numerical weight gains of individual pigs as were obtained in the actual experiment. If the differences in average weight gains of the randomly ordered groups are rarely as large as the difference in weight gains from the actual sets of pigs fed food A-alpha and food B-beta, then we can conclude that the foods do make a difference in pigs’ weight gains.</p>
<p>Note first that pigs in group A gained a total of 382 pounds while group B gained a total of 344 pounds — 38 fewer. To minimize computations, we will deal with totals like these, not averages.</p>
<p>First we construct vectors A and B of the weight gains of the pigs fed with the two foods. Then we combine the two vectors into one long vector and select two groups of 12 randomly and with replacement (the two SAMPLE commands). We SUM the weight gains for the two resamples, and calculate the difference. We keep SCORE of those differences, graph them on a HISTOGRAM, and see how many times resample A exceeded resample B by at least 38 pounds, or vice versa (we are testing whether the two are different, not whether food A produces larger weight gains).</p>
<!--- Resampling stats file; Matlab syntax closeish -->
<div class="sourceCode" id="cb1"><pre class="sourceCode matlab code-with-copy"><code class="sourceCode matlab"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="er">' Program file: "testing_measured_00.rss"</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="va">NUMBERS</span> (<span class="fl">31</span> <span class="fl">34</span> <span class="fl">29</span> <span class="fl">26</span> <span class="fl">32</span> <span class="fl">35</span> <span class="fl">38</span> <span class="fl">34</span> <span class="fl">31</span> <span class="fl">29</span> <span class="fl">32</span> <span class="fl">31</span>) <span class="va">a</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="ss">' Record group a'</span><span class="va">s</span> <span class="va">weight</span> <span class="va">gains</span>.</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="va">NUMBERS</span> (<span class="fl">26</span> <span class="fl">24</span> <span class="fl">28</span> <span class="fl">29</span> <span class="fl">30</span> <span class="fl">29</span> <span class="fl">31</span> <span class="fl">29</span> <span class="fl">32</span> <span class="fl">26</span> <span class="fl">28</span> <span class="fl">32</span>) <span class="va">b</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="ss">' Record group b'</span><span class="va">s</span> <span class="va">weight</span> <span class="va">gains</span>.</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="va">CONCAT</span> <span class="va">a</span> <span class="va">b</span> <span class="va">c</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="er">' Combine a and b together in one long vector.</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="va">REPEAT</span> <span class="fl">1000</span></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>    <span class="er">' Do 1000 experiments.</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>    <span class="va">SAMPLE</span> <span class="fl">12</span> <span class="va">c</span> <span class="va">d</span></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    <span class="er">' Take a "resample" of 12 with replacement from c and put it in d.</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    <span class="va">SAMPLE</span> <span class="fl">12</span> <span class="va">c</span> <span class="va">e</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    <span class="er">' Take another "resample."</span></span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>    <span class="va">SUM</span> <span class="va">d</span> <span class="va">dd</span></span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>    <span class="er">' Sum the first "resample."</span></span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>    <span class="va">SUM</span> <span class="va">e</span> <span class="va">ee</span></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>    <span class="er">' Sum the second "resample."</span></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>    <span class="va">SUBTRACT</span> <span class="va">dd</span> <span class="va">ee</span> <span class="va">f</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>    <span class="er">' Calculate the difference between the two resamples.</span></span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>    <span class="va">SCORE</span> <span class="va">f</span> <span class="va">z</span></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>    <span class="er">' Keep track of each trial result.</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="va">END</span></span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="er">' End one experiment, go back and repeat until all trials are complete,</span></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="er">' then proceed.</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="va">HISTOGRAM</span> <span class="va">z</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="er">' Produce a histogram of trial results.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>PIGS3: Difference Between Two Resamples</strong></p>
<p>Sum of Weight Gains</p>
<p><img src="images/22-Chap-18_002.png" class="img-fluid"></p>
<p><strong>1</strong> <strong>st</strong> <strong>resample less 2</strong> <strong>nd</strong></p>
<p>From this histogram we see that none of the trials produced a difference between groups as large as that observed (or larger). RESAMPLING STATS will calculate this for us with the following commands:</p>
<!--- Resampling stats file; Matlab syntax closeish -->
<div class="sourceCode" id="cb2"><pre class="sourceCode matlab code-with-copy"><code class="sourceCode matlab"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="er">' Program file: "pigs3.rss"</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="va">COUNT</span> <span class="va">z</span> <span class="op">&gt;=</span> <span class="fl">38</span> <span class="va">k</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="er">' Determine how many of the trials produced a difference between resamples</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="er">' \&gt;= 38.</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="va">COUNT</span> <span class="va">z</span> <span class="op">&lt;=</span> <span class="op">-</span><span class="fl">38</span> <span class="va">l</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="er">' Likewise for a difference of -38.</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="va">ADD</span> <span class="va">k</span> <span class="va">l</span> <span class="va">m</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="er">' Add the two together.</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="va">DIVIDE</span> <span class="va">m</span> <span class="fl">1000</span> <span class="va">mm</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="er">' Convert to a proportion.</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="va">PRINT</span> <span class="va">mm</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="er">' Print the result.</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a><span class="er">' Note: The file "pigs3" on the Resampling Stats software disk contains</span></span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="er">' this set of commands.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</section>
<section id="sec-liquor-public-measured" class="level3" data-number="24.0.2">
<h3 data-number="24.0.2" class="anchored" data-anchor-id="sec-liquor-public-measured"><span class="header-section-number">24.0.2</span> Example: Is There a Difference in Liquor Prices Between State-Run and Privately-Run Systems?</h3>
<p>This is an example of <strong>testing for differences between means of unequal-sized samples of measured data</strong>.</p>
<p>In the 1960s I studied the price of liquor in the sixteen “monopoly” states (where the state government owns the retail liquor stores) compared to the twenty-six states in which retail liquor stores are privately owned. (Some states were omitted for technical reasons. And it is interesting to note that the situation and the price pattern has changed radically since then.) These data were introduced in the context of a problem in probability in <a href="probability_theory_3.html" class="quarto-xref"><span>Chapter&nbsp;12</span></a>.</p>
<p>These were the representative 1961 prices of a fifth of Seagram 7 Crown whiskey in the two sets of states:<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a></p>
<p>16 monopoly states: $4.65, $4.55, $4.11, $4.15, $4.20, $4.55, $3.80,</p>
<p>$4.00, $4.19, $4.75, $4.74, $4.50, $4.10, $4.00, $5.05, $4.20</p>
<p>Mean = $4.35</p>
<p>26 private-ownership states: $4.82, $5.29, $4.89, $4.95, $4.55, $4.90,</p>
<p>$5.25, $5.30, $4.29, $4.85, $4.54, $4.75, $4.85, $4.85, $4.50, $4.75,</p>
<p>$4.79, $4.85, $4.79, $4.95, $4.95, $4.75, $5.20, $5.10, $4.80, $4.29.</p>
<p>Mean = $4.84</p>
<p>The <em>economic</em> question that underlay the investigation — having both theoretical and policy ramifications — is as follows: Does state ownership affect prices? The <em>empirical</em> question is whether the prices in the two sets of states were systematically different. In <em>statistical</em> terms, we wish to test the hypothesis that there was a difference between the groups of states related to their mode of liquor distribution, or whether the observed $.49 differential in means might well have occurred by happenstance. In other words, we want to know whether the two sub-groups of states differed systematically in their liquor prices, or whether the observed pattern could well have been produced by chance variability.</p>
<p>The first step is to examine the two sets of data graphically to see whether there was such a clear-cut difference between them — of the order of Snow’s data on cholera, or the Japanese Navy data on beri-beri — that no test was necessary. The separate displays, and then the two combined together, are shown in <a href="#fig-liquor_price_plots" class="quarto-xref">Figure&nbsp;<span>24.1</span></a>; the answer is not clear-cut and hence a formal test is necessary.</p>

<!---
Refer back to @sec-inference-ideas tables 11.3 and 11.4.
-->
<div class="cell" data-layout-align="center" data-opts.label="svg_fig" data-hash="testing_measured_cache/html/fig-liquor_price_plots_47f9e37428e0f8bdc913a79da30eb235">
<div class="cell-output-display">
<div id="fig-liquor_price_plots" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="diagrams/liquor_price_plots.svg" class="img-fluid figure-img" style="width:70.0%"></p>
<figcaption class="figure-caption">Figure&nbsp;24.1: Liquor prices by government and private</figcaption>
</figure>
</div>
</div>
</div>
<p>At first I used a resampling permutation test as follows: Assuming that the entire universe of possible prices consists of the set of events that were observed, because that is all the information available about the universe, I wrote each of the forty-two observed state prices on a separate card. The shuffled deck simulated a situation in which each state has an equal chance for each price.</p>
<p>On the “null hypothesis” that the two groups’ prices do <em>not</em> reflect different price-setting mechanisms, but rather differ only by chance, I then examined how often that simulated universe stochastically produces groups with results as different as observed in 1961. I repeatedly dealt groups of 16 and 26 cards, without replacing the cards, to simulate hypothetical monopoly-state and private-state samples, each time calculating the difference in mean prices.</p>
<p>The probability that the benchmark null-hypothesis universe would produce a difference between groups as large or larger than observed in 1961 is estimated by how frequently the mean of the group of randomly-chosen sixteen prices from the simulated state-ownership universe is less than (or equal to) the mean of the actual sixteen state-ownership prices. If the simulated difference between the randomly-chosen groups was frequently equal to or greater than observed in 1961, one would not conclude that the observed difference was due to the type of retailing system because it could well have been due to chance variation.</p>
<p>The results — not even one “success” in 10,000 trials — imply that there is a very small probability that two groups with mean prices as different as were observed would happen by chance if drawn from the universe of 42 observed prices. So we “reject the null hypothesis” and instead find persuasive the proposition that the type of liquor distribution system influences the prices that consumers pay.<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a></p>
<p>As I shall discuss later, the logical framework of this resampling version of the permutation test differs greatly from the formulaic version, which would have required heavy computation. The standard conventional alternative would be a Student’s t-test, in which the user simply plugs into an unintuitive formula and reads the result from a table. And because of the unequal numbers of cases and unequal dispersions in the two samples, an appropriate t-test is far from obvious, whereas resampling is not made more difficult by such realistic complications.</p>
<!---
Discussion of t-test?  Have we introduced the t-test?
-->
<p>A program to handle the liquor problem with an infinite-universe bootstrap distribution simply substitutes the random sampling command SAMPLE for the SHUFFLE/TAKE commands. The results of the new test are indistinguishable from those in the program given above.</p>
<p>Still another difficult question is whether <em>any</em> hypothesis test is appropriate, because the states were not randomly selected for inclusion in one group or another, and the results could be caused by factors other than the liquor system; this applies to both the above methods. The states constitute the entire universe in which we are interested, rather than being a sample taken from some larger universe as with a biological experiment or a small survey sample. But this objection pertains to a conventional test as well as to resampling methods. And a similar question arises throughout medical and social science — to the two water suppliers between which John Snow detected vast differences in cholera rates, to rates of lung cancer in human smokers, to analyses of changes in speeding laws, and so on.</p>
<p>The appropriate question is not whether the units were assigned randomly, however, but whether there is strong reason to believe that the results are not meaningful because they are the result of a <em>particular</em> “hidden” variable.</p>
<p>These debates about fundamentals illustrate the unsettled state of statistical thinking about basic issues. Other disciplines also have their controversies about fundamentals. But in statistics these issues arise as early as the introductory course, because all but the most contrived problems are shot through with these questions. Instructors and researchers usually gloss over these matters, as Gigerenzer et al., show ( <em>The Empire of Chance</em> ). Again, because with resampling one does not become immersed in the difficult mathematical techniques that underlie conventional methods, one is quicker to see these difficult questions, which apply equally to conventional methods and resampling.</p>
<!---
Discussion of fogginess that arises from uncertainty about maths.
-->
<p><strong>Example 18-3: Is There a Difference Between Treatments to Prevent Low Birthweights?</strong></p>
<p>Next we consider the use of resampling with <em>measured</em> data to test the hypothesis that drug A prevents low birthweights (Rosner, 1982, p.&nbsp;257). The data for the treatment and control groups are shown in Table 18-2.</p>
<p>Table 18-2</p>
<p><strong>Birthweights in a Clinical Trial to Test a Drug for Preventing Low Birthweights</strong></p>
<table class="table">
<tbody>
<tr class="odd">
<td style="text-align: left;"><strong>Treatment Group</strong></td>
<td style="text-align: left;"><strong>Control Group</strong></td>
</tr>
<tr class="even">
<td style="text-align: left;">6.9</td>
<td style="text-align: left;">6.4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7.6</td>
<td style="text-align: left;">6.7</td>
</tr>
<tr class="even">
<td style="text-align: left;">7.3</td>
<td style="text-align: left;">5.4</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7.6</td>
<td style="text-align: left;">8.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">6.8</td>
<td style="text-align: left;">5.3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7.2</td>
<td style="text-align: left;">6.6</td>
</tr>
<tr class="even">
<td style="text-align: left;">8.0</td>
<td style="text-align: left;">5.8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5.5</td>
<td style="text-align: left;">5.7</td>
</tr>
<tr class="even">
<td style="text-align: left;">5.8</td>
<td style="text-align: left;">6.2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">7.3</td>
<td style="text-align: left;">7.1</td>
</tr>
<tr class="even">
<td style="text-align: left;">8.2</td>
<td style="text-align: left;">7.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">6.9</td>
<td style="text-align: left;">6.9</td>
</tr>
<tr class="even">
<td style="text-align: left;">6.8</td>
<td style="text-align: left;">5.6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5.7</td>
<td style="text-align: left;">4.2</td>
</tr>
<tr class="even">
<td style="text-align: left;">8.6</td>
<td style="text-align: left;">6.8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Average: 7.08</td>
<td style="text-align: left;">6.26</td>
</tr>
</tbody>
</table>
<p>Source: Rosner, Table 8.7</p>
<p>The treatment group averaged .82 pounds more than the control group. Here is a resampling approach to the problem:</p>
<ol type="1">
<li><p>If the drug has no effect, our best guess about the “universe” of birthweights is that it is composed of (say) a million each of the observed weights, all lumped together. In other words, in the absence of any other information or compelling theory, we assume that the combination of our samples is our best estimate of the universe. Hence let us write each of the birthweights on a card, and put them into a hat. Drawing them one by one and then replacing them is the operational equivalent of a very large (but equal) number of each birthweight.</p></li>
<li><p>Repeatedly draw two samples of 15 birthweights each, and check how frequently the observed difference is as large as, or larger than, the actual difference of .82 pounds.</p></li>
</ol>
<p>We find in the RESAMPLING STATS program below that only 1 percent of the pairs of hypothetical resamples produced means that differed by as much as .82. We therefore conclude that the observed difference is unlikely to have occurred by chance.</p>
<!--- Resampling stats file; Matlab syntax closeish -->
<div class="sourceCode" id="cb3"><pre class="sourceCode matlab code-with-copy"><code class="sourceCode matlab"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="er">' Program file: "testing_measured_02.rss"</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="va">NUMBERS</span> (<span class="fl">6.9</span> <span class="fl">7.6</span> <span class="fl">7.3</span> <span class="fl">7.6</span> <span class="fl">6.8</span> <span class="fl">7.2</span> <span class="fl">8.0</span> <span class="fl">5.5</span> <span class="fl">5.8</span> <span class="fl">7.3</span> <span class="fl">8.2</span> <span class="fl">6.9</span> <span class="fl">6.8</span> <span class="fl">5.7</span> <span class="fl">8.6</span>) <span class="va">treat</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="va">NUMBERS</span> (<span class="fl">6.4</span> <span class="fl">6.7</span> <span class="fl">5.4</span> <span class="fl">8.2</span> <span class="fl">5.3</span> <span class="fl">6.6</span> <span class="fl">5.8</span> <span class="fl">5.7</span> <span class="fl">6.2</span> <span class="fl">7.1</span> <span class="fl">7.0</span> <span class="fl">6.9</span> <span class="fl">5.6</span> <span class="fl">4.2</span> <span class="fl">6.8</span>) <span class="va">control</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="va">CONCAT</span> <span class="va">treat</span> <span class="va">control</span> <span class="va">all</span></span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="er">' Combine all birthweight observations in same vector</span></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="va">REPEAT</span> <span class="fl">1000</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>    <span class="er">' Do 1000 simulations</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>    <span class="va">SAMPLE</span> <span class="fl">15</span> <span class="va">all</span> <span class="va">treat</span>$</span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a>    <span class="er">' Take a resample of 15 from all birth weights (the \$ indicates a</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a>    <span class="er">' resampling counterpart to a real sample)</span></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>    <span class="va">SAMPLE</span> <span class="fl">15</span> <span class="va">all</span> <span class="va">control</span>$</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>    <span class="er">' Take a second, similar resample</span></span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>    <span class="va">MEAN</span> <span class="va">treat</span>$ <span class="va">mt</span></span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>    <span class="er">' Find the means of the two resamples</span></span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>    <span class="va">MEAN</span> <span class="va">control</span>$ <span class="va">mc</span></span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>    <span class="va">SUBTRACT</span> <span class="va">mt</span> <span class="va">mc</span> <span class="va">dif</span></span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>    <span class="er">' Find the difference between the means of the two resamples</span></span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>    <span class="va">SCORE</span> <span class="va">dif</span> <span class="va">z</span></span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>    <span class="er">' Keep score of the result</span></span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a><span class="va">END</span></span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a><span class="er">' End the simulation experiment, go back and repeat</span></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a><span class="va">HISTOGRAM</span> <span class="va">z</span></span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a><span class="er">' Produce a histogram of the resample differences</span></span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a><span class="va">COUNT</span> <span class="va">z</span> <span class="op">&gt;=</span> <span class="fl">0.82</span> <span class="va">k</span></span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a><span class="er">' How often did resample differences exceed the observed difference of</span></span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a><span class="er">' .82?</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="images/22-Chap-18_006.png" class="img-fluid"></p>
<p><strong>Resample differences in pounds</strong></p>
<p>Result: Only 1.3 percent of the pairs of resamples produced means that differed by as much as .82. We can conclude that the observed difference is unlikely to have occurred by chance.</p>
</section>
<section id="sec-eg-bootstrap-sampling" class="level3" data-number="24.0.3">
<h3 data-number="24.0.3" class="anchored" data-anchor-id="sec-eg-bootstrap-sampling"><span class="header-section-number">24.0.3</span> Example: Bootstrap Sampling with Replacement</h3>
<p>Efron and Tibshirani <span class="citation" data-cites="efron1993bootstrap">(<a href="references.html#ref-efron1993bootstrap" role="doc-biblioref">1993, 11</a>)</span> present this as their basic problem illustrating the bootstrap method: Seven mice were given a new medical treatment intended to improve their survival rates after surgery, and nine mice were not treated. The numbers of days the treated mice survived were 94, 38, 23, 197, 99, 16 and 14, whereas the numbers of days the untreated mice (the control group) survived were 52, 10, 40, 104, 51, 27, 146, 30, and 46. The question we ask is: Did the treatment prolong survival, or might chance variation be responsible for the observed difference in mean survival times?</p>
<p>We start by supposing the treatment did NOT prolong survival and that chance was responsible. <!---
Clarify - sampling variation was responsible.
--> If that is so, then we consider that the two groups came from the same universe. Now we’d like to know how likely it is that two groups drawn from this common universe would differ as much as the two observed groups differ.</p>
<p>If we had unlimited time and money, we would seek additional samples in the same way that we obtained these. Lacking time and money, we create a hypothetical universe that embodies everything we know about such a common universe. We imagine replicating each sample element millions of times to create an almost infinite universe that looks just like our samples. Then we can take resamples from this hypothetical universe and see how they behave.</p>
<p>Even on a computer, creating such a large universe is tedious so we use a shortcut. We replace each element after we pick it for a resample. That way, our hypothetical (bootstrap) universe is effectively infinite.</p>
<p>The following procedure will serve:</p>
<ol type="1">
<li><p>Calculate the difference between the means of the two observed samples – it’s 30.63 days in favor of the treated mice.</p></li>
<li><p>Consider the two samples combined (16 observations) as the relevant universe to resample from.</p></li>
<li><p>Draw 7 hypothetical observations with replacement and designate them “Treatment”; draw 9 hypothetical observations with replacement and designate them “Control.”</p></li>
<li><p>Compute and record the difference between the means of the two samples.</p>
<p>Repeat steps 2 and 3 perhaps 1000 times.</p></li>
<li><p>Determine how often the resampled difference exceeds the observed difference of 30.63.</p></li>
</ol>
<p>The following program (“mice2smp”) follows the above procedure:</p>
<!--- Resampling stats file; Matlab syntax closeish -->
<div class="sourceCode" id="cb4"><pre class="sourceCode matlab code-with-copy"><code class="sourceCode matlab"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="er">' Program file: "testing_measured_03.rss"</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="va">NUMBERS</span> (<span class="fl">94</span> <span class="fl">38</span> <span class="fl">23</span> <span class="fl">197</span> <span class="fl">99</span> <span class="fl">16</span> <span class="fl">141</span>) <span class="va">treatmt</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="er">' treatment group</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="va">NUMBERS</span> (<span class="fl">52</span> <span class="fl">10</span> <span class="fl">40</span> <span class="fl">104</span> <span class="fl">51</span> <span class="fl">27</span> <span class="fl">146</span> <span class="fl">30</span> <span class="fl">46</span>) <span class="va">control</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="er">' control group</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="va">CONCAT</span> <span class="va">treatmt</span> <span class="va">control</span> <span class="va">u</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="er">' U is our universe (step 2 above)</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a><span class="va">REPEAT</span> <span class="fl">1000</span></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>    <span class="er">' step 5 above</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>    <span class="va">SAMPLE</span> <span class="fl">7</span> <span class="va">u</span> <span class="va">treatmt</span>$</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>    <span class="er">' step 3 above</span></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>    <span class="va">SAMPLE</span> <span class="fl">9</span> <span class="va">u</span> <span class="va">control</span>$</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a>    <span class="er">' step 3</span></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>    <span class="va">MEAN</span> <span class="va">treatmt</span>$ <span class="va">tmean</span></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>    <span class="er">' step 4</span></span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>    <span class="va">MEAN</span> <span class="va">control</span>$ <span class="va">cmean</span></span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>    <span class="er">' step 4</span></span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>    <span class="va">SUBTRACT</span> <span class="va">tmean</span> <span class="va">cmean</span> <span class="va">diff</span></span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>    <span class="er">' step 4</span></span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>    <span class="va">SCORE</span> <span class="va">diff</span> <span class="va">scrboard</span></span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>    <span class="er">' step 4</span></span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a><span class="va">END</span></span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a><span class="er">' step 5</span></span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a><span class="va">HISTOGRAM</span> <span class="va">scrboard</span></span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a><span class="va">COUNT</span> <span class="va">scrboard</span> <span class="op">&gt;=</span><span class="fl">30.63</span> <span class="va">k</span></span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a><span class="er">' step 6</span></span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a><span class="va">DIVIDE</span> <span class="va">k</span> <span class="fl">1000</span> <span class="va">prob</span></span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a><span class="va">PRINT</span> <span class="va">prob</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="images/22-Chap-18_007.png" class="img-fluid"></p>
<p>Result: PROB = 0.112</p>
<p>Interpretation: 1000 simulated resamples (of sizes 7 and 9) from a combined universe produced a difference as big as 30.63 more than 11 percent of the time. We cannot rule out the possibility that chance might be responsible for the observed advantage of the treatment group.</p>
<p><strong>Example 18-5: Permutation Sampling Without Replacement</strong></p>
<p>This section discusses at some length the question of when sampling with replacement (the bootstrap), and sampling without replacement (permutation or “exact” test) are the appropriate resampling methods. The case at hand seems like a clearcut case where the bootstrap is appropriate. (Note that in this case we draw both samples from a combined universe consisting of all observations, whether we do so with or without replacement.) Nevertheless, let us see how the technique would differ if one were to consider that the permutation test is appropriate. The algorithm would then be as follows (with the steps that are the same as above labeled “a” and those that are different labeled “b”):</p>
<p><strong>1a.</strong> Calculate the difference between the means of the two observed samples – it’s 30.63 days in favor of the treated mice.</p>
<p><strong>2a.</strong> Consider the two samples combined (16 observations) as the relevant universe to resample from.</p>
<p><strong>3b.</strong> Draw 7 hypothetical observations without replacement and designate them “Treatment”; draw 9 hypothetical observations with replacement and designate them “Control.”</p>
<p><strong>4a.</strong> Compute and record the difference between the means of the two samples.</p>
<p><strong>5a.</strong> Repeat steps 2 and 3 perhaps 1000 times</p>
<p><strong>6a.</strong> Determine how often the resampled difference exceeds the observed difference of 30.63.</p>
<p>Here is the RESAMPLING STATS program:</p>
<!--- Resampling stats file; Matlab syntax closeish -->
<div class="sourceCode" id="cb5"><pre class="sourceCode matlab code-with-copy"><code class="sourceCode matlab"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="er">' Program file: "testing_measured_04.rss"</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="va">NUMBERS</span> (<span class="fl">94</span> <span class="fl">38</span> <span class="fl">23</span> <span class="fl">197</span> <span class="fl">99</span> <span class="fl">16</span> <span class="fl">141</span>) <span class="va">treatmt</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="er">' treatment group</span></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a><span class="va">NUMBERS</span> (<span class="fl">52</span> <span class="fl">10</span> <span class="fl">40</span> <span class="fl">104</span> <span class="fl">51</span> <span class="fl">27</span> <span class="fl">146</span> <span class="fl">30</span> <span class="fl">46</span>) <span class="va">control</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="er">' control group</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a><span class="va">CONCAT</span> <span class="va">treatmt</span> <span class="va">control</span> <span class="va">u</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="er">' U is our universe (step 2 above)</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="va">REPEAT</span> <span class="fl">1000</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a>    <span class="er">' step 5 above</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>    <span class="va">SHUFFLE</span> <span class="va">u</span> <span class="va">ushuf</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>    <span class="va">TAKE</span> <span class="va">ushuf</span> <span class="fl">1</span><span class="op">,</span><span class="fl">7</span> <span class="va">treatmt</span>$</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>    <span class="er">' step 3 above</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>    <span class="va">TAKE</span> <span class="va">ushuf</span> <span class="fl">8</span><span class="op">,</span><span class="fl">16</span> <span class="va">control</span>$</span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>    <span class="er">' step 3</span></span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>    <span class="va">MEAN</span> <span class="va">treatmt</span>$ <span class="va">tmean</span></span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>    <span class="er">' step 4</span></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>    <span class="va">MEAN</span> <span class="va">control</span>$ <span class="va">cmean</span></span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>    <span class="er">' step 4</span></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>    <span class="va">SUBTRACT</span> <span class="va">tmean</span> <span class="va">cmean</span> <span class="va">diff</span></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>    <span class="er">' step 4</span></span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>    <span class="va">SCORE</span> <span class="va">diff</span> <span class="va">scrboard</span></span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>    <span class="er">' step 4</span></span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a><span class="va">END</span></span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a><span class="er">' step 5</span></span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a><span class="va">HISTOGRAM</span> <span class="va">scrboard</span></span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a><span class="va">COUNT</span> <span class="va">scrboard</span> <span class="op">&gt;=</span><span class="fl">30.63</span> <span class="va">k</span></span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a><span class="er">' step 6</span></span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a><span class="va">DIVIDE</span> <span class="va">k</span> <span class="fl">1000</span> <span class="va">prob</span></span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a><span class="va">PRINT</span> <span class="va">prob</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><img src="images/22-Chap-18_008.png" class="img-fluid"></p>
<p>Result: prob = 0.145</p>
<p>Interpretation: 1000 simulated resamples (of sizes 7 and 9) from a combined universe produced a difference as big as 30.63 more than 14 percent of the time. We therefore should not rule out the possibility that chance might be responsible for the observed advantage of the treatment group.</p>
</section>
<section id="differences-among-four-means" class="level2" data-number="24.1">
<h2 data-number="24.1" class="anchored" data-anchor-id="differences-among-four-means"><span class="header-section-number">24.1</span> Differences among four means</h2>
<p><strong>Example 18-6: Differences Among Four Pig Rations</strong> (Test for Differences Among Means of More Than Two Samples of Measured Data) (File “PIGS4”)</p>
<p>In Examples 15-1 and 15-4 we investigated whether or not the results shown by a <em>single</em> sample are sufficiently different from a null (benchmark) hypothesis so that the sample is unlikely to have come from the null-hypothesis benchmark universe. In Examples 15-7, 17-1, and 18-1 we then investigated whether or not the results shown by <em>two</em> samples suggest that both had come from the <em>same</em> universe, a universe that was assumed to be the composite of the two samples. Now as in Example 17-2 we investigate whether or not <em>several</em> samples come from the same universe, except that now we work with measured data rather than with counted data.</p>
<p>If one experiments with each of 100 different pig foods on twelve pigs, some of the foods will show much better results than will others <em>just by chance</em> , just as one family in sixteen is likely to have the very “high” number of 4 daughters in its first four children. Therefore, it is wrong reasoning to try out the 100 pig foods, select the food that shows the best results, and then compare it statistically with the average (sum) of all the other foods (or worse, with the poorest food). With such a procedure and enough samples, you will surely find one (or more) that seems very atypical statistically. A bridge hand with 12 or 13 spades seems very atypical, too, but if you deal enough bridge hands you will sooner or later get one with 12 or 13 spades — as a purely chance phenomenon, dealt randomly from a standard deck. Therefore we need a test that prevents our falling into such traps. Such a test usually operates by taking into account the differences among <em>all</em> the foods that were tried.</p>
<p>The method of Example 18-1 can be extended to handle this problem. Assume that <em>four</em> foods were each tested on twelve pigs. The weight gains in pounds for the pigs fed on foods A and B were as before. For foods C and D the weight gains were:</p>
<p>Ration C: 30, 30, 32, 31, 29, 27, 25, 30, 31, 32, 34, 33</p>
<p>Ration D: 32, 25, 31, 26, 32, 27, 28, 29, 29, 28, 23, 25</p>
<p>Now construct a benchmark universe of <em>forty-eight</em> index cards, one for each weight gain. Then deal out sets of four hands randomly. More specifically:</p>
<p><strong>Step 1.</strong> Constitute a universe of the forty-eight observed weight gains in the four samples, writing the weight gains on cards.</p>
<p><strong>Step 2.</strong> Draw four groups of twelve weight gains, with replacement, since we are drawing from a hypothesized infinite universe in which consecutive draws are independent. Determine whether the difference between the lowest and highest group means is as large or larger than the observed difference. If so write “yes,” otherwise “no.”</p>
<p><strong>Step 3.</strong> Repeat step 2 fifty times.</p>
<p><strong>Step 4.</strong> Count the trials in which the differences between the simulated groups with the highest and lowest means are as large or larger than the differences between the means of the highest and lowest observed samples. The proportion of such trials to the total number of trials is the probability that all four samples would differ as much as do the observed samples if they (in technical terms) come from the same universe.</p>
<p>The problem “Pigs4,” as handled by the steps given above, is quite similar to the way we handled Example TKTK, except that the data are measured (in pounds of weight gain) rather than simply counted (the number of rehabilitations).</p>
<p>Instead of working through a program for the procedure outlined above, let us consider a different approach to the problem — computing the difference between each <em>pair</em> of foods, six differences in all, converting all minus (-) signs to (+) differences. Then we can <em>total</em> the six differences, and compare the total with the sum of the six differences in the <em>observed</em> sample. The proportion of the resampling trials in which the observed sample sum is exceeded by the sum of the differences in the trials is the probability that the observed samples would differ as much as they do if they come from the same universe.<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a></p>
<p>One naturally wonders whether this latter test statistic is better than the range, as discussed above. It would seem obvious that using the information contained in all four samples should increase the precision of the estimate. And indeed it is so, as you can confirm for yourself by comparing the results of the two approaches. But in the long run, the estimate provided by the two approaches would be much the same. That is, there is no reason to think that one or another of the estimates is <em>biased</em> . However, successive samples from the population would steady down faster to the true value using the four-groupbased estimate than they would using the range. That is, the four-group-based estimate would require a smaller sample of pigs.</p>
<p>Is there reason to prefer one or the other approach from the point of view of some decision that might be made? One might think that the range procedure throws light on which <em>one</em> of the foods is best in a way that the four-group-based approach does not. But this is not correct. Both approaches answer this question, and <em>only</em> this question: Are the results from the four foods likely to have resulted from the same “universe” of weight gains or not? If one wants to know whether the <em>best</em> food is similar to, say, all the other three, the appropriate approach would be a <em>two</em> -sample approach similar to various <em>two</em> -sample examples discussed earlier. (It would be still <em>another</em> question to ask whether the best food is different from the worst. One would then use a procedure different from either of those discussed above.)</p>
<p>If the foods cost the same, one would not need even a twosample analysis to decide which food to feed. Feed the one whose results are best in the experiment, without bothering to ask whether it is “really” the best; you can’t go wrong as long as it doesn’t cost more to use it. (One could inquire about the probability that the food yielding the best results in the experiment would attain those results by chance even if it was worse than the others by some stipulated amount, but pursuing that line of thought may be left to the student as an exercise.)</p>
<p>In the problem “Pigs4,” we want a measure of how the groups differ. The obvious first step is to add up the total weight gains for each group: 382, 344, 364, 335. The next step is to calculate the differences between all the possible combinations of groups: 382-344=38, 382-364=18, 382-335=47, 344-364= -20, 344-335=9, 364-335=29.</p>
</section>
<section id="using-squared-differences" class="level2" data-number="24.2">
<h2 data-number="24.2" class="anchored" data-anchor-id="using-squared-differences"><span class="header-section-number">24.2</span> Using Squared Differences</h2>
<p>Here we face a choice. We could work with the absolute differences — that is, the results of the subtractions — treating each result as a positive number even if it is negative. We have seen this approach before. Therefore let us now take the opportunity of showing another approach. Instead of working with the absolute differences, we <em>square</em> each difference, and then SUM the squares. An advantage of working with the squares is that they are positive — a negative number squared is positive — which is convenient. Additionally, conventional statistics works mainly with squared quantities, and therefore it is worth getting familiar with that point of view. The squared differences in this case add up to 5096.</p>
<p>Using RESAMPLING STATS, we shuffle all the weight gains together, select four random groups, and determine whether the squared differences in the resample exceed 5096. If they do so with regularity, then we conclude that the observed differences could easily have occurred by chance.</p>
<p>With the CONCAT command, we string the four vectors into a single vector. After SHUFFLEing the 48-pig weight-gain vector G into H, we TAKE four randomized samples. And we compute the squared differences between the pairs of groups and SUM the squared differences just as we did above for the observed groups.</p>
<p>Last, we examine how often the simulated-trials data produce differences among the groups as large as (or larger than) the actually observed data — 5096.</p>
<!--- Resampling stats file; Matlab syntax closeish -->
<div class="sourceCode" id="cb6"><pre class="sourceCode matlab code-with-copy"><code class="sourceCode matlab"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="er">' Program file: "pigs4.rss"</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="va">NUMBERS</span> (<span class="fl">34</span> <span class="fl">29</span> <span class="fl">26</span> <span class="fl">32</span> <span class="fl">35</span> <span class="fl">38</span> <span class="fl">31</span> <span class="fl">34</span> <span class="fl">30</span> <span class="fl">29</span> <span class="fl">32</span> <span class="fl">31</span>) <span class="va">a</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="va">NUMBERS</span> (<span class="fl">26</span> <span class="fl">24</span> <span class="fl">28</span> <span class="fl">29</span> <span class="fl">30</span> <span class="fl">29</span> <span class="fl">32</span> <span class="fl">26</span> <span class="fl">31</span> <span class="fl">29</span> <span class="fl">32</span> <span class="fl">28</span>) <span class="va">b</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a><span class="va">NUMBERS</span> (<span class="fl">30</span> <span class="fl">30</span> <span class="fl">32</span> <span class="fl">31</span> <span class="fl">29</span> <span class="fl">27</span> <span class="fl">25</span> <span class="fl">30</span> <span class="fl">31</span> <span class="fl">32</span> <span class="fl">34</span> <span class="fl">33</span>) <span class="va">c</span></span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a><span class="va">NUMBERS</span> (<span class="fl">32</span> <span class="fl">25</span> <span class="fl">31</span> <span class="fl">26</span> <span class="fl">32</span> <span class="fl">27</span> <span class="fl">28</span> <span class="fl">29</span> <span class="fl">29</span> <span class="fl">28</span> <span class="fl">23</span> <span class="fl">25</span>) <span class="va">d</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="er">' (Record the data for the 4 foods)</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a><span class="va">CONCAT</span> <span class="va">a</span> <span class="va">b</span> <span class="va">c</span> <span class="va">d</span> <span class="va">g</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a><span class="er">' Combine the four vectors into g</span></span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a><span class="va">REPEAT</span> <span class="fl">1000</span></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>    <span class="er">' Do 1000 trials</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>    <span class="va">SHUFFLE</span> <span class="va">g</span> <span class="va">h</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>    <span class="er">' Shuffle all the weight gains.</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>    <span class="va">SAMPLE</span> <span class="fl">12</span> <span class="va">h</span> <span class="va">p</span></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>    <span class="er">' Take 4 random samples, with replacement.</span></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>    <span class="va">SAMPLE</span> <span class="fl">12</span> <span class="va">h</span> <span class="va">q</span></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>    <span class="va">SAMPLE</span> <span class="fl">12</span> <span class="va">h</span> <span class="va">r</span></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>    <span class="va">SAMPLE</span> <span class="fl">12</span> <span class="va">h</span> <span class="va">s</span></span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a>    <span class="va">SUM</span> <span class="va">p</span> <span class="va">i</span></span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>    <span class="er">' Sum the weight gains for the 4 resamples.</span></span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>    <span class="va">SUM</span> <span class="va">q</span> <span class="va">j</span></span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>    <span class="va">SUM</span> <span class="va">r</span> <span class="va">k</span></span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>    <span class="va">SUM</span> <span class="va">s</span> <span class="va">l</span></span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>    <span class="va">SUBTRACT</span> <span class="va">i</span> <span class="va">j</span> <span class="va">ij</span></span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>    <span class="er">' Find the differences between all the possible pairs of resamples.</span></span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>    <span class="va">SUBTRACT</span> <span class="va">i</span> <span class="va">k</span> <span class="va">ik</span></span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>    <span class="va">SUBTRACT</span> <span class="va">i</span> <span class="va">l</span> <span class="va">il</span></span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>    <span class="va">SUBTRACT</span> <span class="va">j</span> <span class="va">k</span> <span class="va">jk</span></span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>    <span class="va">SUBTRACT</span> <span class="va">j</span> <span class="va">l</span> <span class="va">jl</span></span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a>    <span class="va">SUBTRACT</span> <span class="va">k</span> <span class="va">l</span> <span class="va">kl</span></span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a>    <span class="va">MULTIPLY</span> <span class="va">ij</span> <span class="va">ij</span> <span class="va">ijsq</span></span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a>    <span class="er">' Find the squared differences.</span></span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a>    <span class="va">MULTIPLY</span> <span class="va">ik</span> <span class="va">ik</span> <span class="va">iksq</span></span>
<span id="cb6-34"><a href="#cb6-34" aria-hidden="true" tabindex="-1"></a>    <span class="va">MULTIPLY</span> <span class="va">il</span> <span class="va">il</span> <span class="va">ilsq</span></span>
<span id="cb6-35"><a href="#cb6-35" aria-hidden="true" tabindex="-1"></a>    <span class="va">MULTIPLY</span> <span class="va">jk</span> <span class="va">jk</span> <span class="va">jksq</span></span>
<span id="cb6-36"><a href="#cb6-36" aria-hidden="true" tabindex="-1"></a>    <span class="va">MULTIPLY</span> <span class="va">jl</span> <span class="va">jl</span> <span class="va">jlsq</span></span>
<span id="cb6-37"><a href="#cb6-37" aria-hidden="true" tabindex="-1"></a>    <span class="va">MULTIPLY</span> <span class="va">kl</span> <span class="va">kl</span> <span class="va">klsq</span></span>
<span id="cb6-38"><a href="#cb6-38" aria-hidden="true" tabindex="-1"></a>    <span class="va">ADD</span> <span class="va">ijsq</span> <span class="va">iksq</span> <span class="va">ilsq</span> <span class="va">jksq</span> <span class="va">jlsq</span> <span class="va">klsq</span> <span class="va">total</span></span>
<span id="cb6-39"><a href="#cb6-39" aria-hidden="true" tabindex="-1"></a>    <span class="er">' Add them together.</span></span>
<span id="cb6-40"><a href="#cb6-40" aria-hidden="true" tabindex="-1"></a>    <span class="va">SCORE</span> <span class="va">total</span> <span class="va">z</span></span>
<span id="cb6-41"><a href="#cb6-41" aria-hidden="true" tabindex="-1"></a>    <span class="er">' Keep track of the total for each trial.</span></span>
<span id="cb6-42"><a href="#cb6-42" aria-hidden="true" tabindex="-1"></a><span class="va">END</span></span>
<span id="cb6-43"><a href="#cb6-43" aria-hidden="true" tabindex="-1"></a><span class="er">' End one trial, go back and repeat until 1000 trials are complete.</span></span>
<span id="cb6-44"><a href="#cb6-44" aria-hidden="true" tabindex="-1"></a><span class="va">HISTOGRAM</span> <span class="va">z</span></span>
<span id="cb6-45"><a href="#cb6-45" aria-hidden="true" tabindex="-1"></a><span class="er">' Produce a histogram of the trial results.</span></span>
<span id="cb6-46"><a href="#cb6-46" aria-hidden="true" tabindex="-1"></a><span class="va">COUNT</span> <span class="va">z</span> <span class="op">&gt;=</span> <span class="fl">5096</span> <span class="va">k</span></span>
<span id="cb6-47"><a href="#cb6-47" aria-hidden="true" tabindex="-1"></a><span class="er">' Find out how many trials produced differences among groups as great as</span></span>
<span id="cb6-48"><a href="#cb6-48" aria-hidden="true" tabindex="-1"></a><span class="er">' or greater than those observed.</span></span>
<span id="cb6-49"><a href="#cb6-49" aria-hidden="true" tabindex="-1"></a><span class="va">DIVIDE</span> <span class="va">k</span> <span class="fl">1000</span> <span class="va">kk</span></span>
<span id="cb6-50"><a href="#cb6-50" aria-hidden="true" tabindex="-1"></a><span class="er">' Convert to a proportion.</span></span>
<span id="cb6-51"><a href="#cb6-51" aria-hidden="true" tabindex="-1"></a><span class="va">PRINT</span> <span class="va">kk</span></span>
<span id="cb6-52"><a href="#cb6-52" aria-hidden="true" tabindex="-1"></a><span class="er">' Print the result.</span></span>
<span id="cb6-53"><a href="#cb6-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-54"><a href="#cb6-54" aria-hidden="true" tabindex="-1"></a><span class="er">' Note: The file "pigs4" on the Resampling Stats software disk contains</span></span>
<span id="cb6-55"><a href="#cb6-55" aria-hidden="true" tabindex="-1"></a><span class="er">' this set of commands.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p><strong>PIGS4: Differences Among Four Pig Rations</strong></p>
<p><img src="images/22-Chap-18_009.png" class="img-fluid"></p>
<p><strong>sums of squares</strong></p>
<p>We find that our observed sum of squares — 5096 — was exceeded by randomly-drawn sums of squares in only 3 percent of our trials. We conclude that the four treatments are likely not all similar.</p>
</section>
<section id="exercises" class="level2" data-number="24.3">
<h2 data-number="24.3" class="anchored" data-anchor-id="exercises"><span class="header-section-number">24.3</span> Exercises</h2>
<p>Solutions for problems may be found in the section titled, “Exercise Solutions” at the back of this book.</p>
<p><strong>Exercise 18-1</strong></p>
<p>The data shown in Table 18-3 <span class="citation" data-cites="hollander1999nonparametric">(<a href="references.html#ref-hollander1999nonparametric" role="doc-biblioref">Hollander and Wolfe 1999, 39</a>, Table 3.1)</span> might be data for the outcomes of two different mechanics, showing the length of time until the next overhaul is needed for nine pairs of similar vehicles. Or they could be two readings made by different instruments on the same sample of rock. In fact, they represent data for two successive tests for depression on the Hamilton scale, before and after drug therapy.</p>
<!---
Note on source in Hollander: Salsburg (1970): Personal communication (with the coooperation of Pfizer and co, Groton, Conn.)
-->
<p>Table 18-3</p>
<p><strong>Hamilton Depression Scale Values</strong></p>
<table class="table">
<colgroup>
<col style="width: 23%">
<col style="width: 26%">
<col style="width: 26%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"><strong>Patient #</strong></th>
<th style="text-align: left;"><strong>Score Before</strong></th>
<th style="text-align: left;"><strong>Score After</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1 2 3 4 5 6 7 8 9</td>
<td style="text-align: left;">1.83 .50 1.62 2.48 1.68 1.88 1.55 3.06 1.3</td>
<td style="text-align: left;">.878 .647 .598 2.05 1.06 1.29 1.06 3.14 1.29</td>
</tr>
</tbody>
</table>
<p>The task is to perform a test that will help decide whether there is a difference in the depression scores at the two visits (or the performances of the two mechanics). Perform both a bootstrap test and a permutation test, and give some reason for preferring one to the other in principle. How much do they differ in practice?</p>
<p><strong>Exercise 18-2</strong></p>
<p>Thirty-six of 72 (.5) taxis surveyed in Pittsburgh had visible seatbelts. Seventy-seven of 129 taxis in Chicago (.597) had visible seatbelts. Calculate a confidence interval for the difference in proportions, estimated at -.097. (Source: Peskun, Peter H., “A New Confidence Interval Method Based on the Normal Approximation for the Difference of Two Binomial Probabilities,” <em>Journal of the American Statistical Association</em> , 6/93 p.&nbsp;656).</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-chung1958randomization" class="csl-entry" role="listitem">
Chung, James H, and Donald AS Fraser. 1958. <span>“Randomization Tests for a Multivariate Two-Sample Problem.”</span> <em>Journal of the American Statistical Association</em> 53 (283): 729–35. <a href="https://www.jstor.org/stable/pdf/2282050.pdf">https://www.jstor.org/stable/pdf/2282050.pdf</a>.
</div>
<div id="ref-dwass1957modified" class="csl-entry" role="listitem">
Dwass, Meyer. 1957. <span>“Modified Randomization Tests for Nonparametric Hypotheses.”</span> <em>The Annals of Mathematical Statistics</em>, 181–87. <a href="https://www.jstor.org/stable/pdf/2237031.pdf">https://www.jstor.org/stable/pdf/2237031.pdf</a>.
</div>
<div id="ref-efron1993bootstrap" class="csl-entry" role="listitem">
Efron, Bradley, and Robert J Tibshirani. 1993. <span>“An Introduction to the Bootstrap.”</span> In <em>Monographs on Statistics and Applied Probability</em>, edited by David R Cox, David V Hinkley, Nancy Reid, Donald B Rubin, and Bernard W Silverman. Vol. 57. New York: <span>Chapman &amp; Hall</span>.
</div>
<div id="ref-fisher1935design" class="csl-entry" role="listitem">
Fisher, Ronald Aylmer. 1935. <em>The Design of Experiments</em>. 1st ed. Edinburgh: <span>Oliver and Boyd Ltd</span>. <a href="https://archive.org/details/in.ernet.dli.2015.502684">https://archive.org/details/in.ernet.dli.2015.502684</a>.
</div>
<div id="ref-fisher1960design" class="csl-entry" role="listitem">
———. 1960. <em>The Design of Experiments</em>. 7th ed. Edinburgh: <span>Oliver and Boyd Ltd</span>. <a href="https://archive.org/details/designofexperime0000rona_q7u5">https://archive.org/details/designofexperime0000rona_q7u5</a>.
</div>
<div id="ref-hollander1999nonparametric" class="csl-entry" role="listitem">
Hollander, Myles, and Douglas A Wolfe. 1999. <em>Nonparametric Statistical Methods</em>. 2nd ed. Wiley Series in Probability and Statistics: Applied Probability and Statistics. New York: John Wiley &amp; Sons, Inc. <a href="https://archive.org/details/nonparametricsta0000ed2holl">https://archive.org/details/nonparametricsta0000ed2holl</a>.
</div>
<div id="ref-pitman1937significance" class="csl-entry" role="listitem">
Pitman, Edwin JG. 1937. <span>“Significance Tests Which May Be Applied to Samples from Any Populations.”</span> <em>Supplement to the Journal of the Royal Statistical Society</em> 4 (1): 119–30. <a href="https://www.jstor.org/stable/pdf/2984124.pdf">https://www.jstor.org/stable/pdf/2984124.pdf</a>.
</div>
<div id="ref-simon1996effects" class="csl-entry" role="listitem">
Simon, Julian Lincoln, and David M Simon. 1996. <span>“The Effects of Regulations on State Liquor Prices.”</span> <em>Empirica</em> 23: 303–16.
</div>
</div>
</section>
<aside id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Technical Note: The test described in this section is non-parametric and therefore makes no assumptions about the shapes of the distributions, which is good because we would be on soft ground if we assumed normality in the pig-food case, given the sample sizes. This test does not, however, throw away information as do the rank and median tests illustrated earlier. And indeed, this test proves to be more powerful than the other non-parametric tests. After developing this test, I discovered that its general logic follows the tradition of the “randomization” tests, based on an idea by R.A. Fisher <span class="citation" data-cites="fisher1935design fisher1960design">(<a href="references.html#ref-fisher1935design" role="doc-biblioref">1935</a>; <a href="references.html#ref-fisher1960design" role="doc-biblioref">1960, chap. III</a>, section 21)</span> and worked out for the two-sample cases by E.J.G. Pitman <span class="citation" data-cites="pitman1937significance">(<a href="references.html#ref-pitman1937significance" role="doc-biblioref">1937</a>)</span>. But the only earlier mentions of sampling from the universe of possibilities are in M. Dwass <span class="citation" data-cites="dwass1957modified">(<a href="references.html#ref-dwass1957modified" role="doc-biblioref">1957</a>)</span> and J.H. Chung and D. Fraser <span class="citation" data-cites="chung1958randomization">(<a href="references.html#ref-chung1958randomization" role="doc-biblioref">1958</a>)</span>. I am grateful to J. Pratt for bringing the latter literature to my attention.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>This short comment is the tip of the iceberg of an argument that has been going on for 200 years among statisticians. It needs much more discussion to be understandable or persuasive.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>The data are from <em>The Liquor Handbook</em> (1962, p.&nbsp;68). Eight states are omitted for various reasons. For more information, see Simon and Simon <span class="citation" data-cites="simon1996effects">(<a href="references.html#ref-simon1996effects" role="doc-biblioref">1996</a>)</span>.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>Various tests indicate that the difference between the groups of states was highly significant. See Simon and Simon <span class="citation" data-cites="simon1996effects">(<a href="references.html#ref-simon1996effects" role="doc-biblioref">1996</a>)</span>.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>Technical Note: Computing the sum of squared differences renders this test superficially more similar to the analysis of variance but will not alter the results. This test has not been discussed in the statistical literature, to my knowledge, except perhaps for a faint suggestion at the end of Chung and Fraser <span class="citation" data-cites="chung1958randomization">(<a href="references.html#ref-chung1958randomization" role="doc-biblioref">1958</a>)</span>. This and the two-sample test can easily be performed with canned computer programs as well as R. In addition to their advantages of nonparametricity, they are equally efficient and vastly easier to teach and to understand than the t-test and the analysis of variance. Therefore, we believe that these tests should be “treatments of choice,” as the doctors say.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</aside>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./testing_counts_2.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">The Statistics of Hypothesis-Testing with Counted Data, Part 2</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./testing_procedures.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">General Procedures for Testing Hypotheses</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>