<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.51">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Resampling statistics - 21&nbsp; Hypothesis-Testing with Counted Data, Part 1</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./significance.html" rel="next">
<link href="./framing_questions.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

<script type="text/javascript">
  $(document).ready(function() {
    $("table").addClass('lightable-paper lightable-striped lightable-hover')
  });
</script>

<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">


<link rel="stylesheet" href="style.css">
<link rel="stylesheet" href="font-awesome.min.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./testing_counts_1.html"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Hypothesis-Testing with Counted Data, Part 1</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Resampling statistics</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R edition</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface_third.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface to the third edition</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface_second.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface to the second edition</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./resampling_method.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">The resampling method</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./what_is_probability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">What is probability?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./about_technology.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Introducing R and the RStudio notebook</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./resampling_with_code.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Resampling with code</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./resampling_with_code2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">More resampling with code</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sampling_tools.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Tools for samples and sampling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability_theory_1a.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Probability Theory, Part 1</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability_theory_1b.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Probability Theory Part I (continued)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./more_sampling_tools.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Two puzzles and more tools</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability_theory_2_compound.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Probability Theory, Part 2: Compound Probability</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability_theory_3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Probability Theory, Part 3</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability_theory_4_finite.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Probability Theory, Part 4: Estimating Probabilities from Finite Universes</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./sampling_variability.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">On Variability in Sampling</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./monte_carlo.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">The Procedures of Monte Carlo Simulation (and Resampling)</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./standard_scores.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Ranks, Quantiles and Standard Scores</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference_ideas.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">The Basic Ideas in Statistical Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./inference_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Introduction to Statistical Inference</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./point_estimation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Point Estimation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./framing_questions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Framing Statistical Questions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./testing_counts_1.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Hypothesis-Testing with Counted Data, Part 1</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./significance.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">The Concept of Statistical Significance in Testing Hypotheses</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./testing_counts_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">The Statistics of Hypothesis-Testing with Counted Data, Part 2</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./testing_measured.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">The Statistics of Hypothesis-Testing With Measured Data</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./testing_procedures.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">General Procedures for Testing Hypotheses</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./confidence_1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Confidence Intervals, Part 1: Assessing the Accuracy of Samples</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./confidence_2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Confidence Intervals, Part 2: The Two Approaches to Estimating Confidence Intervals</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./reliability_average.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Some Last Words About the Reliability of Sample Averages</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./correlation_causation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Correlation and Causation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./how_big_sample.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">How Large a Sample?</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./bayes_simulation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">Bayesian Analysis by Simulation</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./exercise_solutions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Exercise Solutions</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./acknowlegements.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">Acknowledgements</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./technical_note.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">Technical Note to the Professional Reader</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">21.1</span> Introduction</a></li>
  <li><a href="#should-a-single-sample-of-counted-data-be-considered-different-from-a-benchmark-universe" id="toc-should-a-single-sample-of-counted-data-be-considered-different-from-a-benchmark-universe" class="nav-link" data-scroll-target="#should-a-single-sample-of-counted-data-be-considered-different-from-a-benchmark-universe"><span class="header-section-number">21.2</span> Should a single sample of counted data be considered different from a benchmark universe?</a>
  <ul class="collapse">
  <li><a href="#sec-female-calves" id="toc-sec-female-calves" class="nav-link" data-scroll-target="#sec-female-calves"><span class="header-section-number">21.2.1</span> Example: Does a treatment increase the female calf rate?</a></li>
  <li><a href="#sec-contract-poll" id="toc-sec-contract-poll" class="nav-link" data-scroll-target="#sec-contract-poll"><span class="header-section-number">21.2.2</span> Example: A Public-Opinion Poll</a></li>
  <li><a href="#example-did-the-trump-clinton-poll-indicate-that-trump-would-win" id="toc-example-did-the-trump-clinton-poll-indicate-that-trump-would-win" class="nav-link" data-scroll-target="#example-did-the-trump-clinton-poll-indicate-that-trump-would-win"><span class="header-section-number">21.2.3</span> Example: Did the Trump-Clinton Poll Indicate that Trump Would Win?</a></li>
  <li><a href="#sec-cancer-cures" id="toc-sec-cancer-cures" class="nav-link" data-scroll-target="#sec-cancer-cures"><span class="header-section-number">21.2.4</span> Example: Comparison of Possible Cancer Cure to Placebo</a></li>
  <li><a href="#example-did-attitudes-about-marijuana-change" id="toc-example-did-attitudes-about-marijuana-change" class="nav-link" data-scroll-target="#example-did-attitudes-about-marijuana-change"><span class="header-section-number">21.2.5</span> Example: Did Attitudes About Marijuana Change?</a></li>
  <li><a href="#sec-framingham-example" id="toc-sec-framingham-example" class="nav-link" data-scroll-target="#sec-framingham-example"><span class="header-section-number">21.2.6</span> Example: Infarction and Cholesterol: Framingham Study</a></li>
  <li><a href="#sec-pig-rations" id="toc-sec-pig-rations" class="nav-link" data-scroll-target="#sec-pig-rations"><span class="header-section-number">21.2.7</span> Example: Is One Pig Ration More Effective Than the Other?</a></li>
  <li><a href="#example-do-planet-densities-differ" id="toc-example-do-planet-densities-differ" class="nav-link" data-scroll-target="#example-do-planet-densities-differ"><span class="header-section-number">21.2.8</span> Example: Do Planet Densities Differ?</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">21.3</span> Conclusion</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-testing-counts-one" class="quarto-section-identifier"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Hypothesis-Testing with Counted Data, Part 1</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="introduction" class="level2" data-number="21.1">
<h2 data-number="21.1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">21.1</span> Introduction</h2>
<p>The first task in inferential statistics is to make one or more <em>point estimates</em> — that is, to make one or more statements about <em>how much</em> there is of something we are interested in — including especially the mean and the dispersion. (That work goes under the label “estimation” and is discussed in <a href="point_estimation.html" class="quarto-xref"><span>Chapter&nbsp;19</span></a>.) Frequently the next step, after making such quantitative estimation of the universe from which a sample has been drawn, is to consider whether two or more samples are different from each other, or whether the single sample is different from a specified value; this work goes under the label “hypothesis testing.” We ask: Did something happen? Or: Is there a difference between two universes? These are yes-no questions.</p>
<p>In other cases, the next step is to inquire into the reliability of the estimates; this goes under the label “confidence intervals.” (Some writers include assessing reliability under the rubric of estimation, but I judge it better not to do so).</p>
<p>So: Having reviewed how to convert hypothesis-testing problems into statistically testable questions in <a href="framing_questions.html" class="quarto-xref"><span>Chapter&nbsp;20</span></a>, we now must ask: How does one employ resampling methods to make the statistical test? As is always the case when using resampling techniques, there is no unique series of steps by which to proceed. The crucial criterion in assessing the model is whether it accurately simulates the actual event. With hypothesis-testing problems, any number of models may be correct. Generally speaking, though, the model that makes fullest use of the quantitative information available from the data is the best model.</p>
<p>When attempting to deduce the characteristics of a universe from sample data, or when asking whether a sample was drawn from a particular universe, a crucial issue is whether a “one-tailed test” or a “two-tailed test” should be applied. That is, in examining the results of our resampling experiment based on the benchmark universe, do we examine both ends of the frequency distribution, or just one? If there is strong reason to believe <em>a priori</em> that the difference between the benchmark (null) universe and the sample will be in a given direction — for example if you hypothesize that the sample mean will be <em>smaller</em> than the mean of the benchmark universe — you should then employ a <em>one-tailed test</em> . If you do <em>not</em> have strong basis for such a prediction, use the <em>two-tailed</em> test. As an example, when a scientist tests a new medication, his/her hypothesis would be that the number of patients who get well will be higher in the treated group than in the control group. Thus, s/he applies the one-tailed test. See the text below for more detail on one- and two-tailed tests.</p>
<p>Some language first:</p>
<p><strong>Hypothesis:</strong> In inferential statistics, a statement or claim about a universe that can be tested and that you wish to investigate.</p>
<p><strong>Testing:</strong> The process of investigating the validity of a hypothesis.</p>
<p><strong>Benchmark (or null) hypothesis:</strong> A particular hypothesis chosen for convenience when testing hypotheses in inferential statistics. For example, we could test the hypothesis that there is <em>no difference</em> between a sample and a given universe, or between two samples, or that a parameter is less than or greater than a certain value. The benchmark universe refers to this hypothesis. (The concept of the benchmark or null hypothesis was discussed in <a href="probability_theory_1b.html" class="quarto-xref"><span>Chapter&nbsp;9</span></a> and <a href="framing_questions.html" class="quarto-xref"><span>Chapter&nbsp;20</span></a>.)</p>
<p>Now let us begin the actual statistical testing of various sorts of hypotheses about samples and populations.</p>
</section>
<section id="should-a-single-sample-of-counted-data-be-considered-different-from-a-benchmark-universe" class="level2" data-number="21.2">
<h2 data-number="21.2" class="anchored" data-anchor-id="should-a-single-sample-of-counted-data-be-considered-different-from-a-benchmark-universe"><span class="header-section-number">21.2</span> Should a single sample of counted data be considered different from a benchmark universe?</h2>
<section id="sec-fruitfly" class="level4" data-number="21.2.0.1">
<h4 data-number="21.2.0.1" class="anchored" data-anchor-id="sec-fruitfly"><span class="header-section-number">21.2.0.1</span> Example: Does Irradiation Affect the Sex Ratio in Fruit Flies?</h4>
<p><strong>Where the Benchmark Universe Mean (in this case, the Proportion) is Known, is the Mean (Proportion) of the Population Affected by the Treatment?)</strong></p>
<p>You think you have developed a technique for irradiating the genes of fruit flies so that the sex ratio of the offspring will <em>not</em> be half males and half females. In the first twenty cases you treat, there are fourteen males and six females. Does this experimental result confirm that the irradiation does work?</p>
<p>First convert the scientific question — whether or not the treatment affects the sex distribution — into a probability-statistical question: Is the observed sample likely to have come from a benchmark universe in which the sex ratio is one male to one female? The benchmark (null) hypothesis, then, is that the treatment makes no difference and the sample comes from the one-male-to-one-female universe. Therefore, we investigate <em>how likely a one-to-one universe is to produce a distribution of fourteen or more of just one sex</em>.</p>
<p>A coin has a one-to-one (one out of two) chance of coming up tails. Therefore, we might flip a coin in groups of twenty flips, and count the number of tails in each twenty flips. Or we can use a random number table. The following steps will produce a sound estimate:</p>
<ul>
<li><strong>Step 1.</strong> Let tails = male, heads = female.</li>
<li><strong>Step 2.</strong> Flip twenty coins and count the number of males. If 14 or more males occur, record “yes.” Also, if 6 or fewer males occur, record “yes” because this means we have gotten 14 or more females. Otherwise, record “no.”</li>
<li><strong>Step 3.</strong> Repeat step 2 perhaps 100 times.</li>
<li><strong>Step 4.</strong> Calculate the proportion “yes” in the 100 trials. This proportion estimates the probability that a fruit-fly population with a propensity to produce 50 percent males will by chance produce as many as 14 or as few as 6 males in a sample of 20 flies.</li>
</ul>
<div class="cell" data-layout-align="center" data-hash="testing_counts_1_cache/html/unnamed-chunk-1_cd46a8a22952ebd5cfe6b71b06e92e38">
<div class="cell-output-display">
<div id="tbl-fruitfly-trials" class="anchored">
<table class="lightable-paper lightable-striped lightable-hover table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Table&nbsp;21.1: Results from 25 random trials for Fruitfly problem</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Trial no</th>
<th style="text-align: right;" data-quarto-table-cell-role="th"># of tails</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">&gt;=14 or &lt;=6</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">12</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">12</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">11</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">10</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">11</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">Yes</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;">Yes</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">10</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="odd">
<td style="text-align: right;">11</td>
<td style="text-align: right;">11</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: right;">12</td>
<td style="text-align: right;">12</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="odd">
<td style="text-align: right;">13</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: right;">14</td>
<td style="text-align: right;">15</td>
<td style="text-align: left;">Yes</td>
</tr>
<tr class="odd">
<td style="text-align: right;">15</td>
<td style="text-align: right;">13</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: right;">16</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="odd">
<td style="text-align: right;">17</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: right;">18</td>
<td style="text-align: right;">10</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="odd">
<td style="text-align: right;">19</td>
<td style="text-align: right;">10</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: right;">20</td>
<td style="text-align: right;">9</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="odd">
<td style="text-align: right;">21</td>
<td style="text-align: right;">12</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: right;">22</td>
<td style="text-align: right;">11</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="odd">
<td style="text-align: right;">23</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;">Yes</td>
</tr>
<tr class="even">
<td style="text-align: right;">24</td>
<td style="text-align: right;">16</td>
<td style="text-align: left;">Yes</td>
</tr>
<tr class="odd">
<td style="text-align: right;">25</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;">No</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p><a href="#tbl-fruitfly-trials" class="quarto-xref">Table&nbsp;<span>21.1</span></a> shows the results obtained in 25 trials of twenty flips each. In two of the twenty-five trials (8 percent) there were fourteen or more tails, which we call “males,” and in three of the 25 trials (12 percent) there six or fewer tails, meaning there were fourteen or more heads (“females”). We can therefore estimate that, even if the treatment does <em>not</em> affect the sex and the births over a long period really are one to one, five out of twenty-five times (20 percent) we would get fourteen or more of one sex or the other. Therefore, finding fourteen males out of 20 births is not overwhelming evidence that the treatment has any effect, even though the result is suggestive.</p>
<p>How accurate is the estimate? Seventy-five more trials were made, and of the 100 trials nine contained fourteen or more “males” (9 percent), and 8 trials contained fourteen or more “females” (8 percent), a total of 17 percent. So the first twenty-five trials gave a fairly reliable indication. As a matter of fact, analytically-based computation (not explained here) shows that the probability of getting fourteen or more females out of twenty births is .057 and, of course, the same for fourteen or more males from a one-to-one universe, implying a total probability of .114 of getting fourteen or more males <em>or</em> females.</p>
<p>Now let us obtain larger and more accurate simulation samples with the computer. The key step in the R notebook below represents male fruit flies with the string <code>'male'</code> and female fruit flies with the string <code>'female'</code>. The <span class="r"><code>sample</code></span> function is then used to generate 20 of these strings with an equal probability that either string is selected. This simulates randomly choosing 20 fruit flies on the benchmark assumption — the “null hypothesis” — that each fruit fly has an equal chance of being a male or female. Now we want to discover the chances of getting more than 13 (i.e., 14 or more) males or more than 13 females under these conditions. So we use <span class="r"><code>sum</code></span> to count the number of males in each random sample and then store this value in the <code>scores</code> vector of this number for each sample. We repeat these steps 10,000 times.</p>
<p>After ten thousand samples have been drawn, we count (<code>sum</code>) how often there were more than 13 males and then count the number of times there were fewer than 7 males (because if there were fewer than 7 males there must have been more than 13 females). When we add the two results together we have the probability that the results obtained from the sample of irradiated fruit flies would be obtained from a random sample of fruit flies.</p>
<div class="notebook" name="fruit_fly" title="Fruit fly simulation">
<p>Start of <code>fruit_fly</code> notebook</p>
<div class="nb-links">
<a class="notebook-link" href="notebooks/fruit_fly.Rmd">Download notebook</a>
<a class="interact-button" href="https://resampling-stats.github.io/python-book/jupyterlite/lab/index.html?path=/fruit_fly.Rmd">Interact</a>
</div>

<div class="cell" data-layout-align="center" data-hash="testing_counts_1_cache/html/unnamed-chunk-5_fc1859fd6af4e9fa84d5979eb4393db1">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set the number of trials</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>n_trials <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co"># set the sample size for each trial</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a>sample_size <span class="ot">&lt;-</span> <span class="dv">20</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co"># An empty array to store the trials</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>scores <span class="ot">&lt;-</span> <span class="fu">numeric</span>(n_trials)</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Do 10000 trials</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n_trials) {</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Generate 20 simulated fruit flies, where each has an equal chance of being</span></span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>    <span class="co"># male or female</span></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>    a <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">'male'</span>, <span class="st">'female'</span>),</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>                <span class="at">size=</span>sample_size,</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>                <span class="at">prob=</span><span class="fu">c</span>(<span class="fl">0.5</span>, <span class="fl">0.5</span>),</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>                <span class="at">replace=</span><span class="cn">TRUE</span>)</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>    <span class="co"># count the number of males in the sample</span></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>    b <span class="ot">&lt;-</span> <span class="fu">sum</span>(a <span class="sc">==</span> <span class="st">'male'</span>)</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>    <span class="co"># store the result of this trial</span></span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>    scores[i] <span class="ot">&lt;-</span> b</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Produce a histogram of the trial results</span></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>title_of_plot <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">"Number of males in"</span>, n_trials, <span class="st">" samples of </span><span class="sc">\n</span><span class="st">"</span>, sample_size, <span class="st">" simulated fruit flies"</span>)</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(scores, <span class="at">xlab=</span><span class="st">'Number of Males'</span>, <span class="at">main=</span>title_of_plot)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="testing_counts_1_files/figure-html/unnamed-chunk-5-1.png" class="img-fluid figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<p>In the histogram above, we see that in 16 percent of the trials, the number of males was 14 or more, or 6 or fewer. Or instead of reading the results from the histogram, we can calculate the result by tacking on the following commands to the above program:</p>
<div class="cell" data-layout-align="center" data-hash="testing_counts_1_cache/html/unnamed-chunk-7_5cd3bc4c20ea3bb41778d698412b492e">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Determine the number of trials in which we had 14 or more males.</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>j <span class="ot">&lt;-</span> <span class="fu">sum</span>(scores <span class="sc">&gt;=</span> <span class="dv">14</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Determine the number of trials in which we had 6 or fewer males.</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="fu">sum</span>(scores <span class="sc">&lt;=</span> <span class="dv">6</span>)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Add the two results together.</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> j <span class="sc">+</span> k</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert to a proportion.</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>mm <span class="ot">&lt;-</span> m<span class="sc">/</span>n_trials</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Print the results.</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(mm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.121</code></pre>
</div>
</div>
<p>End of <code>fruit_fly</code> notebook</p>
</div>
<!---
End of notebook
-->
<p>Notice that the strength of the evidence for the effectiveness of the radiation treatment depends upon the original question: whether or not the treatment had <em>any</em> effect on the sex of the fruit fly, which is a two-tailed question. If there were reason to believe at the start that the treatment could increase <em>only</em> the number of <em>males</em> , then we would focus our attention on the result that in only two of the twenty-five trials were fourteen or more males. There would then be only a 2/25 = 0.08 probability of getting the observed results by chance if the treatment really has no effect, rather than the weaker odds against obtaining fourteen or more of <em>either</em> males or females.</p>
<p>Therefore, whether you decide to figure the odds of just fourteen or more males (what is called a “one-tail test”) or the odds for fourteen or more males <em>plus</em> fourteen or more females (a “two-tail test”), depends upon your advance knowledge of the subject. If you have no reason to believe that the treatment will have an effect <em>only</em> in the direction of creating more males and if you figure the odds for the one-tail test anyway, then you will be kidding yourself. Theory comes to bear here. If you have a strong hypothesis, deduced from a strong theory, that there will be more males, then you should figure one-tail odds, but if you have no such theory you should figure the weaker two-tail odds.<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a></p>
<p>In the case of the next problem concerning calves, we shall see that a one-tail test is appropriate because we have no interest in producing more male calves. Before leaving this example, let us review our intellectual strategy in handling the problem. First we observe a result (14 males in 20 flies) which differs from the proportion of the benchmark population (50 percent males). Because we have treated this sample with irradiation and observed a result that differs from the untreated benchmark-population’s mean, we speculate that the irradiation caused the sample to differ from the untreated population. We wish to check on whether this speculation is correct.</p>
<p>When asking whether this speculation is correct, we are implicitly asking whether future irradiation would also produce a proportion of males higher than 50 percent. That is, we are implicitly asking whether irradiated flies would produce more samples with male proportions as high as 14/20 than would occur by chance in the absence of irradiation.</p>
<p>If samples as far away as 14/20 from the benchmark population mean of 10/20 would occur frequently by chance, then we would not be impressed with that experimental evidence as proof that irradiation does affect the sex ratio. Hence we set up a model that will tell us the frequency with which samples of 14 or more males out of 20 births would be observed by chance. Carrying out the resampling procedure tells us that perhaps a tenth of the time such samples would be observed by chance. That is not extremely frequent, but it is not infrequent either. Hence we would probably conclude that the evidence is provocative enough to justify further experimentation, but not so strong that we should immediately believe in the truth of this speculation.</p>
<p>The logic of attaching meaning to the probabilistic outcome of a test of a hypothesis is discussed in <a href="significance.html" class="quarto-xref"><span>Chapter&nbsp;22</span></a>. There also is more about the concept of the level of significance in <a href="significance.html" class="quarto-xref"><span>Chapter&nbsp;22</span></a>.</p>
<p>Because of the great importance of this sort of case, which brings out the basic principles particularly clearly, let us consider another example:</p>
</section>
<section id="sec-female-calves" class="level3" data-number="21.2.1">
<h3 data-number="21.2.1" class="anchored" data-anchor-id="sec-female-calves"><span class="header-section-number">21.2.1</span> Example: Does a treatment increase the female calf rate?</h3>
<p><strong>What is the probability that among 10 calves born, 9 or more will be female?</strong></p>
<p>Let’s consider this question in the context of a set of queries for performing statistical inference that will be discussed further in <a href="testing_procedures.html" class="quarto-xref"><span>Chapter&nbsp;25</span></a>.</p>
<p><strong><em>The question</em></strong>: (From <span class="citation" data-cites="hodges1970basic">Hodges Jr and Lehmann (<a href="references.html#ref-hodges1970basic" role="doc-biblioref">1970</a>)</span>): Female calves are more valuable than males. A bio-engineer claims to be able to cause more females to be born than the expected 50 percent rate. He conducts his procedure, and nine females are born out of the next 10 pregnancies among the treated cows. Should you believe his claim? That is, what is the probability of a result this (or more) surprising occurring by chance if his procedure has no effect? In this problem, we assume that on average 100 of 206 births are female, in contrast to the 50-50 benchmark universe in the previous problem.</p>
<p><strong><em>What is the purpose of the work?</em></strong>: Female calves are more valuable than male calves.</p>
<p><strong><em>Statistical inference?</em></strong>: Yes.</p>
<p><strong><em>Confidence interval or Test of hypothesis?</em></strong>: Test of hypothesis.</p>
<p><strong><em>Will you state the costs and benefits of various outcomes, or a loss function?</em></strong>: Yes. One need only say that the benefits are very large, and if the results are promising, it is worth gathering more data to confirm results.</p>
<p><strong><em>How many samples of data are part of the hypothesis test?</em></strong>: One.</p>
<p><strong><em>What is the size of the first sample about which you wish to make significance statements?</em></strong>: Ten.</p>
<p><strong><em>What comparison(s) to make?</em></strong>: Compare the sample to the benchmark universe.</p>
<p><strong><em>What is the benchmark universe</em></strong>: <strong>that embodies the null hypothesis?</strong> 100/206 female.</p>
<p><strong><em>Which symbols for the observed entities?</em></strong>: Balls in bucket, or numbers.</p>
<p><strong><em>What values or ranges of values?</em></strong>: We could write numbers 1 through 206 on pieces of paper, and take numbers 1-100 as “male” and 101-206 as “female”. Or we could use some other mechanism to give us a 100/206 chance of any one calf being female.</p>
<p><strong><em>Finite or infinite universe?</em></strong>: Infinite.</p>
<p><strong><em>Which sample(s) do you wish to compare to which, or to the null universe (and perhaps to the alternative universe)?</em></strong>: Ten calves.</p>
<p><strong><em>What procedure to produce the sample entities?</em></strong>: Sampling with replacement.</p>
<p><strong><em>Simple (single step) or complex (multiple “if” drawings)?</em></strong>: Can think of it either way.</p>
<p><strong><em>What to record as the outcome of each resample trial?</em></strong>: The proportion (or number) of females.</p>
<p><strong><em>What is the criterion to be used in the test?</em></strong>: The probability that in a sample of ten calves, nine (or more) females would be drawn by chance from the benchmark universe of 100/206 females.</p>
<p><strong><em>“One tail” or “two tail” test?</em></strong>: One tail, because the farmer is only interested in females. Finding a large proportion of males would not be of interest; it would not cause rejecting the null hypothesis.</p>
<p>The actual computation of probability may be done in several ways, as discussed earlier for four children and for ten cows. Conventional methods are discussed for comparison in <a href="testing_procedures.html" class="quarto-xref"><span>Chapter&nbsp;25</span></a>. Here is the resampling solution in R.</p>
<div class="notebook" name="female_calves" title="Female calf numbers simulation">
<p>Start of <code>female_calves</code> notebook</p>
<div class="nb-links">
<a class="notebook-link" href="notebooks/female_calves.Rmd">Download notebook</a>
<a class="interact-button" href="https://resampling-stats.github.io/python-book/jupyterlite/lab/index.html?path=/female_calves.Rmd">Interact</a>
</div>

<div class="cell" data-layout-align="center" data-hash="testing_counts_1_cache/html/unnamed-chunk-9_7e7e11c0f3a64efc1defcefd6253672f">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set the number of trials.</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>n_trials <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Set the size of each sample.</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>sample_size <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Probability of any one calf being female.</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>p_female <span class="ot">&lt;-</span> <span class="dv">100</span> <span class="sc">/</span> <span class="dv">206</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a><span class="co"># A vector to store the results.</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>scores <span class="ot">&lt;-</span> <span class="fu">numeric</span>(n_trials)</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a><span class="co"># for 10000 repeats.</span></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n_trials) {</span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>    a <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">'female'</span>, <span class="st">'male'</span>),</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>                <span class="at">size=</span>sample_size,</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>                <span class="at">prob=</span><span class="fu">c</span>(p_female, <span class="dv">1</span> <span class="sc">-</span> p_female),</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>                <span class="at">replace=</span><span class="cn">TRUE</span>)</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>    b <span class="ot">&lt;-</span> <span class="fu">sum</span>(a <span class="sc">==</span> <span class="st">'female'</span>)</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Store the result of the current trial.</span></span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>    scores[i] <span class="ot">&lt;-</span> b</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot a histogram of the scores.</span></span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a>title_of_plot <span class="ot">&lt;-</span> <span class="fu">paste0</span>(<span class="st">"Number of females in"</span>, n_trials, <span class="st">" samples of </span><span class="sc">\n</span><span class="st">"</span>, sample_size, <span class="st">" simulated calves"</span>)</span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(scores, <span class="at">xlab =</span> <span class="st">'Number of Females'</span>, <span class="at">main=</span>title_of_plot)</span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a><span class="co"># Count the number of scores that were greater than or equal to 9.</span></span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="fu">sum</span>(scores <span class="sc">&gt;=</span> <span class="dv">9</span>)</span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a><span class="co"># Express as a proportion.</span></span>
<span id="cb4-34"><a href="#cb4-34" aria-hidden="true" tabindex="-1"></a>kk <span class="ot">&lt;-</span> k <span class="sc">/</span> n_trials</span>
<span id="cb4-35"><a href="#cb4-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-36"><a href="#cb4-36" aria-hidden="true" tabindex="-1"></a><span class="co"># Show the proportion.</span></span>
<span id="cb4-37"><a href="#cb4-37" aria-hidden="true" tabindex="-1"></a><span class="fu">message</span>(<span class="st">"Probability of 9 or 10 females occurring by chance: "</span>, kk)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Probability of 9 or 10 females occurring by chance: 0.0106</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="testing_counts_1_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<p>We read from the result in variable <code>kk</code> that the probability of 9 or 10 females occurring by chance is a bit more than one percent.</p>
<p>End of <code>female_calves</code> notebook</p>
</div>
<!---
End of calves notebook.
-->
</section>
<section id="sec-contract-poll" class="level3" data-number="21.2.2">
<h3 data-number="21.2.2" class="anchored" data-anchor-id="sec-contract-poll"><span class="header-section-number">21.2.2</span> Example: A Public-Opinion Poll</h3>
<p><strong>Is the Proportion of a Population Greater Than a Given Value?</strong></p>
<p>A municipal official wants to determine whether a majority of the town’s residents are for or against the awarding of a high-speed internet contract, and she asks you to take a poll. You judge that the voter registration records are a fair representation of the universe in which the politician was interested, and you therefore decided to interview a random selection of registered voters. Of a sample of fifty people who expressed opinions, thirty said “yes” they were for the plan and twenty said “no,” they were against it. How conclusively do the results show that the people in town want this internet contract?</p>
<p>Now comes some necessary subtle thinking in the interpretation of what seems like a simple problem. Notice that our aim in the analysis is to avoid the mistake of saying that the town favors the plan when in fact it does not favor the plan. Our chance of making this mistake is greatest when the voters are evenly split, so we choose as the benchmark (null) hypothesis that 50 percent of the town does not want the plan. This statement really means that “50 percent or more do not want the plan.” We could assess the probability of obtaining our result from a population that is split (say) 52-48 against, but such a probability would necessarily be even smaller, and we are primarily interested in assessing the maximum probability of being wrong. If the maximum probability of error turns out to be inconsequential, then we need not worry about less likely errors.</p>
<p>This problem is very much like the one-group fruit fly irradiation problem above. The only difference is that now we are comparing the observed sample against an arbitrary value of 50 percent (because that is the break-point in a situation where the majority decides) whereas in <a href="#sec-fruitfly" class="quarto-xref"><span>Section&nbsp;21.2.0.1</span></a> we compared the observed sample against the normal population proportion (also 50 percent, because that is the normal proportion of males). But it really does not matter <em>why</em> we are comparing the observed sample to the figure of 50 percent; the procedure is the same in both cases. (Please notice that there is nothing special about the 50 percent figure; the same procedure would be followed for 20 percent or 85 percent.)</p>
<p>In brief, we a) take two pieces of paper, write “Yes” on one and “No” on the other, put them in a bucket b) draw a piece of paper from the bucket, record whether it was “Yes” or “No”, replace, and repeat 50 times c) count the number of “yeses” and “noes” in the fifty draws, c) repeat for perhaps a hundred trials, then d) count the proportion of the trials in which a 50-50 universe would produce thirty or more “yes” answers.</p>
<p>In operational steps, the procedure is as follows:</p>
<ul>
<li><strong>Step 1.</strong> “1-5” = no, “6-0” = yes.</li>
<li><strong>Step 2.</strong> In 50 random numbers, count the “yeses,” and record “false positive” if 30 or more “yeses.”</li>
<li><strong>Step 3.</strong> Repeat step 2 perhaps 100 times.</li>
<li><strong>Step 4.</strong> Calculate the proportion of experimental trials showing “false positive.” This estimates the probability that as many as 30 “yeses” would be observed by chance in a sample of 50 people <em>if</em> half (or more) are really against the plan.</li>
</ul>
<div class="cell" data-layout-align="center" data-hash="testing_counts_1_cache/html/unnamed-chunk-11_427953ae3e741fe89e5bf42e9f8a6176">
<div class="cell-output-display">
<div id="tbl-contract-trials" class="anchored">
<table class="lightable-paper lightable-striped lightable-hover table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Table&nbsp;21.2: Results from 20 random trials for contract poll problem</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Trial no</th>
<th style="text-align: right;" data-quarto-table-cell-role="th"># of "Noes"</th>
<th style="text-align: right;" data-quarto-table-cell-role="th"># of "Yeses"</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">&gt;= 30 "Yeses"</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">25</td>
<td style="text-align: right;">25</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">27</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">32</td>
<td style="text-align: left;">+</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">17</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">32</td>
<td style="text-align: right;">18</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">23</td>
<td style="text-align: right;">27</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">22</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">22</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">28</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">30</td>
<td style="text-align: right;">20</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: right;">11</td>
<td style="text-align: right;">22</td>
<td style="text-align: right;">28</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: right;">12</td>
<td style="text-align: right;">28</td>
<td style="text-align: right;">22</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: right;">13</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">24</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: right;">14</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">30</td>
<td style="text-align: left;">+</td>
</tr>
<tr class="odd">
<td style="text-align: right;">15</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">23</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: right;">16</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">31</td>
<td style="text-align: left;">+</td>
</tr>
<tr class="odd">
<td style="text-align: right;">17</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">24</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: right;">18</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">23</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: right;">19</td>
<td style="text-align: right;">20</td>
<td style="text-align: right;">30</td>
<td style="text-align: left;">+</td>
</tr>
<tr class="even">
<td style="text-align: right;">20</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">26</td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>In <a href="#tbl-contract-trials" class="quarto-xref">Table&nbsp;<span>21.2</span></a>, we see the results of twenty trials; 4 of 20 times (20 percent), 30 or more “yeses” were observed by chance. So our “significance level” or “probability value” is 20 percent, which is normally too high to feel confident that our poll results are reliable. This is the probability that as many as thirty of fifty people would say “yes” by chance if the population were “really” split evenly. (If the population were split so that <em>more</em> than 50 percent were against the plan, the probability would be even <em>less</em> that the observed results would occur by chance. In this sense, the benchmark hypothesis is conservative). On the other hand, if we had been counting the number of times there are 30 or more “No” votes that, in our setup, have the same odds as to 30 or more “Yes” votes, there would have been three. This indicates how samples can vary just by chance.</p>
<p>Taken together, the evidence suggests that the official would be wise not to place very much confidence in the poll results, but rather ought to act with caution or else take a larger sample of voters.</p>
<div class="notebook" name="contract_poll" title="Contract poll simulation">
<p>Start of <code>contract_poll</code> notebook</p>
<div class="nb-links">
<a class="notebook-link" href="notebooks/contract_poll.Rmd">Download notebook</a>
<a class="interact-button" href="https://resampling-stats.github.io/python-book/jupyterlite/lab/index.html?path=/contract_poll.Rmd">Interact</a>
</div>

<p>This R notebook generates samples of 50 simulated voters on the assumption that only 50 percent are in favor of the contract. Then it counts (<code>sum</code>s) the number of samples where over 29 (30 or more) of the 50 respondents said they were in favor of the contract. (That is, we use a “one-tailed test.”) The result in the <code>kk</code> variable is the chance of a “false positive,” that is, 30 or more people saying they favor a contract when support for the proposal is actually split evenly down the middle.</p>
<div class="cell" data-layout-align="center" data-hash="testing_counts_1_cache/html/unnamed-chunk-13_792ba0f227779e59c7d4822a6dc8848e">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We will do 10,000 iterations.</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Make an array of integers to store the "Yes" counts.</span></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>yeses <span class="ot">&lt;-</span> <span class="fu">numeric</span>(n)</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n) {</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    answers <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">'No'</span>, <span class="st">'Yes'</span>), <span class="at">size=</span><span class="dv">50</span>, <span class="at">replace=</span><span class="cn">TRUE</span>)</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>    yeses[i] <span class="ot">&lt;-</span> <span class="fu">sum</span>(answers <span class="sc">==</span> <span class="st">'Yes'</span>)</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Produce a histogram of the trial results.</span></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Use integer bins for histogram, from 10 through 40.</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(yeses, <span class="at">breaks=</span><span class="dv">10</span><span class="sc">:</span><span class="dv">40</span>,</span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">'Number of yes votes out of 50, in null universe'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="testing_counts_1_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<p>In the histogram above, we see that about 11 percent of our trials had 30 or more voters in favor, despite the fact that they were drawn from a population that was split 50-50. R will calculate this proportion directly if we add the following commands to the above:</p>
<div class="cell" data-layout-align="center" data-hash="testing_counts_1_cache/html/unnamed-chunk-15_0b5e8e80646a9cb1d9dc5aed3342e47e">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="fu">sum</span>(yeses <span class="sc">&gt;=</span> <span class="dv">30</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>kk <span class="ot">&lt;-</span> k <span class="sc">/</span> n</span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="fu">message</span>(<span class="st">'Proportion &gt;= 30: '</span>, <span class="fu">round</span>(kk, <span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Proportion &gt;= 30: 0.1</code></pre>
</div>
</div>
<p>End of <code>contract_poll</code> notebook</p>
</div>
<!---
End of contract_poll notebook.
-->
<p>The section above discusses testing hypotheses about a single sample of counted data relative to a benchmark universe. This section discusses the issue of whether <em>two</em> samples with counted data should be considered the same or different.</p>
</section>
<section id="example-did-the-trump-clinton-poll-indicate-that-trump-would-win" class="level3" data-number="21.2.3">
<h3 data-number="21.2.3" class="anchored" data-anchor-id="example-did-the-trump-clinton-poll-indicate-that-trump-would-win"><span class="header-section-number">21.2.3</span> Example: Did the Trump-Clinton Poll Indicate that Trump Would Win?</h3>
<div class="notebook" name="trump_clinton" title="Trump/Clinton poll simulation">
<p>Start of <code>trump_clinton</code> notebook</p>
<div class="nb-links">
<a class="notebook-link" href="notebooks/trump_clinton.Rmd">Download notebook</a>
<a class="interact-button" href="https://resampling-stats.github.io/python-book/jupyterlite/lab/index.html?path=/trump_clinton.Rmd">Interact</a>
</div>

<p>What is the probability that a sample outcome such as actually observed (840 Trump, 660 Clinton) would occur by chance if Clinton is “really” ahead — that is, if Clinton has 50 percent (or more) of the support? To restate in sharper statistical language: What is the probability that the observed sample or one even more favorable to Trump would occur if the universe has a mean of 50 percent or below?</p>
<p>Here is a procedure that responds to that question:</p>
<ol type="1">
<li>Create a benchmark universe with one ball marked “Trump” and another marked “Clinton”</li>
<li>Draw a ball, record its marking, and replace. (We sample with replacement to simulate the practically-infinite population of U. S. voters.)</li>
<li>Repeat step 2 1500 times and count the number of “Trump”s. If 840 or greater, record “Y”; otherwise, record “N.”</li>
<li>Repeat steps 3 and 4 perhaps 1000 or 10,000 times, and count the number of “Y”s. The outcome estimates the probability that 840 or more Trump choices would occur if the universe is “really” half or more in favor of Clinton.</li>
</ol>
<p>This procedure may be done as follows with R.</p>
<div class="cell" data-layout-align="center" data-hash="testing_counts_1_cache/html/unnamed-chunk-17_99d862dec6bcf2067e243fd03d49a93b">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Number of repeats we will run.</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Make an array to store the counts.</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>trumps <span class="ot">&lt;-</span> <span class="fu">numeric</span>(n)</span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n) {</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>    votes <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">'Trump'</span>, <span class="st">'Clinton'</span>), <span class="at">size=</span><span class="dv">1500</span>, <span class="at">replace=</span><span class="cn">TRUE</span>)</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>    trumps[i] <span class="ot">&lt;-</span> <span class="fu">sum</span>(votes <span class="sc">==</span> <span class="st">'Trump'</span>)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Integer bins from 670 through 830 in steps of 5.</span></span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(trumps, <span class="at">breaks=</span><span class="fu">seq</span>(<span class="dv">670</span>, <span class="dv">830</span>, <span class="at">by=</span><span class="dv">5</span>),</span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">'Number of Trump voters of 1500 in null-world simulation'</span>)</span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a><span class="co"># How often &gt;= 840 Trump votes in random draw?</span></span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="fu">sum</span>(trumps <span class="sc">&gt;=</span> <span class="dv">840</span>)</span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a><span class="co"># As a proportion of simulated resamples.</span></span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>kk <span class="ot">&lt;-</span> k <span class="sc">/</span> n</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a><span class="fu">message</span>(<span class="st">'Proportion voting for Trump: '</span>, kk)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Proportion voting for Trump: 0</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="testing_counts_1_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<p>The value for <code>kk</code> is our estimate of the probability that Trump’s “victory” in the sample would occur by chance if he really were behind. In this case, our probability estimate is less than 1 in 10,000 (&lt; 0.0001).</p>
<p>End of <code>trump_clinton</code> notebook</p>
</div>
<!---
End of Trump / Clinton notebook.
-->
<!---
The results of the various runs may be seen in the histogram and printout
following.

**Bin Center Freq Pct Cum Pct**

  ------- ----- ------ ------
  0.465   4     0.4    0.4
  0.47    14    1.4    1.8
  0.475   28    2.8    4.6
  0.48    46    4.6    9.2
  0.485   97    9.7    18.9
  0.49    106   10.6   29.5
  0.495   159   15.9   45.4
  0.5     121   12.1   57.5
  0.505   157   15.7   73.2
  0.51    102   10.2   83.4
  0.515   75    7.5    90.9
  0.52    39    3.9    94.8
  0.525   35    3.5    98.3
  0.53    11    1.1    99.4
  0.535   5     0.5    99.9
  0.54    1     0.1    100
  ------- ----- ------ ------
-->
</section>
<section id="sec-cancer-cures" class="level3" data-number="21.2.4">
<h3 data-number="21.2.4" class="anchored" data-anchor-id="sec-cancer-cures"><span class="header-section-number">21.2.4</span> Example: Comparison of Possible Cancer Cure to Placebo</h3>
<p><strong>Do Two Binomial Populations Differ in Their Proportions</strong>.</p>
<p><a href="#sec-fruitfly" class="quarto-xref"><span>Section&nbsp;21.2.0.1</span></a> used an observed sample of male and female fruitflies to test the benchmark (null) hypothesis that the flies came from a universe with a one-to-one sex ratio, and the poll data problem also compared results to a 50-50 hypothesis. The calves problem also compared the results to a single benchmark universe — a proportion of 100/206 females. Now we want to compare <em>two samples with each other</em> , rather than comparing one sample with a hypothesized universe. That is, in this example we are not comparing one sample to a benchmark universe, but rather asking whether <em>both</em> samples come from the <em>same</em> universe. The universe from which both samples come, <em>if</em> both belong to the same universe, may be thought of as the benchmark universe, in this case.</p>
<p>The scientific question is whether pill P cures a rare cancer. A researcher gave pill P to six patients selected randomly from a group of twelve cancer patients; of the six, five got well. He gave an inactive placebo to the other six patients, and two of them got well. Does the evidence justify a conclusion that the pill has a curative effect?</p>
<p>(An identical statistical example would serve for an experiment on methods of teaching reading to children. In such a situation the researcher would respond to inconclusive results by running the experiment on more subjects, but in cases like the cancer-pill example the researcher often cannot obtain more subjects.)</p>
<p>We can answer the stated question by <em>combining</em> the two samples and testing both samples against the resulting combined universe. In this case, the universe is twelve subjects, seven (5 + 2) of whom got well. How likely would such a universe produce two samples as far apart as five of six, and two of six, patients who get well? In other words, how often will two samples of six subjects, each drawn from a universe in which 7/12 of the patients get well, be as far apart as 5 - 2 = 3 patients in favor of the sample designated “pill”? This is obviously a one-tail test, for we have no reason to believe that the pill group might do <em>less</em> well than the placebo group.</p>
<p>We might construct a twelve-sided die, seven of whose sides are marked “get well.” Or put 12 pieces of paper in a bucket, seven with “get well” and five with “not well”. Or we would use pairs of numbers from the random-number table, with numbers “01-07” corresponding to get well, numbers “08-12” corresponding to “not get well,” and all other numbers omitted. (If you wish to save time, you can work out a system that uses more numbers and skips fewer, but that is up to you.) Designate the first six subjects “pill” and the next six subjects “placebo.”</p>
<p>The specific procedure might be as follows:</p>
<ul>
<li><strong>Step 1.</strong> Write “get well” on seven pieces of paper, “not well” on another five. Put the 12 pieces of paper into a bucket.</li>
<li><strong>Step 2.</strong> Select two groups, “pill” and “placebo”, each with six random draws (with replacement) from the 12 pieces of paper.</li>
<li><strong>Step 3.</strong> Record how many “get well” in each group.</li>
<li><strong>Step 4.</strong> Subtract the result in group “placebo” from that in group “pill” (the difference may be negative).</li>
<li><strong>Step 5.</strong> Repeat steps 1-4 perhaps 100 times.</li>
<li><strong>Step 6.</strong> Compute the proportion of trials in which the pill does better by three or more cases.</li>
</ul>
<div class="cell" data-layout-align="center" data-hash="testing_counts_1_cache/html/unnamed-chunk-19_d776bf40800a7d9b2a849998eb5e7f97">
<div class="cell-output-display">
<div id="tbl-pill-trials" class="anchored">
<table class="lightable-paper lightable-striped lightable-hover table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Table&nbsp;21.3: Results from 25 random trials for pill/placebo</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Trial no</th>
<th style="text-align: right;" data-quarto-table-cell-role="th"># of pill cures</th>
<th style="text-align: right;" data-quarto-table-cell-role="th"># of placebo cures</th>
<th style="text-align: right;" data-quarto-table-cell-role="th">Difference</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">-4</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">-3</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">-2</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">-1</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">-1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">11</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: right;">12</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">-1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">13</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">-3</td>
</tr>
<tr class="even">
<td style="text-align: right;">14</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">-1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">15</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: right;">16</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: right;">17</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">18</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">19</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">20</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: right;">21</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">-2</td>
</tr>
<tr class="even">
<td style="text-align: right;">22</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: right;">23</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">24</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">-1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">25</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p>In the trials shown in <a href="#tbl-pill-trials" class="quarto-xref">Table&nbsp;<span>21.3</span></a>, in two cases (8 percent) the difference between the randomly-drawn groups is three cases or greater. Apparently it is <em>somewhat</em> unusual — it happens 8 percent of the time — for this universe to generate “pill” samples in which the number of recoveries exceeds the number in the “placebo” samples by three or more. Therefore the answer to the scientific question, based on these samples, is that there is <em>some</em> reason to think that the medicine does have a favorable effect. But the investigator might sensibly await more data before reaching a firm conclusion about the pill’s efficiency, given the 8 percent probability.</p>
<div class="notebook" name="pill_placebo" title="Cures for pill vs placebo">
<p>Start of <code>pill_placebo</code> notebook</p>
<div class="nb-links">
<a class="notebook-link" href="notebooks/pill_placebo.Rmd">Download notebook</a>
<a class="interact-button" href="https://resampling-stats.github.io/python-book/jupyterlite/lab/index.html?path=/pill_placebo.Rmd">Interact</a>
</div>

<p>Now for a R solution. Again, the benchmark hypothesis is that pill P has no effect, and we ask how often, on this assumption, the results that were obtained from the actual test of the pill would occur by chance.</p>
<p>Given that in the test 7 of 12 patients overall got well, the benchmark hypothesis assumes 7/12 to be the chances of any random patient being cured. We generate two similar samples of 6 patients, both taken from the same universe composed of the combined samples — the bootstrap procedure. We count (<code>sum</code>) the number who are “get well” in each sample. Then we subtract the number who got well in the “pill” sample from the number who got well in the “no-pill” sample. We record the resulting difference for each trial in the variable <code>pill_betters</code>.</p>
<p>In the actual test, 3 more patients got well in the sample given the pill than in the sample given the placebo. We therefore count how many of the trials yield results where the difference between the sample given the pill and the sample not given the pill was greater than 2 (equal to or greater than 3). This result is the probability that the results derived from the actual test would be obtained from random samples drawn from a population which has a constant cure rate, pill or no pill.</p>
<div class="cell" data-layout-align="center" data-hash="testing_counts_1_cache/html/unnamed-chunk-21_edf5200e24d1ab390d50728832ebefad">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># The bucket with the pieces of paper.</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>options <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">'get well'</span>, <span class="st">'not well'</span>), <span class="fu">c</span>(<span class="dv">7</span>, <span class="dv">5</span>))</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>pill_betters <span class="ot">&lt;-</span> <span class="fu">numeric</span>(n)</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n) {</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>    pill <span class="ot">&lt;-</span> <span class="fu">sample</span>(options, <span class="at">size=</span><span class="dv">6</span>, <span class="at">replace=</span><span class="cn">TRUE</span>)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>    pill_cures <span class="ot">&lt;-</span> <span class="fu">sum</span>(pill <span class="sc">==</span> <span class="st">'get well'</span>)</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>    placebo <span class="ot">&lt;-</span> <span class="fu">sample</span>(options, <span class="at">size=</span><span class="dv">6</span>, <span class="at">replace=</span><span class="cn">TRUE</span>)</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>    placebo_cures <span class="ot">&lt;-</span> <span class="fu">sum</span>(placebo <span class="sc">==</span> <span class="st">'get well'</span>)</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>    pill_betters[i] <span class="ot">&lt;-</span> pill_cures <span class="sc">-</span> placebo_cures</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(pill_betters, <span class="at">breaks=</span><span class="sc">-</span><span class="dv">6</span><span class="sc">:</span><span class="dv">6</span>,</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">'Number of extra cures pill vs placebo in null universe'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="testing_counts_1_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<p>Recall our actual observed results: In the medicine group, three more patients were cured than in the placebo group. From the histogram, we see that in only about 8 percent of the simulated trials did the “medicine” group do as well or better. The results seem to suggest — but by no means conclusively — that the medicine’s performance is not due to chance. Further study would probably be warranted. The following commands added to the above program will calculate this proportion directly:</p>
<p>End of <code>pill_placebo</code> notebook</p>
</div>
<!---
End of pill vs placebo notebook.
-->
<p>As I (JLS) wrote when I first proposed this bootstrap method in 1969, this method is not the standard way of handling the problem; it is not even analogous to the standard analytic difference-of-proportions method (though since then it has become widely accepted). Though the method shown is quite direct and satisfactory, there are also <em>many other</em> resampling methods that one might construct to solve the same problem. By all means, invent your own statistics rather than simply trying to copy the methods described here; the examples given here only illustrate the process of inventing statistics rather than offering solutions for all classes of problems.</p>
</section>
<section id="example-did-attitudes-about-marijuana-change" class="level3" data-number="21.2.5">
<h3 data-number="21.2.5" class="anchored" data-anchor-id="example-did-attitudes-about-marijuana-change"><span class="header-section-number">21.2.5</span> Example: Did Attitudes About Marijuana Change?</h3>
<!---
Example 8.18 in W+W 1990.  Looks like fake data.
-->
<p>Consider two polls, each asking 1500 Americans about marijuana legalization. One poll, taken in 1980, found 52 percent of respondents in favor of decriminalization; the other, taken in 1985, found 46 percent in favor of decriminalization <span class="citation" data-cites="wonnacott1990introductory">(<a href="references.html#ref-wonnacott1990introductory" role="doc-biblioref">Wonnacott and Wonnacott 1990, 275</a>)</span>. Our null (benchmark) hypothesis is that both samples came from the same universe (the universe made up of the total of the two sets of observations). If so, let us then ask how likely would be two polls to produce results as different as were observed? Hence we construct a universe with a mean of 49 percent (the mean of the two polls of 52 percent and 46 percent), and repeatedly draw pairs of samples of size 1500 from it.</p>
<p>To see how the construction of the appropriate question is much more challenging intellectually than is the actual mathematics, let us consider another possibility suggested by a student: What about considering the universe to be the earlier poll with a mean of 52 percent, and then asking the probability that the later poll of 1500 people with a mean of 46 percent would come from it? Indeed, on first thought that procedure seems reasonable.</p>
<p>Upon reflection — and it takes considerable thought on these matters to get them right — that would <em>not</em> be an appropriate procedure. The student’s suggested procedure would be the same as assuming that we had long-run solid knowledge of the universe, as if based on millions of observations, and then asking about the probability of a particular sample drawn from it. That does not correspond to the facts.</p>
<p>The only way to find the approach you eventually consider best — and there is no guarantee that it is indeed <em>correct</em> — is by close reference to the particular facts of the case.</p>
</section>
<section id="sec-framingham-example" class="level3" data-number="21.2.6">
<h3 data-number="21.2.6" class="anchored" data-anchor-id="sec-framingham-example"><span class="header-section-number">21.2.6</span> Example: Infarction and Cholesterol: Framingham Study</h3>
<p>It is so important to understand the logic of hypothesis tests, and of the resampling method of doing them, that we will now tackle another problem similar to the preceding one.</p>
<p>This will be the first of several problems that use data from the famous Framingham study (drawn from Kahn and Sempos <span class="citation" data-cites="kahn1989statistical">(<a href="references.html#ref-kahn1989statistical" role="doc-biblioref">1989</a>)</span>) concerning the development of myocardial infarction 16 years after the Framingham study began, for men ages 35- 44 with serum cholesterol above 250, compared to those with serum cholesterol below 250. The raw data are shown in <a href="#tbl-framingham-data" class="quarto-xref">Table&nbsp;<span>21.4</span></a>. The data are from <span class="citation" data-cites="shurtleff1970framingham">(<a href="references.html#ref-shurtleff1970framingham" role="doc-biblioref">Shurtleff 1970</a>)</span>, cited in <span class="citation" data-cites="kahn1989statistical">(<a href="references.html#ref-kahn1989statistical" role="doc-biblioref">Kahn and Sempos 1989, 12:61</a>, Table 3-8)</span>. Kahn and Sempos divided the cases into “high” and “low” cholesterol.</p>
<div id="tbl-framingham-data" class="anchored">
<table class="table">
<caption>Table&nbsp;21.4: Development of Myocardial Infarction in Men Aged 35-44 After 16 Years</caption>
<thead>
<tr class="header">
<th>Serum Cholesterol</th>
<th>Developed MI</th>
<th>Didn’t Develop MI</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>&gt; 250</td>
<td>10</td>
<td>125</td>
<td>135</td>
</tr>
<tr class="even">
<td>&lt;= 250</td>
<td>21</td>
<td>449</td>
<td>470</td>
</tr>
</tbody>
</table>
</div>
<p>The statistical logic properly begins by asking: How likely is that the two observed groups “really” came from the same “population” with respect to infarction rates? That is, we start with this question: How sure should one be that there is a difference in myocardial infarction rates between the high and low-cholesterol groups? Operationally, we address this issue by asking how likely it is that two groups as different in disease rates as the observed groups would be produced by the same “statistical universe.”</p>
<p>Key step: We assume that the relevant “benchmark” or “null hypothesis” population (universe) is the composite of the two observed groups. That is, if there were no “true” difference in infarction rates between the two serum-cholesterol groups, and the observed disease differences occurred just because of sampling variation, the most reasonable representation of the population from which they came is the composite of the two observed groups.</p>
<p>Therefore, we compose a hypothetical “benchmark” universe containing (135 + 470 =) 605 men at risk, and designate (10 + 21 =) 31 of them as infarction cases. We want to determine how likely it is that a universe like this one would produce — just by chance — two groups that differ as much as do the actually observed groups. That is, how often would random sampling from this universe produce one sub-sample of 135 men containing a large enough number of infarctions, and the other sub-sample of 470 men producing few enough infarctions, that the difference in occurrence rates would be as high as the observed difference of .029? (10/135 = .074, and 21/470 = .045, and .074 - .045 = .029).</p>
<p>So far, everything that has been said applies both to the conventional formulaic method and to the “new statistics” resampling method. But the logic is seldom explained to the reader of a piece of research — if indeed the researcher her/ himself grasps what the formula is doing. And if one just grabs for a formula with a prayer that it is the right one, one need never analyze the statistical logic of the problem at hand.</p>
<p>Now we tackle this problem with a method that you would think of yourself if you began with the following mind-set: How can I simulate the mechanism whose operation I wish to understand? These steps will do the job:</p>
<ul>
<li><strong>Step 1:</strong> Fill a bucket with 605 balls, 31 red (infarction) and the rest (605 — 31 = 574) green (no infarction).</li>
<li><strong>Step 2:</strong> Draw a sample of 135 (simulating the high serum-cholesterol group), one ball at a time and throwing it back after it is drawn to keep the simulated probability of an infarction the same throughout the sample; record the number of reds. Then do the same with another sample of 470 (the low serum-cholesterol group).</li>
<li><strong>Step 3:</strong> Calculate the difference in infarction rates for the two simulated groups, and compare it to the actual difference of .029; if the simulated difference is that large, record “Yes” for this trial; if not, record “No.”</li>
<li><strong>Step 4:</strong> Repeat steps 2 and 3 until a total of (say) 400 or 1000 trials have been completed. Compute the frequency with which the simulated groups produce a difference as great as actually observed. This frequency is an estimate of the probability that a difference as great as actually observed in Framingham would occur even if serum cholesterol has no effect upon myocardial infarction.</li>
</ul>
<p>The procedure above can be carried out with balls in a bucket in a few hours. Yet it is natural to seek the added convenience of the computer to draw the samples. Here is a R program:</p>
<div class="notebook" name="framingham_hearts" title="Framingham heart data">
<p>Start of <code>framingham_hearts</code> notebook</p>
<div class="nb-links">
<a class="notebook-link" href="notebooks/framingham_hearts.Rmd">Download notebook</a>
<a class="interact-button" href="https://resampling-stats.github.io/python-book/jupyterlite/lab/index.html?path=/framingham_hearts.Rmd">Interact</a>
</div>

<div class="cell" data-layout-align="center" data-hash="testing_counts_1_cache/html/unnamed-chunk-24_4890c4e39eb6b614c3c37b3e06e7c6f0">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>men <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">'infarction'</span>, <span class="st">'no infarction'</span>), <span class="fu">c</span>(<span class="dv">31</span>, <span class="dv">574</span>))</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>n_high <span class="ot">&lt;-</span> <span class="dv">135</span>  <span class="co"># Number of men with high cholesterol</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>n_low <span class="ot">&lt;-</span> <span class="dv">470</span>  <span class="co"># Number of men with low cholesterol</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a>infarct_differences <span class="ot">&lt;-</span> <span class="fu">numeric</span>(n)</span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n) {</span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a>    highs <span class="ot">&lt;-</span> <span class="fu">sample</span>(men, <span class="at">size=</span>n_high, <span class="at">replace=</span><span class="cn">TRUE</span>)</span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>    lows <span class="ot">&lt;-</span> <span class="fu">sample</span>(men, <span class="at">size=</span>n_low, <span class="at">replace=</span><span class="cn">TRUE</span>)</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>    high_infarcts <span class="ot">&lt;-</span> <span class="fu">sum</span>(highs <span class="sc">==</span> <span class="st">'infarction'</span>)</span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>    low_infarcts <span class="ot">&lt;-</span> <span class="fu">sum</span>(lows <span class="sc">==</span> <span class="st">'infarction'</span>)</span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>    high_prop <span class="ot">&lt;-</span> high_infarcts <span class="sc">/</span> n_high</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>    low_prop <span class="ot">&lt;-</span> low_infarcts <span class="sc">/</span> n_low</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>    infarct_differences[i] <span class="ot">&lt;-</span> high_prop <span class="sc">-</span> low_prop</span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(infarct_differences, <span class="at">breaks=</span><span class="fu">seq</span>(<span class="sc">-</span><span class="fl">0.1</span>, <span class="fl">0.1</span>, <span class="at">by=</span><span class="fl">0.005</span>),</span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">'Infarct proportion differences in null universe'</span>)</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a><span class="co"># How often was the resampled difference &gt;= the observed difference?</span></span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="fu">sum</span>(infarct_differences <span class="sc">&gt;=</span> <span class="fl">0.029</span>)</span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert this result to a proportion</span></span>
<span id="cb12-26"><a href="#cb12-26" aria-hidden="true" tabindex="-1"></a>kk <span class="ot">&lt;-</span> k <span class="sc">/</span> n</span>
<span id="cb12-27"><a href="#cb12-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-28"><a href="#cb12-28" aria-hidden="true" tabindex="-1"></a><span class="fu">message</span>(<span class="st">'Proportion of trials with difference &gt;= observed: '</span>,</span>
<span id="cb12-29"><a href="#cb12-29" aria-hidden="true" tabindex="-1"></a>        <span class="fu">round</span>(kk, <span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Proportion of trials with difference &gt;= observed: 0.1</code></pre>
</div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="testing_counts_1_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<p>The results of the test using this program may be seen in the histogram. We find — perhaps surprisingly — that a difference as large as observed would occur by chance around 10 percent of the time. (If we were not guided by the theoretical expectation that high serum cholesterol produces heart disease, we might include the 10 percent difference going in the other direction, giving a 20 percent chance). Even a ten percent chance is sufficient to call into question the conclusion that high serum cholesterol is dangerous. At a minimum, this statistical result should call for more research before taking any strong action clinically or otherwise.</p>
<p>End of <code>framingham_hearts</code> notebook</p>
</div>
<!---
End of Framingham notebook.
-->
<p>Where should one look to determine which procedures should be used to deal with a problem such as set forth above? Unlike the formulaic approach, the basic source is not a manual which sets forth a menu of formulas together with sets of rules about when they are appropriate. Rather, you consult your own understanding about what is happening in (say) the Framingham situation, and the question that needs to be answered, and then you construct a “model” that is as faithful to the facts as is possible. The bucket-sampling described above is such a model for the case at hand.</p>
<p>To connect up what we have done with the conventional approach, one could apply a z test (conceptually similar to the t test, but applicable to yes-no data; it is the Normal-distribution approximation to the large binomial distribution). Do so, we find that the results are much the same as the resampling result — an eleven percent probability.</p>
<p>Someone may ask: Why do a resampling test when you can use a standard device such as a z or t test? The great advantage of resampling is that it avoids using the wrong method. The researcher is more likely to arrive at sound conclusions with resampling because s/he can understand what s/he is doing, instead of blindly grabbing a formula which may be in error.</p>
<p>The textbook from which the problem is drawn is an excellent one; the difficulty of its presentation is an inescapable consequence of the formulaic approach to probability and statistics. The body of complex algebra and tables that only a rare expert understands down to the foundations constitutes an impenetrable wall to understanding. Yet without such understanding, there can be only rote practice, which leads to frustration and error.</p>
</section>
<section id="sec-pig-rations" class="level3" data-number="21.2.7">
<h3 data-number="21.2.7" class="anchored" data-anchor-id="sec-pig-rations"><span class="header-section-number">21.2.7</span> Example: Is One Pig Ration More Effective Than the Other?</h3>
<p><strong>Testing For a Difference in Means With a Two-by-Two Classification</strong>.</p>
<p>Each of two new types of ration is fed to twelve pigs. A farmer wants to know whether ration A or ration B is better.<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> The weight gains in pounds for pigs fed on rations A and B are:</p>
<p>A: 31, 34, 29, 26, 32, 35, 38, 34, 31, 29, 32, 31</p>
<p>B: 26, 24, 28, 29, 30, 29, 31, 29, 32, 26, 28, 32</p>
<p>The statistical question may be framed as follows: should one consider that the pigs fed on the different rations come from the same universe with respect to weight gains?</p>
<p>In the actual experiment, 9 of the 12 pigs who were fed ration A also were in the top half of weight gains. How likely is it that one group of 12 randomly-chosen pigs would contain 9 of the 12 top weight gainers?</p>
<p>One approach to the problem is to divide the pigs into two groups — the twelve with the highest weight gains, and the twelve with the lowest weight gains — and examine whether an unusually large number of high-weight-gain pigs were fed on one or the other of the rations.</p>
<p>We can make this test by ordering and grouping the twenty four pigs:</p>
<ul>
<li><strong>High-weight group:</strong> 38 (ration A), 35 (A), 34 (A), 34 (A), 32 (B), 32 (A), 32 (A), 32 (B), 31 (A), 31 (B), 31 (A), 31 (A)</li>
<li><strong>Low-weight group:</strong> 30 (B), 29 (A), 29 (A), 29 (B), 29 (B), 29 (B), 28 (B), 28 (B), 26 (A), 26 (B), 26 (B), 24 (B).</li>
</ul>
<p>Among the twelve high-weight-gain pigs, nine were fed on ration A. We ask: Is this further from an even split than we are likely to get by chance? Let us take twelve red and twelve black cards, shuffle them, and deal out twelve cards (the other twelve need not be dealt out). Count the proportion of the hands in which one ration comes up nine or more times in the first twelve cards, to reflect ration A’s appearance nine times among the highest twelve weight gains. More specifically:</p>
<ul>
<li><strong>Step 1.</strong> Constitute a deck of twelve red and twelve black cards, and shuffle.</li>
<li><strong>Step 2.</strong> Deal out twelve cards, count the number red, and record “yes” if there are nine or more of <em>either</em> red or black.</li>
<li><strong>Step 3.</strong> Repeat step 2 perhaps fifty times.</li>
<li><strong>Step 4.</strong> Compute the proportion “yes.” This proportion estimates the probability sought.</li>
</ul>
<div class="cell" data-layout-align="center" data-hash="testing_counts_1_cache/html/unnamed-chunk-26_2b11bfa8bdacf6f17cd0e156785c90c3">
<div class="cell-output-display">
<div id="tbl-pig-trials" class="anchored">
<table class="lightable-paper lightable-striped lightable-hover table table-sm table-striped small" data-quarto-postprocess="true">
<caption>Table&nbsp;21.5: Results from 25 random trials for pig rations</caption>
<thead>
<tr class="header">
<th style="text-align: right;" data-quarto-table-cell-role="th">Trial no</th>
<th style="text-align: right;" data-quarto-table-cell-role="th"># red</th>
<th style="text-align: right;" data-quarto-table-cell-role="th"># black</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">&gt;=9 red or black</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: right;">11</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: right;">12</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: right;">13</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">3</td>
<td style="text-align: left;">+</td>
</tr>
<tr class="even">
<td style="text-align: right;">14</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: right;">15</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">4</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: right;">16</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">8</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: right;">17</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: right;">18</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: right;">19</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: right;">20</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: right;">21</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: right;">22</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: right;">23</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;"></td>
</tr>
<tr class="even">
<td style="text-align: right;">24</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">7</td>
<td style="text-align: left;"></td>
</tr>
<tr class="odd">
<td style="text-align: right;">25</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">6</td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
</div>


</div>
</div>
<p><a href="#tbl-pig-trials" class="quarto-xref">Table&nbsp;<span>21.5</span></a> shows the results of 25 trials. In one (marked by + signs) of the 25 (that is, 4 percent of the trials) there were nine or more either red or black cards in the first twelve cards. Again the results suggest that it would be <em>slightly unusual</em> for the results to favor one ration or the other so strongly just by chance if they come from the same universe.</p>
<p>Now the R procedure to answer the question:</p>
<div class="notebook" name="pig_rations" title="Weight gain on pig rations">
<p>Start of <code>pig_rations</code> notebook</p>
<div class="nb-links">
<a class="notebook-link" href="notebooks/pig_rations.Rmd">Download notebook</a>
<a class="interact-button" href="https://resampling-stats.github.io/python-book/jupyterlite/lab/index.html?path=/pig_rations.Rmd">Interact</a>
</div>

<p>The <span class="r"><code>ranks &lt;- 1:24</code></span> statement creates a vector of numbers 1 through 24, which will represent the rankings of weight gains for each of the 24 pigs. We repeat the following procedure for 10000 trials. First we shuffle the elements of vector <code>ranks</code> so that the rank numbers for weight gains are randomized and placed in vector <code>shuffled</code>. We then select the first 12 elements of <code>shuffled</code> and place them in <code>first_12</code>; this represents the rankings of a randomly-selected group of 12 pigs. We next count (<code>sum</code>) in <code>n_top</code> the number of pigs whose rankings for weight gain were in the top half — that is, a rank of less than 13. We record that number in <code>top_ranks</code>, and then continue the loop, until we finish our <code>n</code> trials.</p>
<p>Since we did not know beforehand the direction of the effect of ration A on weight gain, we want to count the times that <em>either more than 8</em> of the random selection of 12 pigs were in the top half of the rankings, <em>or that fewer than 4</em> of these pigs were in the top half of the weight gain rankings — (The latter is the same as counting the number of times that more than 8 of the 12 <em>non-selected</em> random pigs were in the top half in weight gain.)</p>
<p>We do so with the final two <code>sum</code> statements. By adding the two results <code>n_gte_9</code> and <code>n_lte_3</code> together, we have the number of times out of 10,000 that differences in weight gains in two groups as dramatic as those obtained in the actual experiment would occur by chance.</p>
<div class="cell" data-layout-align="center" data-hash="testing_counts_1_cache/html/unnamed-chunk-28_c381f13aa7a786d83b3028d4fa0c659f">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Constitute the set of the weight gain rank orders. ranks is now a vector</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="co"># consisting of the numbers 1 — 24, in that order.</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>ranks <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">24</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>top_ranks <span class="ot">&lt;-</span> <span class="fu">numeric</span>(n)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n) {</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Shuffle the ranks of the weight gains.</span></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>    shuffled <span class="ot">&lt;-</span> <span class="fu">sample</span>(ranks)</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Take the first 12 ranks.</span></span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>    first_12 <span class="ot">&lt;-</span> shuffled[<span class="dv">1</span><span class="sc">:</span><span class="dv">12</span>]</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Determine how many of these randomly selected 12 ranks are less than</span></span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>    <span class="co"># 12 (i.e. 1-12), put that result in n_top.</span></span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>    n_top <span class="ot">&lt;-</span> <span class="fu">sum</span>(first_12 <span class="sc">&lt;=</span> <span class="dv">12</span>)</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Keep track of each trial result in top_ranks</span></span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>    top_ranks[i] <span class="ot">&lt;-</span> n_top</span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(top_ranks, <span class="at">breaks=</span><span class="dv">1</span><span class="sc">:</span><span class="dv">11</span>,</span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">'Number of top 12 ranks in pig-ration trials'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="testing_counts_1_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" style="width:70.0%"></p>
</figure>
</div>
</div>
</div>
<p>We see from the histogram that, in about 3 percent of the trials, either more than 8 or fewer than 4 top half ranks (1-12) made it into the random group of twelve that we selected. R will calculate this for us as follows:</p>
<div class="cell" data-layout-align="center" data-hash="testing_counts_1_cache/html/unnamed-chunk-30_0dd99237cd03dd1c06f93b83ca012399">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Determine how many of the trials yielded 9 or more top ranks.</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>n_gte_9 <span class="ot">&lt;-</span> <span class="fu">sum</span>(top_ranks <span class="sc">&gt;=</span> <span class="dv">9</span>)</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Determine how many trials yielded 3 or fewer of the top ranks.</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="co"># If there were 3 or fewer, then 9 or more of the top ranks must</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a><span class="co"># have been in the other group (not selected).</span></span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a>n_lte_3 <span class="ot">&lt;-</span> <span class="fu">sum</span>(top_ranks <span class="sc">&lt;=</span> <span class="dv">3</span>)</span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Add the two together.</span></span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>n_both <span class="ot">&lt;-</span> n_gte_9 <span class="sc">+</span> n_lte_3</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert to a proportion.</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>prop_both <span class="ot">&lt;-</span> n_both <span class="sc">/</span> n</span>
<span id="cb15-11"><a href="#cb15-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-12"><a href="#cb15-12" aria-hidden="true" tabindex="-1"></a><span class="fu">message</span>(<span class="st">'Trial proportion &gt;=9 top ranks in either group: '</span>,</span>
<span id="cb15-13"><a href="#cb15-13" aria-hidden="true" tabindex="-1"></a>        <span class="fu">round</span>(prop_both, <span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Trial proportion &gt;=9 top ranks in either group: 0.04</code></pre>
</div>
</div>
<p>The decisions that are warranted on the basis of the results depend upon one’s purpose. If writing a scientific paper on the merits of ration A is the ultimate purpose, it would be sensible to test another batch of pigs to get further evidence. (Or you could proceed to employ another sort of test for a slightly more precise evaluation.) But if the goal is a decision on which type of ration to buy for a small farm and they are the same price, just go ahead and buy ration A because, even if it is no better than ration B, you have strong evidence that it is <em>no worse</em> .</p>
<p>End of <code>pig_rations</code> notebook</p>
</div>
<!---
End of pig-ration notebook.
-->
</section>
<section id="example-do-planet-densities-differ" class="level3" data-number="21.2.8">
<h3 data-number="21.2.8" class="anchored" data-anchor-id="example-do-planet-densities-differ"><span class="header-section-number">21.2.8</span> Example: Do Planet Densities Differ?</h3>
<p><strong>Consider the five planets known to the ancient world.</strong></p>
<p>Mosteller and Rourke <span class="citation" data-cites="mosteller1973sturdy">(<a href="references.html#ref-mosteller1973sturdy" role="doc-biblioref">1973, 17–19</a>)</span> ask us to compare the densities of the three planets <em>farther</em> from the sun than is the earth (Mars, density 0.71; Jupiter, 0.24; and Saturn, 0.12) against the densities of the planets <em>closer</em> to the sun than is the earth (Mercury, 0.68; Venus, 0.94).</p>
<p>The average density of the distant planets is .357, of the closer planets is .81. Is this difference (.353) statistically surprising, or is it likely to occur in a chance ordering of these planets?</p>
<p>We can answer this question with a permutation test; such sampling without replacement makes sense here because we are considering the entire set of planets, rather than a sample drawn from a larger population of planets (the word “population” is used here, rather than “universe,” to avoid confusion.) And because the number of objects is so small, one could examine all possible arrangements (permutations), and see how many have (say) differences in mean densities between the two groups as large as observed.</p>
<p>Another method that Mosteller and Rourke suggest is by a comparison of the density <em>ranks</em> of the two sets, where Saturn has rank 1 and Venus has rank 5. This might have a scientific advantage if the sample data are dominated by a single “outlier,” whose domination is removed when we rank the data.</p>
<p>We see that the sum of the ranks for the “closer” set is 3+5=8. We can then ask: If the ranks were assigned at random, how likely is it that a set of two planets would have a sum as large as 8? Again, because the sample is small, we can examine all the possible permutations, as Mosteller and Rourke do in Table 3-1 <span class="citation" data-cites="mosteller1973sturdy">(<a href="references.html#ref-mosteller1973sturdy" role="doc-biblioref">Mosteller and Rourke 1973, 56</a>)</span> (Substitute “Closer” for “B,” “Further” for “A”). In two of the ten permutations, a sum of ranks as great as 8 is observed, so the probability of a result as great as observed happening by chance is 20 percent, using these data. (We could just as well consider the difference in mean ranks between the two groups: (8/2 - 7/3 = 10 / 6 = 1.67).</p>

<!---
Perhaps easier to reproduce M+R table here - no-one will have that reference to
hand.
-->
<p>To illuminate the logic of this test, consider comparing the heights of two samples of trees. If sample A has the five tallest trees, and sample B has the five shortest trees, the difference in mean ranks will be (6+7+8+9+10=) 40 — (1+2+3+4+5=) 15, the largest possible difference. If the groups are less sharply differentiated — for example, if sample A has #3 and sample B has #8 — the difference in ranks will be less than the maximum of 40, as you can quickly verify.</p>
<p>The method we have just used is called a Mann-Whitney test, though that label is usually applied when the data are too many to examine all the possible permutations; in that case one conventionally uses a table prepared by formula. In the case where there are too many for a complete permutation test, our resampling algorithm is as follows (though we’ll continue with the planets example):</p>
<ol type="1">
<li>Compute the mean ranks of the two groups.</li>
<li>Calculate the difference between the means computed in step 1.</li>
<li>Create a bucket containing the ranks from 1 to the number of observations (5, in the case of the planets)</li>
<li>Shuffle the ranks.</li>
<li>Since we are working with the ranked data, we must draw without replacement, because there can only be one #3, one #7, and so on. So draw the number of observations corresponding to the number of observations — 2 “Closer” and 3 “Further.”</li>
<li>Compute the mean ranks of the two simulated groups of planets.</li>
<li>Calculate the difference between the means computed in step 5 and record.</li>
<li>Repeat steps 4 through 7 perhaps 1000 times.</li>
<li>Count how often the shuffled difference in ranks exceeds the observed difference from step 2 (1.67).</li>
</ol>
<div class="notebook" name="planet_densities" title="Planet densities and distance">
<p>Start of <code>planet_densities</code> notebook</p>
<div class="nb-links">
<a class="notebook-link" href="notebooks/planet_densities.Rmd">Download notebook</a>
<a class="interact-button" href="https://resampling-stats.github.io/python-book/jupyterlite/lab/index.html?path=/planet_densities.Rmd">Interact</a>
</div>

<div class="cell" data-layout-align="center" data-hash="testing_counts_1_cache/html/unnamed-chunk-32_45f5d1b8e2007d7292250aac6c8289b2">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Steps 1 and 2.</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>actual_mean_diff <span class="ot">&lt;-</span> <span class="dv">8</span> <span class="sc">/</span> <span class="dv">2</span> <span class="sc">-</span> <span class="dv">7</span> <span class="sc">/</span> <span class="dv">3</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 3</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>ranks <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="dv">5</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>mean_differences <span class="ot">&lt;-</span> <span class="fu">numeric</span>(n)</span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span>n) {</span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Step 4</span></span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>    shuffled <span class="ot">&lt;-</span> <span class="fu">sample</span>(ranks)</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Step 5</span></span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>    closer <span class="ot">&lt;-</span> shuffled[<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>]  <span class="co"># First 2</span></span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>    further <span class="ot">&lt;-</span> shuffled[<span class="dv">3</span><span class="sc">:</span><span class="dv">5</span>] <span class="co"># Last 3</span></span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Step 6</span></span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a>    mean_close <span class="ot">&lt;-</span> <span class="fu">mean</span>(closer)</span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a>    mean_far <span class="ot">&lt;-</span> <span class="fu">mean</span>(further)</span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a>    <span class="co"># Step 7</span></span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>    mean_differences[i] <span class="ot">&lt;-</span> mean_close <span class="sc">-</span> mean_far</span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Step 9</span></span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a>k <span class="ot">&lt;-</span> <span class="fu">sum</span>(mean_differences <span class="sc">&gt;=</span> actual_mean_diff)</span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a>prob <span class="ot">&lt;-</span> k <span class="sc">/</span> n</span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a><span class="fu">message</span>(<span class="st">'Proportion of trials with mean difference &gt;= 1.67: '</span>,</span>
<span id="cb17-29"><a href="#cb17-29" aria-hidden="true" tabindex="-1"></a>        <span class="fu">round</span>(prob, <span class="dv">2</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Proportion of trials with mean difference &gt;= 1.67: 0.2</code></pre>
</div>
</div>
<p>Interpretation: 20 percent of the time, random shufflings produced a difference in ranks as great as or greater than observed. Hence, on the strength of this evidence, we should <em>not</em> conclude that there is a statistically surprising difference in densities between the further planets and the closer planets.</p>
<p>End of <code>planet_densities</code> notebook</p>
</div>
<!---
End of planets notebook.
-->
</section>
</section>
<section id="conclusion" class="level2" data-number="21.3">
<h2 data-number="21.3" class="anchored" data-anchor-id="conclusion"><span class="header-section-number">21.3</span> Conclusion</h2>
<p>This chapter has begun the actual work of testing hypotheses. The next chapter continues with discussion of somewhat more complex problems with counted data — more complex to think about, but no more difficult to actually treat mathematically with resampling simulation. If you have understood the general logic of the procedures used up until this point, you are in command of all the necessary conceptual knowledge to construct your own tests to answer any statistical question. A lot more practice, working on a variety of problems, obviously would help. But the key elements are simple: 1) Model the real situation accurately, 2) experiment with the model, and 3) compare the results of the model with the observed results.</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-dixon1983introduction" class="csl-entry" role="listitem">
Dixon, Wilfrid J, and Frank J Massey Jr. 1983. <span>“Introduction to Statistical Analysis.”</span>
</div>
<div id="ref-hodges1970basic" class="csl-entry" role="listitem">
Hodges Jr, Joseph Lawson, and Erich Leo Lehmann. 1970. <em>Basic Concepts of Probability and Statistics</em>. 2nd ed. San Francisco, California: <span>H</span>olden-<span>D</span>ay, <span>I</span>nc. <a href="https://archive.org/details/basicconceptsofp0000unse_m8m9">https://archive.org/details/basicconceptsofp0000unse_m8m9</a>.
</div>
<div id="ref-kahn1989statistical" class="csl-entry" role="listitem">
Kahn, Harold A, and Christopher T Sempos. 1989. <em>Statistical Methods in Epidemiology</em>. Vol. 12. Monographs in Epidemiology and Biostatistics. New <span>Y</span>ork: Oxford University Press. <a href="https://www.google.co.uk/books/edition/Statistical_Methods_in_Epidemiology/YERYAgAAQBAJ">https://www.google.co.uk/books/edition/Statistical_Methods_in_Epidemiology/YERYAgAAQBAJ</a>.
</div>
<div id="ref-mosteller1973sturdy" class="csl-entry" role="listitem">
Mosteller, Frederick, and Robert E. K. Rourke. 1973. <em>Sturdy Statistics: Nonparametrics and Order Statistics</em>. Addison-Wesley Publishing Company.
</div>
<div id="ref-shurtleff1970framingham" class="csl-entry" role="listitem">
Shurtleff, Dewey. 1970. <span>“Some Characteristics Related to the Incidence of Cardiovascular Disease and Death: Framingham Study, 16-Year Follow-up.”</span> Section 26. Edited by William B. Kannel and Tavia Gordon. The Framingham Study: An Epidemiological Investigation of Cardiovascular Disease. Washington, D.C.: <span>U.S. Government Printing Office</span>. <a href="https://upload.wikimedia.org/wikipedia/commons/6/6d/The_Framingham_study_-_an_epidemiological_investigation_of_cardiovascular_disease_sec.26_1970_%28IA_framinghamstudye00kann_25%29.pdf">https://upload.wikimedia.org/wikipedia/commons/6/6d/The_Framingham_study_-_an_epidemiological_investigation_of_cardiovascular_disease_sec.26_1970_%28IA_framinghamstudye00kann_25%29.pdf</a>.
</div>
<div id="ref-wonnacott1990introductory" class="csl-entry" role="listitem">
Wonnacott, Thomas H, and Ronald J Wonnacott. 1990. <em>Introductory Statistics</em>. 5th ed. New York: John Wiley &amp; Sons.
</div>
</div>
</section>
<aside id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>If you are very knowledgeable, you may do some in-between figuring (with what is known as “Bayesian analysis”), but leave this alone unless you know well what you are doing.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>The data for this example are based on Dixon and Massey <span class="citation" data-cites="dixon1983introduction">(<a href="references.html#ref-dixon1983introduction" role="doc-biblioref">1983, 124</a>)</span>, who offer an orthodox method of handling the problem with a t-test.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</aside>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./framing_questions.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Framing Statistical Questions</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./significance.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">The Concept of Statistical Significance in Testing Hypotheses</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>