# Sum of squared differences for pig rations


Here we are working on the question — are the observed differences
between pig ration measured weight gains for different rations greater
than we would expect to see as a result of random sampling in the
null-world.

```{r}
# Load data file.
rations_df <- read.csv('data/pig_rations.csv')
# Show the first six rows.
head(rations_df)
```

```{r}
# Get vectors for each ration.
# A
a_rows <- subset(rations_df, rations_df$ration == 'A')
a_weights <- a_rows$weight_gain
# B
b_rows <- subset(rations_df, rations_df$ration == 'B')
b_weights <- b_rows$weight_gain
# C
c_rows <- subset(rations_df, rations_df$ration == 'C')
c_weights <- c_rows$weight_gain
# D
d_rows <- subset(rations_df, rations_df$ration == 'D')
d_weights <- d_rows$weight_gain
# Concatenate into one long vector.
all_weights <- c(a_weights, b_weights, c_weights, d_weights)
# Show the concatenated vector.
all_weights
```

```{r}
n_trials <- 10000

# An vector to store the result of each trial.
results <- numeric(n_trials)

# Do 10000 trials
for (i in 1:n_trials) {
    # Shuffle all the weight gains.
    shuffled <- sample(all_weights)
    # Split into 4 now random samples.
    fake_a <- shuffled[1:12]
    fake_b <- shuffled[13:24]
    fake_c <- shuffled[25:36]
    fake_d <- shuffled[37:48]
    # Sum the weight gains for the 4 resamples.
    sum_a <- sum(fake_a)
    sum_b <- sum(fake_b)
    sum_c <- sum(fake_c)
    sum_d <- sum(fake_d)
    # Find the differences between all the possible pairs of resamples.
    a_b <- sum_a - sum_b
    a_c <- sum_a - sum_c
    a_d <- sum_a - sum_d
    b_c <- sum_b - sum_c
    b_d <- sum_b - sum_d
    c_d <- sum_c - sum_d
    # Put the differences into an vector.
    fake_diffs <- c(a_b, a_c, a_d, b_c, b_d, c_d)
    # Square them to give six squared differences.
    sq_fake_diffs <- fake_diffs ** 2
    # Sum the squares.
    sum_sq_fake_diffs <- sum(sq_fake_diffs)
    # Keep track of the total for each trial.
    results[i] <- sum_sq_fake_diffs
    # End one trial, go back and repeat until 10000 trials are complete.
}

# Produce a histogram of the trial results.
hist(results, breaks=25,
    main='Null distribution of sum of squared differences',
    xlab='Sum of squared differences in null world')

# Find out how many trials produced differences among groups as great as
# or greater than those observed.
k <- sum(results >= 5299)
# Convert to a proportion.
kk <- k / n_trials
# Print the result.
message('Number of sum of squared differences >= 5299: ', kk)
```
